//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetFacturaEServicios.ServicioResolucion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resolucion", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class Resolucion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveTecnicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVigenciaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVigenciaInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RangoFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RangoInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SetIdDianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionDianField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveTecnica {
            get {
                return this.ClaveTecnicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveTecnicaField, value) != true)) {
                    this.ClaveTecnicaField = value;
                    this.RaisePropertyChanged("ClaveTecnica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataKey {
            get {
                return this.DataKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DataKeyField, value) != true)) {
                    this.DataKeyField = value;
                    this.RaisePropertyChanged("DataKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaResolucion {
            get {
                return this.FechaResolucionField;
            }
            set {
                if ((this.FechaResolucionField.Equals(value) != true)) {
                    this.FechaResolucionField = value;
                    this.RaisePropertyChanged("FechaResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVigenciaFinal {
            get {
                return this.FechaVigenciaFinalField;
            }
            set {
                if ((this.FechaVigenciaFinalField.Equals(value) != true)) {
                    this.FechaVigenciaFinalField = value;
                    this.RaisePropertyChanged("FechaVigenciaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVigenciaInicial {
            get {
                return this.FechaVigenciaInicialField;
            }
            set {
                if ((this.FechaVigenciaInicialField.Equals(value) != true)) {
                    this.FechaVigenciaInicialField = value;
                    this.RaisePropertyChanged("FechaVigenciaInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroResolucion {
            get {
                return this.NumeroResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroResolucionField, value) != true)) {
                    this.NumeroResolucionField = value;
                    this.RaisePropertyChanged("NumeroResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RangoFinal {
            get {
                return this.RangoFinalField;
            }
            set {
                if ((this.RangoFinalField.Equals(value) != true)) {
                    this.RangoFinalField = value;
                    this.RaisePropertyChanged("RangoFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RangoInicial {
            get {
                return this.RangoInicialField;
            }
            set {
                if ((this.RangoInicialField.Equals(value) != true)) {
                    this.RangoInicialField = value;
                    this.RaisePropertyChanged("RangoInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SetIdDian {
            get {
                return this.SetIdDianField;
            }
            set {
                if ((object.ReferenceEquals(this.SetIdDianField, value) != true)) {
                    this.SetIdDianField = value;
                    this.RaisePropertyChanged("SetIdDian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VersionDian {
            get {
                return this.VersionDianField;
            }
            set {
                if ((this.VersionDianField.Equals(value) != true)) {
                    this.VersionDianField = value;
                    this.RaisePropertyChanged("VersionDian");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", ConfigurationName="ServicioResolucion.ServicioResolucion")]
    public interface ServicioResolucion {
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/TestResponse")]
        HGInetFacturaEServicios.ServicioResolucion.TestResponse Test(HGInetFacturaEServicios.ServicioResolucion.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/TestResponse")]
        System.IAsyncResult BeginTest(HGInetFacturaEServicios.ServicioResolucion.TestRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioResolucion.TestResponse EndTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/Consultar", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/ConsultarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibreriaGlobalHGInet.Error.Error), Action="Consultar", Name="Error")]
        HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse Consultar(HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/Consultar", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/ConsultarResponse")]
        System.IAsyncResult BeginConsultar(HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse EndConsultar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/ConsultarResolucion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/ConsultarResolucionRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibreriaGlobalHGInet.Error.Error), Action="ConsultarResolucion", Name="Error")]
        HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse ConsultarResolucion(HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/ConsultarResolucion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioResolucion/ConsultarResolucionRespo" +
            "nse")]
        System.IAsyncResult BeginConsultarResolucion(HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse EndConsultarResolucion(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consultar", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string DataKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=1)]
        public string Identificacion;
        
        public ConsultarRequest() {
        }
        
        public ConsultarRequest(string DataKey, string Identificacion) {
            this.DataKey = DataKey;
            this.Identificacion = Identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioResolucion.Resolucion> ConsultarResult;
        
        public ConsultarResponse() {
        }
        
        public ConsultarResponse(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioResolucion.Resolucion> ConsultarResult) {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarResolucion", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultarResolucionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public HGInetFacturaEServicios.ServicioResolucion.Resolucion Resolucion;
        
        public ConsultarResolucionRequest() {
        }
        
        public ConsultarResolucionRequest(HGInetFacturaEServicios.ServicioResolucion.Resolucion Resolucion) {
            this.Resolucion = Resolucion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarResolucionResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultarResolucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioResolucion.Resolucion> ConsultarResolucionResult;
        
        public ConsultarResolucionResponse() {
        }
        
        public ConsultarResolucionResponse(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioResolucion.Resolucion> ConsultarResolucionResult) {
            this.ConsultarResolucionResult = ConsultarResolucionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioResolucionChannel : HGInetFacturaEServicios.ServicioResolucion.ServicioResolucion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioResolucion.TestResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioResolucion.TestResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarResolucionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarResolucionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResolucionClient : System.ServiceModel.ClientBase<HGInetFacturaEServicios.ServicioResolucion.ServicioResolucion>, HGInetFacturaEServicios.ServicioResolucion.ServicioResolucion {
        
        private BeginOperationDelegate onBeginTestDelegate;
        
        private EndOperationDelegate onEndTestDelegate;
        
        private System.Threading.SendOrPostCallback onTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarDelegate;
        
        private EndOperationDelegate onEndConsultarDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarResolucionDelegate;
        
        private EndOperationDelegate onEndConsultarResolucionDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarResolucionCompletedDelegate;
        
        public ServicioResolucionClient() {
        }
        
        public ServicioResolucionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioResolucionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResolucionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResolucionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<TestCompletedEventArgs> TestCompleted;
        
        public event System.EventHandler<ConsultarCompletedEventArgs> ConsultarCompleted;
        
        public event System.EventHandler<ConsultarResolucionCompletedEventArgs> ConsultarResolucionCompleted;
        
        public HGInetFacturaEServicios.ServicioResolucion.TestResponse Test(HGInetFacturaEServicios.ServicioResolucion.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTest(HGInetFacturaEServicios.ServicioResolucion.TestRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioResolucion.TestResponse EndTest(System.IAsyncResult result) {
            return base.Channel.EndTest(result);
        }
        
        private System.IAsyncResult OnBeginTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioResolucion.TestRequest request = ((HGInetFacturaEServicios.ServicioResolucion.TestRequest)(inValues[0]));
            return this.BeginTest(request, callback, asyncState);
        }
        
        private object[] OnEndTest(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioResolucion.TestResponse retVal = this.EndTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestCompleted(object state) {
            if ((this.TestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestCompleted(this, new TestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestAsync(HGInetFacturaEServicios.ServicioResolucion.TestRequest request) {
            this.TestAsync(request, null);
        }
        
        public void TestAsync(HGInetFacturaEServicios.ServicioResolucion.TestRequest request, object userState) {
            if ((this.onBeginTestDelegate == null)) {
                this.onBeginTestDelegate = new BeginOperationDelegate(this.OnBeginTest);
            }
            if ((this.onEndTestDelegate == null)) {
                this.onEndTestDelegate = new EndOperationDelegate(this.OnEndTest);
            }
            if ((this.onTestCompletedDelegate == null)) {
                this.onTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestCompleted);
            }
            base.InvokeAsync(this.onBeginTestDelegate, new object[] {
                        request}, this.onEndTestDelegate, this.onTestCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse Consultar(HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request) {
            return base.Channel.Consultar(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultar(HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse EndConsultar(System.IAsyncResult result) {
            return base.Channel.EndConsultar(result);
        }
        
        private System.IAsyncResult OnBeginConsultar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request = ((HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest)(inValues[0]));
            return this.BeginConsultar(request, callback, asyncState);
        }
        
        private object[] OnEndConsultar(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioResolucion.ConsultarResponse retVal = this.EndConsultar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarCompleted(object state) {
            if ((this.ConsultarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarCompleted(this, new ConsultarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarAsync(HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request) {
            this.ConsultarAsync(request, null);
        }
        
        public void ConsultarAsync(HGInetFacturaEServicios.ServicioResolucion.ConsultarRequest request, object userState) {
            if ((this.onBeginConsultarDelegate == null)) {
                this.onBeginConsultarDelegate = new BeginOperationDelegate(this.OnBeginConsultar);
            }
            if ((this.onEndConsultarDelegate == null)) {
                this.onEndConsultarDelegate = new EndOperationDelegate(this.OnEndConsultar);
            }
            if ((this.onConsultarCompletedDelegate == null)) {
                this.onConsultarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarDelegate, new object[] {
                        request}, this.onEndConsultarDelegate, this.onConsultarCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse ConsultarResolucion(HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request) {
            return base.Channel.ConsultarResolucion(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultarResolucion(HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarResolucion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse EndConsultarResolucion(System.IAsyncResult result) {
            return base.Channel.EndConsultarResolucion(result);
        }
        
        private System.IAsyncResult OnBeginConsultarResolucion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request = ((HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest)(inValues[0]));
            return this.BeginConsultarResolucion(request, callback, asyncState);
        }
        
        private object[] OnEndConsultarResolucion(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionResponse retVal = this.EndConsultarResolucion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarResolucionCompleted(object state) {
            if ((this.ConsultarResolucionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarResolucionCompleted(this, new ConsultarResolucionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarResolucionAsync(HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request) {
            this.ConsultarResolucionAsync(request, null);
        }
        
        public void ConsultarResolucionAsync(HGInetFacturaEServicios.ServicioResolucion.ConsultarResolucionRequest request, object userState) {
            if ((this.onBeginConsultarResolucionDelegate == null)) {
                this.onBeginConsultarResolucionDelegate = new BeginOperationDelegate(this.OnBeginConsultarResolucion);
            }
            if ((this.onEndConsultarResolucionDelegate == null)) {
                this.onEndConsultarResolucionDelegate = new EndOperationDelegate(this.OnEndConsultarResolucion);
            }
            if ((this.onConsultarResolucionCompletedDelegate == null)) {
                this.onConsultarResolucionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarResolucionCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarResolucionDelegate, new object[] {
                        request}, this.onEndConsultarResolucionDelegate, this.onConsultarResolucionCompletedDelegate, userState);
        }
    }
}
