//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectronicaAudit.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FEHGIAuditoria : DbContext
    {
        public FEHGIAuditoria()
            : base("name=FEHGIAuditoria")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblSeguimientoAlertas> TblSeguimientoAlertas { get; set; }
        public virtual DbSet<TblAuditDocumentos> TblAuditDocumentos { get; set; }
        public virtual DbSet<TblAuditFormatos> TblAuditFormatos { get; set; }
        public virtual DbSet<TblLog> TblLog { get; set; }
    }
}
