//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectronicaAudit.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLog
    {
        public System.Guid Id { get; set; }
        public System.DateTime DatFecha { get; set; }
        public int IntCategoria { get; set; }
        public string StrCategoria { get; set; }
        public int IntTipo { get; set; }
        public string StrTipo { get; set; }
        public int IntAccion { get; set; }
        public string StrAccion { get; set; }
        public string StrMensaje { get; set; }
        public string StrExcepcion { get; set; }
        public string Strerror_custom { get; set; }
        public Nullable<int> StrLinea { get; set; }
        public string StrArchivo { get; set; }
        public string StrClase { get; set; }
        public string StrMetodo { get; set; }
        public string StrModulo { get; set; }
    }
}
