//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetFacturaEServicios.ServicioDocumento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class DocumentoRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AceptacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionAceptacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEstadoEnvioMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DescuentaSaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibreriaGlobalHGInet.Error.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFacturaEServicios.ServicioDocumento.RespuestaDian EstadoDianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaUltimoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoEnvioMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdPeticionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionObligadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoFinalizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlAnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlPdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlXmlUblField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Aceptacion {
            get {
                return this.AceptacionField;
            }
            set {
                if ((this.AceptacionField.Equals(value) != true)) {
                    this.AceptacionField = value;
                    this.RaisePropertyChanged("Aceptacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRegistro {
            get {
                return this.CodigoRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRegistroField, value) != true)) {
                    this.CodigoRegistroField = value;
                    this.RaisePropertyChanged("CodigoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cufe {
            get {
                return this.CufeField;
            }
            set {
                if ((object.ReferenceEquals(this.CufeField, value) != true)) {
                    this.CufeField = value;
                    this.RaisePropertyChanged("Cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionAceptacion {
            get {
                return this.DescripcionAceptacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionAceptacionField, value) != true)) {
                    this.DescripcionAceptacionField = value;
                    this.RaisePropertyChanged("DescripcionAceptacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstado {
            get {
                return this.DescripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEstadoField, value) != true)) {
                    this.DescripcionEstadoField = value;
                    this.RaisePropertyChanged("DescripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstadoEnvioMail {
            get {
                return this.DescripcionEstadoEnvioMailField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEstadoEnvioMailField, value) != true)) {
                    this.DescripcionEstadoEnvioMailField = value;
                    this.RaisePropertyChanged("DescripcionEstadoEnvioMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionProceso {
            get {
                return this.DescripcionProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionProcesoField, value) != true)) {
                    this.DescripcionProcesoField = value;
                    this.RaisePropertyChanged("DescripcionProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DescuentaSaldo {
            get {
                return this.DescuentaSaldoField;
            }
            set {
                if ((this.DescuentaSaldoField.Equals(value) != true)) {
                    this.DescuentaSaldoField = value;
                    this.RaisePropertyChanged("DescuentaSaldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentoTipo {
            get {
                return this.DocumentoTipoField;
            }
            set {
                if ((this.DocumentoTipoField.Equals(value) != true)) {
                    this.DocumentoTipoField = value;
                    this.RaisePropertyChanged("DocumentoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibreriaGlobalHGInet.Error.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFacturaEServicios.ServicioDocumento.RespuestaDian EstadoDian {
            get {
                return this.EstadoDianField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoDianField, value) != true)) {
                    this.EstadoDianField = value;
                    this.RaisePropertyChanged("EstadoDian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRecepcion {
            get {
                return this.FechaRecepcionField;
            }
            set {
                if ((this.FechaRecepcionField.Equals(value) != true)) {
                    this.FechaRecepcionField = value;
                    this.RaisePropertyChanged("FechaRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaUltimoProceso {
            get {
                return this.FechaUltimoProcesoField;
            }
            set {
                if ((this.FechaUltimoProcesoField.Equals(value) != true)) {
                    this.FechaUltimoProcesoField = value;
                    this.RaisePropertyChanged("FechaUltimoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoEnvioMail {
            get {
                return this.IdEstadoEnvioMailField;
            }
            set {
                if ((this.IdEstadoEnvioMailField.Equals(value) != true)) {
                    this.IdEstadoEnvioMailField = value;
                    this.RaisePropertyChanged("IdEstadoEnvioMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdPeticion {
            get {
                return this.IdPeticionField;
            }
            set {
                if ((this.IdPeticionField.Equals(value) != true)) {
                    this.IdPeticionField = value;
                    this.RaisePropertyChanged("IdPeticion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdPlan {
            get {
                return this.IdPlanField;
            }
            set {
                if ((this.IdPlanField.Equals(value) != true)) {
                    this.IdPlanField = value;
                    this.RaisePropertyChanged("IdPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProceso {
            get {
                return this.IdProcesoField;
            }
            set {
                if ((this.IdProcesoField.Equals(value) != true)) {
                    this.IdProcesoField = value;
                    this.RaisePropertyChanged("IdProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionObligado {
            get {
                return this.IdentificacionObligadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionObligadoField, value) != true)) {
                    this.IdentificacionObligadoField = value;
                    this.RaisePropertyChanged("IdentificacionObligado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoRechazo {
            get {
                return this.MotivoRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoRechazoField, value) != true)) {
                    this.MotivoRechazoField = value;
                    this.RaisePropertyChanged("MotivoRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroResolucion {
            get {
                return this.NumeroResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroResolucionField, value) != true)) {
                    this.NumeroResolucionField = value;
                    this.RaisePropertyChanged("NumeroResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcesoFinalizado {
            get {
                return this.ProcesoFinalizadoField;
            }
            set {
                if ((this.ProcesoFinalizadoField.Equals(value) != true)) {
                    this.ProcesoFinalizadoField = value;
                    this.RaisePropertyChanged("ProcesoFinalizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlAnexo {
            get {
                return this.UrlAnexoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlAnexoField, value) != true)) {
                    this.UrlAnexoField = value;
                    this.RaisePropertyChanged("UrlAnexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlAuditoria {
            get {
                return this.UrlAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlAuditoriaField, value) != true)) {
                    this.UrlAuditoriaField = value;
                    this.RaisePropertyChanged("UrlAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlPdf {
            get {
                return this.UrlPdfField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlPdfField, value) != true)) {
                    this.UrlPdfField = value;
                    this.RaisePropertyChanged("UrlPdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlXmlUbl {
            get {
                return this.UrlXmlUblField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlXmlUblField, value) != true)) {
                    this.UrlXmlUblField = value;
                    this.RaisePropertyChanged("UrlXmlUbl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDian", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class RespuestaDian : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlXmlRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoDocumento {
            get {
                return this.EstadoDocumentoField;
            }
            set {
                if ((this.EstadoDocumentoField.Equals(value) != true)) {
                    this.EstadoDocumentoField = value;
                    this.RaisePropertyChanged("EstadoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConsulta {
            get {
                return this.FechaConsultaField;
            }
            set {
                if ((this.FechaConsultaField.Equals(value) != true)) {
                    this.FechaConsultaField = value;
                    this.RaisePropertyChanged("FechaConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlXmlRespuesta {
            get {
                return this.UrlXmlRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlXmlRespuestaField, value) != true)) {
                    this.UrlXmlRespuestaField = value;
                    this.RaisePropertyChanged("UrlXmlRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoArchivo", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class DocumentoArchivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ArchivoXmlUblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ArchivoXmlUbl {
            get {
                return this.ArchivoXmlUblField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoXmlUblField, value) != true)) {
                    this.ArchivoXmlUblField = value;
                    this.RaisePropertyChanged("ArchivoXmlUbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRegistro {
            get {
                return this.CodigoRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRegistroField, value) != true)) {
                    this.CodigoRegistroField = value;
                    this.RaisePropertyChanged("CodigoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataKey {
            get {
                return this.DataKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DataKeyField, value) != true)) {
                    this.DataKeyField = value;
                    this.RaisePropertyChanged("DataKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroResolucion {
            get {
                return this.NumeroResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroResolucionField, value) != true)) {
                    this.NumeroResolucionField = value;
                    this.RaisePropertyChanged("NumeroResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", ConfigurationName="ServicioDocumento.ServicioDocumentos")]
    public interface ServicioDocumentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/TestResponse")]
        HGInetFacturaEServicios.ServicioDocumento.TestResponse Test(HGInetFacturaEServicios.ServicioDocumento.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/TestResponse")]
        System.IAsyncResult BeginTest(HGInetFacturaEServicios.ServicioDocumento.TestRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioDocumento.TestResponse EndTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorNumeros", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorNumerosRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibreriaGlobalHGInet.Error.Error), Action="ConsultaPorNumeros", Name="Error")]
        HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse ConsultaPorNumeros(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorNumeros", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorNumerosRespon" +
            "se")]
        System.IAsyncResult BeginConsultaPorNumeros(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse EndConsultaPorNumeros(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorCodigoRegistr" +
            "o", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorCodigoRegistr" +
            "oResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibreriaGlobalHGInet.Error.Error), Action="ConsultaPorCodigoRegistro", Name="Error")]
        HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse ConsultaPorCodigoRegistro(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorCodigoRegistr" +
            "o", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorCodigoRegistr" +
            "oResponse")]
        System.IAsyncResult BeginConsultaPorCodigoRegistro(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse EndConsultaPorCodigoRegistro(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorFechaElaborac" +
            "ion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorFechaElaborac" +
            "ionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibreriaGlobalHGInet.Error.Error), Action="ConsultaPorFechaElaboracion", Name="Error")]
        HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse ConsultaPorFechaElaboracion(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorFechaElaborac" +
            "ion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/ConsultaPorFechaElaborac" +
            "ionResponse")]
        System.IAsyncResult BeginConsultaPorFechaElaboracion(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse EndConsultaPorFechaElaboracion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/Recepcion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/RecepcionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibreriaGlobalHGInet.Error.Error), Action="Recepcion", Name="Error")]
        HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse Recepcion(HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/Recepcion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioDocumentos/RecepcionResponse")]
        System.IAsyncResult BeginRecepcion(HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse EndRecepcion(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorNumeros", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorNumerosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string DataKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=1)]
        public string Identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=2)]
        public int TipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=3)]
        public string Numeros;
        
        public ConsultaPorNumerosRequest() {
        }
        
        public ConsultaPorNumerosRequest(string DataKey, string Identificacion, int TipoDocumento, string Numeros) {
            this.DataKey = DataKey;
            this.Identificacion = Identificacion;
            this.TipoDocumento = TipoDocumento;
            this.Numeros = Numeros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorNumerosResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorNumerosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> ConsultaPorNumerosResult;
        
        public ConsultaPorNumerosResponse() {
        }
        
        public ConsultaPorNumerosResponse(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> ConsultaPorNumerosResult) {
            this.ConsultaPorNumerosResult = ConsultaPorNumerosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorCodigoRegistro", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorCodigoRegistroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string DataKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=1)]
        public string Identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=2)]
        public int TipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=3)]
        public string CodigosRegistros;
        
        public ConsultaPorCodigoRegistroRequest() {
        }
        
        public ConsultaPorCodigoRegistroRequest(string DataKey, string Identificacion, int TipoDocumento, string CodigosRegistros) {
            this.DataKey = DataKey;
            this.Identificacion = Identificacion;
            this.TipoDocumento = TipoDocumento;
            this.CodigosRegistros = CodigosRegistros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorCodigoRegistroResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorCodigoRegistroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> ConsultaPorCodigoRegistroResult;
        
        public ConsultaPorCodigoRegistroResponse() {
        }
        
        public ConsultaPorCodigoRegistroResponse(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> ConsultaPorCodigoRegistroResult) {
            this.ConsultaPorCodigoRegistroResult = ConsultaPorCodigoRegistroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorFechaElaboracion", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorFechaElaboracionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string DataKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=1)]
        public string Identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=2)]
        public int TipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=3)]
        public System.DateTime FechaInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=4)]
        public System.DateTime FechaFinal;
        
        public ConsultaPorFechaElaboracionRequest() {
        }
        
        public ConsultaPorFechaElaboracionRequest(string DataKey, string Identificacion, int TipoDocumento, System.DateTime FechaInicial, System.DateTime FechaFinal) {
            this.DataKey = DataKey;
            this.Identificacion = Identificacion;
            this.TipoDocumento = TipoDocumento;
            this.FechaInicial = FechaInicial;
            this.FechaFinal = FechaFinal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorFechaElaboracionResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorFechaElaboracionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> ConsultaPorFechaElaboracionResult;
        
        public ConsultaPorFechaElaboracionResponse() {
        }
        
        public ConsultaPorFechaElaboracionResponse(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> ConsultaPorFechaElaboracionResult) {
            this.ConsultaPorFechaElaboracionResult = ConsultaPorFechaElaboracionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Recepcion", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class RecepcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoArchivo> documentos;
        
        public RecepcionRequest() {
        }
        
        public RecepcionRequest(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoArchivo> documentos) {
            this.documentos = documentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class RecepcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> RecepcionResult;
        
        public RecepcionResponse() {
        }
        
        public RecepcionResponse(System.Collections.Generic.List<HGInetFacturaEServicios.ServicioDocumento.DocumentoRespuesta> RecepcionResult) {
            this.RecepcionResult = RecepcionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDocumentosChannel : HGInetFacturaEServicios.ServicioDocumento.ServicioDocumentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.TestResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioDocumento.TestResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaPorNumerosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaPorNumerosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaPorCodigoRegistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaPorCodigoRegistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaPorFechaElaboracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaPorFechaElaboracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RecepcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDocumentosClient : System.ServiceModel.ClientBase<HGInetFacturaEServicios.ServicioDocumento.ServicioDocumentos>, HGInetFacturaEServicios.ServicioDocumento.ServicioDocumentos {
        
        private BeginOperationDelegate onBeginTestDelegate;
        
        private EndOperationDelegate onEndTestDelegate;
        
        private System.Threading.SendOrPostCallback onTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaPorNumerosDelegate;
        
        private EndOperationDelegate onEndConsultaPorNumerosDelegate;
        
        private System.Threading.SendOrPostCallback onConsultaPorNumerosCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaPorCodigoRegistroDelegate;
        
        private EndOperationDelegate onEndConsultaPorCodigoRegistroDelegate;
        
        private System.Threading.SendOrPostCallback onConsultaPorCodigoRegistroCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaPorFechaElaboracionDelegate;
        
        private EndOperationDelegate onEndConsultaPorFechaElaboracionDelegate;
        
        private System.Threading.SendOrPostCallback onConsultaPorFechaElaboracionCompletedDelegate;
        
        private BeginOperationDelegate onBeginRecepcionDelegate;
        
        private EndOperationDelegate onEndRecepcionDelegate;
        
        private System.Threading.SendOrPostCallback onRecepcionCompletedDelegate;
        
        public ServicioDocumentosClient() {
        }
        
        public ServicioDocumentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDocumentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDocumentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDocumentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<TestCompletedEventArgs> TestCompleted;
        
        public event System.EventHandler<ConsultaPorNumerosCompletedEventArgs> ConsultaPorNumerosCompleted;
        
        public event System.EventHandler<ConsultaPorCodigoRegistroCompletedEventArgs> ConsultaPorCodigoRegistroCompleted;
        
        public event System.EventHandler<ConsultaPorFechaElaboracionCompletedEventArgs> ConsultaPorFechaElaboracionCompleted;
        
        public event System.EventHandler<RecepcionCompletedEventArgs> RecepcionCompleted;
        
        public HGInetFacturaEServicios.ServicioDocumento.TestResponse Test(HGInetFacturaEServicios.ServicioDocumento.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTest(HGInetFacturaEServicios.ServicioDocumento.TestRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioDocumento.TestResponse EndTest(System.IAsyncResult result) {
            return base.Channel.EndTest(result);
        }
        
        private System.IAsyncResult OnBeginTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioDocumento.TestRequest request = ((HGInetFacturaEServicios.ServicioDocumento.TestRequest)(inValues[0]));
            return this.BeginTest(request, callback, asyncState);
        }
        
        private object[] OnEndTest(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioDocumento.TestResponse retVal = this.EndTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestCompleted(object state) {
            if ((this.TestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestCompleted(this, new TestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestAsync(HGInetFacturaEServicios.ServicioDocumento.TestRequest request) {
            this.TestAsync(request, null);
        }
        
        public void TestAsync(HGInetFacturaEServicios.ServicioDocumento.TestRequest request, object userState) {
            if ((this.onBeginTestDelegate == null)) {
                this.onBeginTestDelegate = new BeginOperationDelegate(this.OnBeginTest);
            }
            if ((this.onEndTestDelegate == null)) {
                this.onEndTestDelegate = new EndOperationDelegate(this.OnEndTest);
            }
            if ((this.onTestCompletedDelegate == null)) {
                this.onTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestCompleted);
            }
            base.InvokeAsync(this.onBeginTestDelegate, new object[] {
                        request}, this.onEndTestDelegate, this.onTestCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse ConsultaPorNumeros(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request) {
            return base.Channel.ConsultaPorNumeros(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultaPorNumeros(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaPorNumeros(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse EndConsultaPorNumeros(System.IAsyncResult result) {
            return base.Channel.EndConsultaPorNumeros(result);
        }
        
        private System.IAsyncResult OnBeginConsultaPorNumeros(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request = ((HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest)(inValues[0]));
            return this.BeginConsultaPorNumeros(request, callback, asyncState);
        }
        
        private object[] OnEndConsultaPorNumeros(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosResponse retVal = this.EndConsultaPorNumeros(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaPorNumerosCompleted(object state) {
            if ((this.ConsultaPorNumerosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaPorNumerosCompleted(this, new ConsultaPorNumerosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaPorNumerosAsync(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request) {
            this.ConsultaPorNumerosAsync(request, null);
        }
        
        public void ConsultaPorNumerosAsync(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorNumerosRequest request, object userState) {
            if ((this.onBeginConsultaPorNumerosDelegate == null)) {
                this.onBeginConsultaPorNumerosDelegate = new BeginOperationDelegate(this.OnBeginConsultaPorNumeros);
            }
            if ((this.onEndConsultaPorNumerosDelegate == null)) {
                this.onEndConsultaPorNumerosDelegate = new EndOperationDelegate(this.OnEndConsultaPorNumeros);
            }
            if ((this.onConsultaPorNumerosCompletedDelegate == null)) {
                this.onConsultaPorNumerosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaPorNumerosCompleted);
            }
            base.InvokeAsync(this.onBeginConsultaPorNumerosDelegate, new object[] {
                        request}, this.onEndConsultaPorNumerosDelegate, this.onConsultaPorNumerosCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse ConsultaPorCodigoRegistro(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request) {
            return base.Channel.ConsultaPorCodigoRegistro(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultaPorCodigoRegistro(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaPorCodigoRegistro(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse EndConsultaPorCodigoRegistro(System.IAsyncResult result) {
            return base.Channel.EndConsultaPorCodigoRegistro(result);
        }
        
        private System.IAsyncResult OnBeginConsultaPorCodigoRegistro(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request = ((HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest)(inValues[0]));
            return this.BeginConsultaPorCodigoRegistro(request, callback, asyncState);
        }
        
        private object[] OnEndConsultaPorCodigoRegistro(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroResponse retVal = this.EndConsultaPorCodigoRegistro(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaPorCodigoRegistroCompleted(object state) {
            if ((this.ConsultaPorCodigoRegistroCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaPorCodigoRegistroCompleted(this, new ConsultaPorCodigoRegistroCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaPorCodigoRegistroAsync(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request) {
            this.ConsultaPorCodigoRegistroAsync(request, null);
        }
        
        public void ConsultaPorCodigoRegistroAsync(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorCodigoRegistroRequest request, object userState) {
            if ((this.onBeginConsultaPorCodigoRegistroDelegate == null)) {
                this.onBeginConsultaPorCodigoRegistroDelegate = new BeginOperationDelegate(this.OnBeginConsultaPorCodigoRegistro);
            }
            if ((this.onEndConsultaPorCodigoRegistroDelegate == null)) {
                this.onEndConsultaPorCodigoRegistroDelegate = new EndOperationDelegate(this.OnEndConsultaPorCodigoRegistro);
            }
            if ((this.onConsultaPorCodigoRegistroCompletedDelegate == null)) {
                this.onConsultaPorCodigoRegistroCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaPorCodigoRegistroCompleted);
            }
            base.InvokeAsync(this.onBeginConsultaPorCodigoRegistroDelegate, new object[] {
                        request}, this.onEndConsultaPorCodigoRegistroDelegate, this.onConsultaPorCodigoRegistroCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse ConsultaPorFechaElaboracion(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request) {
            return base.Channel.ConsultaPorFechaElaboracion(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultaPorFechaElaboracion(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaPorFechaElaboracion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse EndConsultaPorFechaElaboracion(System.IAsyncResult result) {
            return base.Channel.EndConsultaPorFechaElaboracion(result);
        }
        
        private System.IAsyncResult OnBeginConsultaPorFechaElaboracion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request = ((HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest)(inValues[0]));
            return this.BeginConsultaPorFechaElaboracion(request, callback, asyncState);
        }
        
        private object[] OnEndConsultaPorFechaElaboracion(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionResponse retVal = this.EndConsultaPorFechaElaboracion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaPorFechaElaboracionCompleted(object state) {
            if ((this.ConsultaPorFechaElaboracionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaPorFechaElaboracionCompleted(this, new ConsultaPorFechaElaboracionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaPorFechaElaboracionAsync(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request) {
            this.ConsultaPorFechaElaboracionAsync(request, null);
        }
        
        public void ConsultaPorFechaElaboracionAsync(HGInetFacturaEServicios.ServicioDocumento.ConsultaPorFechaElaboracionRequest request, object userState) {
            if ((this.onBeginConsultaPorFechaElaboracionDelegate == null)) {
                this.onBeginConsultaPorFechaElaboracionDelegate = new BeginOperationDelegate(this.OnBeginConsultaPorFechaElaboracion);
            }
            if ((this.onEndConsultaPorFechaElaboracionDelegate == null)) {
                this.onEndConsultaPorFechaElaboracionDelegate = new EndOperationDelegate(this.OnEndConsultaPorFechaElaboracion);
            }
            if ((this.onConsultaPorFechaElaboracionCompletedDelegate == null)) {
                this.onConsultaPorFechaElaboracionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaPorFechaElaboracionCompleted);
            }
            base.InvokeAsync(this.onBeginConsultaPorFechaElaboracionDelegate, new object[] {
                        request}, this.onEndConsultaPorFechaElaboracionDelegate, this.onConsultaPorFechaElaboracionCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse Recepcion(HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request) {
            return base.Channel.Recepcion(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRecepcion(HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecepcion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse EndRecepcion(System.IAsyncResult result) {
            return base.Channel.EndRecepcion(result);
        }
        
        private System.IAsyncResult OnBeginRecepcion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request = ((HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest)(inValues[0]));
            return this.BeginRecepcion(request, callback, asyncState);
        }
        
        private object[] OnEndRecepcion(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioDocumento.RecepcionResponse retVal = this.EndRecepcion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRecepcionCompleted(object state) {
            if ((this.RecepcionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecepcionCompleted(this, new RecepcionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecepcionAsync(HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request) {
            this.RecepcionAsync(request, null);
        }
        
        public void RecepcionAsync(HGInetFacturaEServicios.ServicioDocumento.RecepcionRequest request, object userState) {
            if ((this.onBeginRecepcionDelegate == null)) {
                this.onBeginRecepcionDelegate = new BeginOperationDelegate(this.OnBeginRecepcion);
            }
            if ((this.onEndRecepcionDelegate == null)) {
                this.onEndRecepcionDelegate = new EndOperationDelegate(this.OnEndRecepcion);
            }
            if ((this.onRecepcionCompletedDelegate == null)) {
                this.onRecepcionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecepcionCompleted);
            }
            base.InvokeAsync(this.onBeginRecepcionDelegate, new object[] {
                        request}, this.onEndRecepcionDelegate, this.onRecepcionCompletedDelegate, userState);
        }
    }
}
