//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetFeAPI.ServicioReenvioDocumento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnvioDocumento", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class EnvioDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionFacturadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RadicadoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataKey {
            get {
                return this.DataKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DataKeyField, value) != true)) {
                    this.DataKeyField = value;
                    this.RaisePropertyChanged("DataKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionFacturador {
            get {
                return this.IdentificacionFacturadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionFacturadorField, value) != true)) {
                    this.IdentificacionFacturadorField = value;
                    this.RaisePropertyChanged("IdentificacionFacturador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RadicadoDocumento {
            get {
                return this.RadicadoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.RadicadoDocumentoField, value) != true)) {
                    this.RadicadoDocumentoField = value;
                    this.RaisePropertyChanged("RadicadoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificacionCorreo", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class NotificacionCorreo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSeguridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSeguridad {
            get {
                return this.IdSeguridadField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSeguridadField, value) != true)) {
                    this.IdSeguridadField = value;
                    this.RaisePropertyChanged("IdSeguridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFeAPI.ServicioReenvioDocumento.CodigoError CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFeAPI.ServicioReenvioDocumento.CodigoError Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodigoError", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    public enum CodigoError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_NO_CONTROLADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EN_SERVIDOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VALIDACION = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_AGREGAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EDITAR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_ELIMINAR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_LICENCIA = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NINGUNO = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", ConfigurationName="ServicioReenvioDocumento.ServicioReenvioDocumento")]
    public interface ServicioReenvioDocumento {
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/TestResponse")]
        HGInetFeAPI.ServicioReenvioDocumento.TestResponse Test(HGInetFeAPI.ServicioReenvioDocumento.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/TestResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioReenvioDocumento.TestResponse> TestAsync(HGInetFeAPI.ServicioReenvioDocumento.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/Recepcion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/RecepcionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HGInetFeAPI.ServicioReenvioDocumento.Error), Action="Recepcion", Name="Error")]
        HGInetFeAPI.ServicioReenvioDocumento.RecepcionResponse Recepcion(HGInetFeAPI.ServicioReenvioDocumento.RecepcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/Recepcion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioReenvioDocumento/RecepcionResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioReenvioDocumento.RecepcionResponse> RecepcionAsync(HGInetFeAPI.ServicioReenvioDocumento.RecepcionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Recepcion", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class RecepcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFeAPI.ServicioReenvioDocumento.EnvioDocumento> documentos;
        
        public RecepcionRequest() {
        }
        
        public RecepcionRequest(System.Collections.Generic.List<HGInetFeAPI.ServicioReenvioDocumento.EnvioDocumento> documentos) {
            this.documentos = documentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class RecepcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFeAPI.ServicioReenvioDocumento.NotificacionCorreo> RecepcionResult;
        
        public RecepcionResponse() {
        }
        
        public RecepcionResponse(System.Collections.Generic.List<HGInetFeAPI.ServicioReenvioDocumento.NotificacionCorreo> RecepcionResult) {
            this.RecepcionResult = RecepcionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioReenvioDocumentoChannel : HGInetFeAPI.ServicioReenvioDocumento.ServicioReenvioDocumento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReenvioDocumentoClient : System.ServiceModel.ClientBase<HGInetFeAPI.ServicioReenvioDocumento.ServicioReenvioDocumento>, HGInetFeAPI.ServicioReenvioDocumento.ServicioReenvioDocumento {
        
        public ServicioReenvioDocumentoClient() {
        }
        
        public ServicioReenvioDocumentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReenvioDocumentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReenvioDocumentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReenvioDocumentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HGInetFeAPI.ServicioReenvioDocumento.TestResponse Test(HGInetFeAPI.ServicioReenvioDocumento.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioReenvioDocumento.TestResponse> TestAsync(HGInetFeAPI.ServicioReenvioDocumento.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public HGInetFeAPI.ServicioReenvioDocumento.RecepcionResponse Recepcion(HGInetFeAPI.ServicioReenvioDocumento.RecepcionRequest request) {
            return base.Channel.Recepcion(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioReenvioDocumento.RecepcionResponse> RecepcionAsync(HGInetFeAPI.ServicioReenvioDocumento.RecepcionRequest request) {
            return base.Channel.RecepcionAsync(request);
        }
    }
}
