//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetFacturaEServicios.ServicioNotaDebito {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaDebito", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class NotaDebito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio")]
    [System.SerializableAttribute()]
    public partial class DocumentoRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AceptacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFacturaEServicios.ServicioNotaDebito.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaUltimoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUltimoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoFinalizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltimoProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlPdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlXmlUblField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Aceptacion {
            get {
                return this.AceptacionField;
            }
            set {
                if ((this.AceptacionField.Equals(value) != true)) {
                    this.AceptacionField = value;
                    this.RaisePropertyChanged("Aceptacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRegistro {
            get {
                return this.CodigoRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRegistroField, value) != true)) {
                    this.CodigoRegistroField = value;
                    this.RaisePropertyChanged("CodigoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cufe {
            get {
                return this.CufeField;
            }
            set {
                if ((object.ReferenceEquals(this.CufeField, value) != true)) {
                    this.CufeField = value;
                    this.RaisePropertyChanged("Cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionProceso {
            get {
                return this.DescripcionProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionProcesoField, value) != true)) {
                    this.DescripcionProcesoField = value;
                    this.RaisePropertyChanged("DescripcionProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFacturaEServicios.ServicioNotaDebito.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRecepcion {
            get {
                return this.FechaRecepcionField;
            }
            set {
                if ((this.FechaRecepcionField.Equals(value) != true)) {
                    this.FechaRecepcionField = value;
                    this.RaisePropertyChanged("FechaRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaUltimoProceso {
            get {
                return this.FechaUltimoProcesoField;
            }
            set {
                if ((this.FechaUltimoProcesoField.Equals(value) != true)) {
                    this.FechaUltimoProcesoField = value;
                    this.RaisePropertyChanged("FechaUltimoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProceso {
            get {
                return this.IdProcesoField;
            }
            set {
                if ((this.IdProcesoField.Equals(value) != true)) {
                    this.IdProcesoField = value;
                    this.RaisePropertyChanged("IdProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUltimoProceso {
            get {
                return this.IdUltimoProcesoField;
            }
            set {
                if ((this.IdUltimoProcesoField.Equals(value) != true)) {
                    this.IdUltimoProcesoField = value;
                    this.RaisePropertyChanged("IdUltimoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoRechazo {
            get {
                return this.MotivoRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoRechazoField, value) != true)) {
                    this.MotivoRechazoField = value;
                    this.RaisePropertyChanged("MotivoRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroResolucion {
            get {
                return this.NumeroResolucionField;
            }
            set {
                if ((this.NumeroResolucionField.Equals(value) != true)) {
                    this.NumeroResolucionField = value;
                    this.RaisePropertyChanged("NumeroResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcesoFinalizado {
            get {
                return this.ProcesoFinalizadoField;
            }
            set {
                if ((this.ProcesoFinalizadoField.Equals(value) != true)) {
                    this.ProcesoFinalizadoField = value;
                    this.RaisePropertyChanged("ProcesoFinalizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltimoProceso {
            get {
                return this.UltimoProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimoProcesoField, value) != true)) {
                    this.UltimoProcesoField = value;
                    this.RaisePropertyChanged("UltimoProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlPdf {
            get {
                return this.UrlPdfField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlPdfField, value) != true)) {
                    this.UrlPdfField = value;
                    this.RaisePropertyChanged("UrlPdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlXmlUbl {
            get {
                return this.UrlXmlUblField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlXmlUblField, value) != true)) {
                    this.UrlXmlUblField = value;
                    this.RaisePropertyChanged("UrlXmlUbl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFacturaEServicios.ServicioNotaDebito.CodigoError CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFacturaEServicios.ServicioNotaDebito.CodigoError Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodigoError", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    public enum CodigoError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_NO_CONTROLADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EN_SERVIDOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VALIDACION = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_AGREGAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EDITAR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_ELIMINAR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_LICENCIA = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NINGUNO = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", ConfigurationName="ServicioNotaDebito.ServicioNotaDebito")]
    public interface ServicioNotaDebito {
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/TestResponse")]
        HGInetFacturaEServicios.ServicioNotaDebito.TestResponse Test(HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/TestResponse")]
        System.IAsyncResult BeginTest(HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioNotaDebito.TestResponse EndTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/Recepcion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/RecepcionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HGInetFacturaEServicios.ServicioNotaDebito.Error), Action="Recepcion", Name="Error")]
        HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse Recepcion(HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/Recepcion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioNotaDebito/RecepcionResponse")]
        System.IAsyncResult BeginRecepcion(HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request, System.AsyncCallback callback, object asyncState);
        
        HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse EndRecepcion(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Recepcion", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class RecepcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public HGInetFacturaEServicios.ServicioNotaDebito.NotaDebito[] documentos;
        
        public RecepcionRequest() {
        }
        
        public RecepcionRequest(HGInetFacturaEServicios.ServicioNotaDebito.NotaDebito[] documentos) {
            this.documentos = documentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class RecepcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public HGInetFacturaEServicios.ServicioNotaDebito.DocumentoRespuesta[] RecepcionResult;
        
        public RecepcionResponse() {
        }
        
        public RecepcionResponse(HGInetFacturaEServicios.ServicioNotaDebito.DocumentoRespuesta[] RecepcionResult) {
            this.RecepcionResult = RecepcionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioNotaDebitoChannel : HGInetFacturaEServicios.ServicioNotaDebito.ServicioNotaDebito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioNotaDebito.TestResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioNotaDebito.TestResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RecepcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioNotaDebitoClient : System.ServiceModel.ClientBase<HGInetFacturaEServicios.ServicioNotaDebito.ServicioNotaDebito>, HGInetFacturaEServicios.ServicioNotaDebito.ServicioNotaDebito {
        
        private BeginOperationDelegate onBeginTestDelegate;
        
        private EndOperationDelegate onEndTestDelegate;
        
        private System.Threading.SendOrPostCallback onTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginRecepcionDelegate;
        
        private EndOperationDelegate onEndRecepcionDelegate;
        
        private System.Threading.SendOrPostCallback onRecepcionCompletedDelegate;
        
        public ServicioNotaDebitoClient() {
        }
        
        public ServicioNotaDebitoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioNotaDebitoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNotaDebitoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNotaDebitoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<TestCompletedEventArgs> TestCompleted;
        
        public event System.EventHandler<RecepcionCompletedEventArgs> RecepcionCompleted;
        
        public HGInetFacturaEServicios.ServicioNotaDebito.TestResponse Test(HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTest(HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioNotaDebito.TestResponse EndTest(System.IAsyncResult result) {
            return base.Channel.EndTest(result);
        }
        
        private System.IAsyncResult OnBeginTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request = ((HGInetFacturaEServicios.ServicioNotaDebito.TestRequest)(inValues[0]));
            return this.BeginTest(request, callback, asyncState);
        }
        
        private object[] OnEndTest(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioNotaDebito.TestResponse retVal = this.EndTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestCompleted(object state) {
            if ((this.TestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestCompleted(this, new TestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestAsync(HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request) {
            this.TestAsync(request, null);
        }
        
        public void TestAsync(HGInetFacturaEServicios.ServicioNotaDebito.TestRequest request, object userState) {
            if ((this.onBeginTestDelegate == null)) {
                this.onBeginTestDelegate = new BeginOperationDelegate(this.OnBeginTest);
            }
            if ((this.onEndTestDelegate == null)) {
                this.onEndTestDelegate = new EndOperationDelegate(this.OnEndTest);
            }
            if ((this.onTestCompletedDelegate == null)) {
                this.onTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestCompleted);
            }
            base.InvokeAsync(this.onBeginTestDelegate, new object[] {
                        request}, this.onEndTestDelegate, this.onTestCompletedDelegate, userState);
        }
        
        public HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse Recepcion(HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request) {
            return base.Channel.Recepcion(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRecepcion(HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecepcion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse EndRecepcion(System.IAsyncResult result) {
            return base.Channel.EndRecepcion(result);
        }
        
        private System.IAsyncResult OnBeginRecepcion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request = ((HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest)(inValues[0]));
            return this.BeginRecepcion(request, callback, asyncState);
        }
        
        private object[] OnEndRecepcion(System.IAsyncResult result) {
            HGInetFacturaEServicios.ServicioNotaDebito.RecepcionResponse retVal = this.EndRecepcion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRecepcionCompleted(object state) {
            if ((this.RecepcionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecepcionCompleted(this, new RecepcionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecepcionAsync(HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request) {
            this.RecepcionAsync(request, null);
        }
        
        public void RecepcionAsync(HGInetFacturaEServicios.ServicioNotaDebito.RecepcionRequest request, object userState) {
            if ((this.onBeginRecepcionDelegate == null)) {
                this.onBeginRecepcionDelegate = new BeginOperationDelegate(this.OnBeginRecepcion);
            }
            if ((this.onEndRecepcionDelegate == null)) {
                this.onEndRecepcionDelegate = new EndOperationDelegate(this.OnEndRecepcion);
            }
            if ((this.onRecepcionCompletedDelegate == null)) {
                this.onRecepcionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecepcionCompleted);
            }
            base.InvokeAsync(this.onBeginRecepcionDelegate, new object[] {
                        request}, this.onEndRecepcionDelegate, this.onRecepcionCompletedDelegate, userState);
        }
    }
}
