//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetFeAPI.ServicioRutasPlataforma {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFeAPI.ServicioRutasPlataforma.CodigoError CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFeAPI.ServicioRutasPlataforma.CodigoError Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodigoError", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    public enum CodigoError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_NO_CONTROLADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EN_SERVIDOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VALIDACION = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_AGREGAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EDITAR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_ELIMINAR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_LICENCIA = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NINGUNO = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="FacturaE.ServiciosWcf", ConfigurationName="ServicioRutasPlataforma.ServicioFacturaE")]
    public interface ServicioFacturaE {
        
        [System.ServiceModel.OperationContractAttribute(Action="FacturaE.ServiciosWcf/ServicioFacturaE/Test", ReplyAction="FacturaE.ServiciosWcf/ServicioFacturaE/TestResponse")]
        HGInetFeAPI.ServicioRutasPlataforma.TestResponse Test(HGInetFeAPI.ServicioRutasPlataforma.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="FacturaE.ServiciosWcf/ServicioFacturaE/Test", ReplyAction="FacturaE.ServiciosWcf/ServicioFacturaE/TestResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioRutasPlataforma.TestResponse> TestAsync(HGInetFeAPI.ServicioRutasPlataforma.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="FacturaE.ServiciosWcf/ServicioFacturaE/ObtenerServidorFE", ReplyAction="FacturaE.ServiciosWcf/ServicioFacturaE/ObtenerServidorFEResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HGInetFeAPI.ServicioRutasPlataforma.Error), Action="ObtenerServidorFE", Name="Error")]
        HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFEResponse ObtenerServidorFE(HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="FacturaE.ServiciosWcf/ServicioFacturaE/ObtenerServidorFE", ReplyAction="FacturaE.ServiciosWcf/ServicioFacturaE/ObtenerServidorFEResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFEResponse> ObtenerServidorFEAsync(HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="FacturaE.ServiciosWcf", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="FacturaE.ServiciosWcf", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FacturaE.ServiciosWcf", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerServidorFE", WrapperNamespace="FacturaE.ServiciosWcf", IsWrapped=true)]
    public partial class ObtenerServidorFERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FacturaE.ServiciosWcf", Order=0)]
        public short ambiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FacturaE.ServiciosWcf", Order=1)]
        public short version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FacturaE.ServiciosWcf", Order=2)]
        public string identificacion_empresa;
        
        public ObtenerServidorFERequest() {
        }
        
        public ObtenerServidorFERequest(short ambiente, short version, string identificacion_empresa) {
            this.ambiente = ambiente;
            this.version = version;
            this.identificacion_empresa = identificacion_empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerServidorFEResponse", WrapperNamespace="FacturaE.ServiciosWcf", IsWrapped=true)]
    public partial class ObtenerServidorFEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="FacturaE.ServiciosWcf", Order=0)]
        public string ObtenerServidorFEResult;
        
        public ObtenerServidorFEResponse() {
        }
        
        public ObtenerServidorFEResponse(string ObtenerServidorFEResult) {
            this.ObtenerServidorFEResult = ObtenerServidorFEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFacturaEChannel : HGInetFeAPI.ServicioRutasPlataforma.ServicioFacturaE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturaEClient : System.ServiceModel.ClientBase<HGInetFeAPI.ServicioRutasPlataforma.ServicioFacturaE>, HGInetFeAPI.ServicioRutasPlataforma.ServicioFacturaE {
        
        public ServicioFacturaEClient() {
        }
        
        public ServicioFacturaEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturaEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturaEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturaEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HGInetFeAPI.ServicioRutasPlataforma.TestResponse Test(HGInetFeAPI.ServicioRutasPlataforma.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioRutasPlataforma.TestResponse> TestAsync(HGInetFeAPI.ServicioRutasPlataforma.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFEResponse ObtenerServidorFE(HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFERequest request) {
            return base.Channel.ObtenerServidorFE(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFEResponse> ObtenerServidorFEAsync(HGInetFeAPI.ServicioRutasPlataforma.ObtenerServidorFERequest request) {
            return base.Channel.ObtenerServidorFEAsync(request);
        }
    }
}
