using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HGInetUBLv2_1.DianListas
{
	public class ListaLanguageCode
	{
		public string ShortName = "LanguageCode";
		public string LongName = "Language Code";
		public string Version = "20061027";
		public string CanonicalUri = "urn:un:unece:uncefact:identifierlist:standard:ISO:ISOAlpha2LanguageCode:20061027";
		public string CanonicalVersionUri = "urn:un:unece:uncefact:identifierlist:standard:ISO:ISOAlpha2LanguageCode:20061027";
		public string LocationUri = "http://docs.oasis-open.org/ubl/os-UBL-2.1/cl/gc/special-purpose/LanguageCode-2.1.gc";
		public string AgencyName = "International Organization for Standardization";
		public string AgencyIdentifier = "5";

		public List<ListaItem> Items = new List<ListaItem>()
		{
			new ListaItem("aa", "Afar", "Afar"),
new ListaItem("AA", "Afar", "Afar"),
new ListaItem("ab", "Abkhazian", "Abkhazian"),
new ListaItem("AB", "Abkhazian", "Abkhazian"),
new ListaItem("ae", "Avestan", "Avestan"),
new ListaItem("AE", "Avestan", "Avestan"),
new ListaItem("af", "Afrikaans", "Afrikaans"),
new ListaItem("AF", "Afrikaans", "Afrikaans"),
new ListaItem("ak", "Akan", "Akan"),
new ListaItem("AK", "Akan", "Akan"),
new ListaItem("am", "Amharic", "Amharic"),
new ListaItem("AM", "Amharic", "Amharic"),
new ListaItem("an", "Aragonese", "Aragonese"),
new ListaItem("AN", "Aragonese", "Aragonese"),
new ListaItem("ar", "Arabic", "Arabic"),
new ListaItem("AR", "Arabic", "Arabic"),
new ListaItem("as", "Assamese", "Assamese"),
new ListaItem("AS", "Assamese", "Assamese"),
new ListaItem("av", "Avaric", "Avaric"),
new ListaItem("AV", "Avaric", "Avaric"),
new ListaItem("ay", "Aymara", "Aymara"),
new ListaItem("AY", "Aymara", "Aymara"),
new ListaItem("az", "Azerbaijani", "Azerbaijani"),
new ListaItem("AZ", "Azerbaijani", "Azerbaijani"),
new ListaItem("ba", "Bashkir", "Bashkir"),
new ListaItem("BA", "Bashkir", "Bashkir"),
new ListaItem("be", "Belarusian", "Belarusian"),
new ListaItem("BE", "Belarusian", "Belarusian"),
new ListaItem("bg", "Bulgarian", "Bulgarian"),
new ListaItem("BG", "Bulgarian", "Bulgarian"),
new ListaItem("bh", "Bihari languages", "Bihari languages"),
new ListaItem("BH", "Bihari languages", "Bihari languages"),
new ListaItem("bi", "Bislama", "Bislama"),
new ListaItem("BI", "Bislama", "Bislama"),
new ListaItem("bm", "Bambara", "Bambara"),
new ListaItem("BM", "Bambara", "Bambara"),
new ListaItem("bn", "Bengali", "Bengali"),
new ListaItem("BN", "Bengali", "Bengali"),
new ListaItem("bo", "Tibetan", "Tibetan"),
new ListaItem("BO", "Tibetan", "Tibetan"),
new ListaItem("br", "Breton", "Breton"),
new ListaItem("BR", "Breton", "Breton"),
new ListaItem("bs", "Bosnian", "Bosnian"),
new ListaItem("BS", "Bosnian", "Bosnian"),
new ListaItem("ca", "Catalan; Valencian", "Catalan; Valencian"),
new ListaItem("CA", "Catalan; Valencian", "Catalan; Valencian"),
new ListaItem("ce", "Chechen", "Chechen"),
new ListaItem("CE", "Chechen", "Chechen"),
new ListaItem("ch", "Chamorro", "Chamorro"),
new ListaItem("CH", "Chamorro", "Chamorro"),
new ListaItem("co", "Corsican", "Corsican"),
new ListaItem("CO", "Corsican", "Corsican"),
new ListaItem("cr", "Cree", "Cree"),
new ListaItem("CR", "Cree", "Cree"),
new ListaItem("cs", "Czech", "Czech"),
new ListaItem("CS", "Czech", "Czech"),
new ListaItem("cu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
new ListaItem("CU", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
new ListaItem("cv", "Chuvash", "Chuvash"),
new ListaItem("CV", "Chuvash", "Chuvash"),
new ListaItem("cy", "Welsh", "Welsh"),
new ListaItem("CY", "Welsh", "Welsh"),
new ListaItem("da", "Danish", "Danish"),
new ListaItem("DA", "Danish", "Danish"),
new ListaItem("de", "German", "German"),
new ListaItem("DE", "German", "German"),
new ListaItem("dv", "Divehi; Dhivehi; Maldivian", "Divehi; Dhivehi; Maldivian"),
new ListaItem("DV", "Divehi; Dhivehi; Maldivian", "Divehi; Dhivehi; Maldivian"),
new ListaItem("dz", "Dzongkha", "Dzongkha"),
new ListaItem("DZ", "Dzongkha", "Dzongkha"),
new ListaItem("ee", "Ewe", "Ewe"),
new ListaItem("EE", "Ewe", "Ewe"),
new ListaItem("el", "Greek; Modern (1453-)", "Greek; Modern (1453-)"),
new ListaItem("EL", "Greek; Modern (1453-)", "Greek; Modern (1453-)"),
new ListaItem("en", "English", "English"),
new ListaItem("EN", "English", "English"),
new ListaItem("eo", "Esperanto", "Esperanto"),
new ListaItem("EO", "Esperanto", "Esperanto"),
new ListaItem("es", "Spanish; Castilian", "Spanish; Castilian"),
new ListaItem("ES", "Spanish; Castilian", "Spanish; Castilian"),
new ListaItem("et", "Estonian", "Estonian"),
new ListaItem("ET", "Estonian", "Estonian"),
new ListaItem("eu", "Basque", "Basque"),
new ListaItem("EU", "Basque", "Basque"),
new ListaItem("fa", "Persian", "Persian"),
new ListaItem("FA", "Persian", "Persian"),
new ListaItem("ff", "Fulah", "Fulah"),
new ListaItem("FF", "Fulah", "Fulah"),
new ListaItem("fi", "Finnish", "Finnish"),
new ListaItem("FI", "Finnish", "Finnish"),
new ListaItem("fj", "Fijian", "Fijian"),
new ListaItem("FJ", "Fijian", "Fijian"),
new ListaItem("fo", "Faroese", "Faroese"),
new ListaItem("FO", "Faroese", "Faroese"),
new ListaItem("fr", "French", "French"),
new ListaItem("FR", "French", "French"),
new ListaItem("fy", "Western Frisian", "Western Frisian"),
new ListaItem("FY", "Western Frisian", "Western Frisian"),
new ListaItem("ga", "Irish", "Irish"),
new ListaItem("GA", "Irish", "Irish"),
new ListaItem("gd", "Gaelic; Scottish Gaelic", "Gaelic; Scottish Gaelic"),
new ListaItem("GD", "Gaelic; Scottish Gaelic", "Gaelic; Scottish Gaelic"),
new ListaItem("gl", "Galician", "Galician"),
new ListaItem("GL", "Galician", "Galician"),
new ListaItem("gn", "Guarani", "Guarani"),
new ListaItem("GN", "Guarani", "Guarani"),
new ListaItem("gu", "Gujarati", "Gujarati"),
new ListaItem("GU", "Gujarati", "Gujarati"),
new ListaItem("gv", "Manx", "Manx"),
new ListaItem("GV", "Manx", "Manx"),
new ListaItem("ha", "Hausa", "Hausa"),
new ListaItem("HA", "Hausa", "Hausa"),
new ListaItem("he", "Hebrew", "Hebrew"),
new ListaItem("HE", "Hebrew", "Hebrew"),
new ListaItem("hi", "Hindi", "Hindi"),
new ListaItem("HI", "Hindi", "Hindi"),
new ListaItem("ho", "Hiri Motu", "Hiri Motu"),
new ListaItem("HO", "Hiri Motu", "Hiri Motu"),
new ListaItem("hr", "Croatian", "Croatian"),
new ListaItem("HR", "Croatian", "Croatian"),
new ListaItem("ht", "Haitian; Haitian Creole", "Haitian; Haitian Creole"),
new ListaItem("HT", "Haitian; Haitian Creole", "Haitian; Haitian Creole"),
new ListaItem("hu", "Hungarian", "Hungarian"),
new ListaItem("HU", "Hungarian", "Hungarian"),
new ListaItem("hy", "Armenian", "Armenian"),
new ListaItem("HY", "Armenian", "Armenian"),
new ListaItem("hz", "Herero", "Herero"),
new ListaItem("HZ", "Herero", "Herero"),
new ListaItem("ia", "Interlingua (International Auxiliary Language Association)", "Interlingua (International Auxiliary Language Association)"),
new ListaItem("IA", "Interlingua (International Auxiliary Language Association)", "Interlingua (International Auxiliary Language Association)"),
new ListaItem("id", "Indonesian", "Indonesian"),
new ListaItem("ID", "Indonesian", "Indonesian"),
new ListaItem("ie", "Interlingue; Occidental", "Interlingue; Occidental"),
new ListaItem("IE", "Interlingue; Occidental", "Interlingue; Occidental"),
new ListaItem("ig", "Igbo", "Igbo"),
new ListaItem("IG", "Igbo", "Igbo"),
new ListaItem("ii", "Sichuan Yi; Nuosu", "Sichuan Yi; Nuosu"),
new ListaItem("II", "Sichuan Yi; Nuosu", "Sichuan Yi; Nuosu"),
new ListaItem("ik", "Inupiaq", "Inupiaq"),
new ListaItem("IK", "Inupiaq", "Inupiaq"),
new ListaItem("io", "Ido", "Ido"),
new ListaItem("IO", "Ido", "Ido"),
new ListaItem("is", "Icelandic", "Icelandic"),
new ListaItem("IS", "Icelandic", "Icelandic"),
new ListaItem("it", "Italian", "Italian"),
new ListaItem("IT", "Italian", "Italian"),
new ListaItem("iu", "Inuktiut", "Inuktiut"),
new ListaItem("IU", "Inuktiut", "Inuktiut"),
new ListaItem("ja", "Japanese", "Japanese"),
new ListaItem("JA", "Japanese", "Japanese"),
new ListaItem("jv", "Javanese", "Javanese"),
new ListaItem("JV", "Javanese", "Javanese"),
new ListaItem("ka", "Georgian", "Georgian"),
new ListaItem("KA", "Georgian", "Georgian"),
new ListaItem("kg", "Kongo", "Kongo"),
new ListaItem("KG", "Kongo", "Kongo"),
new ListaItem("ki", "Kikuyu; Gikuyu", "Kikuyu; Gikuyu"),
new ListaItem("KI", "Kikuyu; Gikuyu", "Kikuyu; Gikuyu"),
new ListaItem("kj", "Kuanyama; Kwanyama", "Kuanyama; Kwanyama"),
new ListaItem("KJ", "Kuanyama; Kwanyama", "Kuanyama; Kwanyama"),
new ListaItem("kk", "Kazakh", "Kazakh"),
new ListaItem("KK", "Kazakh", "Kazakh"),
new ListaItem("kl", "Kalaallisut; Greenlandic", "Kalaallisut; Greenlandic"),
new ListaItem("KL", "Kalaallisut; Greenlandic", "Kalaallisut; Greenlandic"),
new ListaItem("km", "Central Khmer", "Central Khmer"),
new ListaItem("KM", "Central Khmer", "Central Khmer"),
new ListaItem("kn", "Kannada", "Kannada"),
new ListaItem("KN", "Kannada", "Kannada"),
new ListaItem("ko", "Korean", "Korean"),
new ListaItem("KO", "Korean", "Korean"),
new ListaItem("kr", "Kanuri", "Kanuri"),
new ListaItem("KR", "Kanuri", "Kanuri"),
new ListaItem("ks", "Kashmiri", "Kashmiri"),
new ListaItem("KS", "Kashmiri", "Kashmiri"),
new ListaItem("ku", "Kurdish", "Kurdish"),
new ListaItem("KU", "Kurdish", "Kurdish"),
new ListaItem("kv", "Komi", "Komi"),
new ListaItem("KV", "Komi", "Komi"),
new ListaItem("kw", "Cornish", "Cornish"),
new ListaItem("KW", "Cornish", "Cornish"),
new ListaItem("ky", "Kirghiz; Kyrgyz", "Kirghiz; Kyrgyz"),
new ListaItem("KY", "Kirghiz; Kyrgyz", "Kirghiz; Kyrgyz"),
new ListaItem("la", "Latin", "Latin"),
new ListaItem("LA", "Latin", "Latin"),
new ListaItem("lb", "Luxembourgish; Letzeburgesch", "Luxembourgish; Letzeburgesch"),
new ListaItem("LB", "Luxembourgish; Letzeburgesch", "Luxembourgish; Letzeburgesch"),
new ListaItem("lg", "Ganda", "Ganda"),
new ListaItem("LG", "Ganda", "Ganda"),
new ListaItem("li", "Limburgan; Limburger; Limburgish", "Limburgan; Limburger; Limburgish"),
new ListaItem("LI", "Limburgan; Limburger; Limburgish", "Limburgan; Limburger; Limburgish"),
new ListaItem("ln", "Lingala", "Lingala"),
new ListaItem("LN", "Lingala", "Lingala"),
new ListaItem("lo", "Lao", "Lao"),
new ListaItem("LO", "Lao", "Lao"),
new ListaItem("lt", "Lithuanian", "Lithuanian"),
new ListaItem("LT", "Lithuanian", "Lithuanian"),
new ListaItem("lu", "Luba-Katanga", "Luba-Katanga"),
new ListaItem("LU", "Luba-Katanga", "Luba-Katanga"),
new ListaItem("lv", "Latvian", "Latvian"),
new ListaItem("LV", "Latvian", "Latvian"),
new ListaItem("mg", "Malagasy", "Malagasy"),
new ListaItem("MG", "Malagasy", "Malagasy"),
new ListaItem("mh", "Marshallese", "Marshallese"),
new ListaItem("MH", "Marshallese", "Marshallese"),
new ListaItem("mi", "Maori", "Maori"),
new ListaItem("MI", "Maori", "Maori"),
new ListaItem("mk", "Macedonian", "Macedonian"),
new ListaItem("MK", "Macedonian", "Macedonian"),
new ListaItem("ml", "Malayalam", "Malayalam"),
new ListaItem("ML", "Malayalam", "Malayalam"),
new ListaItem("mn", "Mongolian", "Mongolian"),
new ListaItem("MN", "Mongolian", "Mongolian"),
new ListaItem("mo", "Moldavian; Moldovan", "Moldavian; Moldovan"),
new ListaItem("MO", "Moldavian; Moldovan", "Moldavian; Moldovan"),
new ListaItem("mr", "Marathi", "Marathi"),
new ListaItem("MR", "Marathi", "Marathi"),
new ListaItem("ms", "Malay", "Malay"),
new ListaItem("MS", "Malay", "Malay"),
new ListaItem("mt", "Maltese", "Maltese"),
new ListaItem("MT", "Maltese", "Maltese"),
new ListaItem("my", "Burmese", "Burmese"),
new ListaItem("MY", "Burmese", "Burmese"),
new ListaItem("na", "Nauru", "Nauru"),
new ListaItem("NA", "Nauru", "Nauru"),
new ListaItem("nb", "Bokmal Norwegian; Norwegian Bokmal", "Bokmal Norwegian; Norwegian Bokmal"),
new ListaItem("NB", "Bokmal Norwegian; Norwegian Bokmal", "Bokmal Norwegian; Norwegian Bokmal"),
new ListaItem("nd", "Ndebele; North; North Ndebele", "Ndebele; North; North Ndebele"),
new ListaItem("ND", "Ndebele; North; North Ndebele", "Ndebele; North; North Ndebele"),
new ListaItem("ne", "Nepali", "Nepali"),
new ListaItem("NE", "Nepali", "Nepali"),
new ListaItem("ng", "Ndonga", "Ndonga"),
new ListaItem("NG", "Ndonga", "Ndonga"),
new ListaItem("nl", "Dutch; Flemish", "Dutch; Flemish"),
new ListaItem("NL", "Dutch; Flemish", "Dutch; Flemish"),
new ListaItem("nn", "Norwegian Nynorsk; Nynorsk, Norwegian", "Norwegian Nynorsk; Nynorsk, Norwegian"),
new ListaItem("NN", "Norwegian Nynorsk; Nynorsk, Norwegian", "Norwegian Nynorsk; Nynorsk, Norwegian"),
new ListaItem("no", "Norwegian", "Norwegian"),
new ListaItem("NO", "Norwegian", "Norwegian"),
new ListaItem("nr", "Ndebele; South; South Ndebele", "Ndebele; South; South Ndebele"),
new ListaItem("NR", "Ndebele; South; South Ndebele", "Ndebele; South; South Ndebele"),
new ListaItem("nv", "Navajo; Navaho", "Navajo; Navaho"),
new ListaItem("NV", "Navajo; Navaho", "Navajo; Navaho"),
new ListaItem("ny", "Chichewa; Chewa; Nyanja", "Chichewa; Chewa; Nyanja"),
new ListaItem("NY", "Chichewa; Chewa; Nyanja", "Chichewa; Chewa; Nyanja"),
new ListaItem("oc", "Occitan (post 1500)", "Occitan (post 1500)"),
new ListaItem("OC", "Occitan (post 1500)", "Occitan (post 1500)"),
new ListaItem("oj", "Ojibwa", "Ojibwa"),
new ListaItem("OJ", "Ojibwa", "Ojibwa"),
new ListaItem("om", "Oromo", "Oromo"),
new ListaItem("OM", "Oromo", "Oromo"),
new ListaItem("or", "Oriya", "Oriya"),
new ListaItem("OR", "Oriya", "Oriya"),
new ListaItem("os", "Ossetian; Ossetic", "Ossetian; Ossetic"),
new ListaItem("OS", "Ossetian; Ossetic", "Ossetian; Ossetic"),
new ListaItem("pa", "Panjabi; Punjabi", "Panjabi; Punjabi"),
new ListaItem("PA", "Panjabi; Punjabi", "Panjabi; Punjabi"),
new ListaItem("pi", "Pali", "Pali"),
new ListaItem("PI", "Pali", "Pali"),
new ListaItem("pl", "Polish", "Polish"),
new ListaItem("PL", "Polish", "Polish"),
new ListaItem("ps", "Pushto; Pashto", "Pushto; Pashto"),
new ListaItem("PS", "Pushto; Pashto", "Pushto; Pashto"),
new ListaItem("pt", "Portuguese", "Portuguese"),
new ListaItem("PT", "Portuguese", "Portuguese"),
new ListaItem("qu", "Quechua", "Quechua"),
new ListaItem("QU", "Quechua", "Quechua"),
new ListaItem("rm", "Romansh", "Romansh"),
new ListaItem("RM", "Romansh", "Romansh"),
new ListaItem("rn", "Rundi", "Rundi"),
new ListaItem("RN", "Rundi", "Rundi"),
new ListaItem("ro", "Romanian", "Romanian"),
new ListaItem("RO", "Romanian", "Romanian"),
new ListaItem("ru", "Russian", "Russian"),
new ListaItem("RU", "Russian", "Russian"),
new ListaItem("rw", "Kinyarwanda", "Kinyarwanda"),
new ListaItem("RW", "Kinyarwanda", "Kinyarwanda"),
new ListaItem("sa", "Sanskrit", "Sanskrit"),
new ListaItem("SA", "Sanskrit", "Sanskrit"),
new ListaItem("sc", "Sardinian", "Sardinian"),
new ListaItem("SC", "Sardinian", "Sardinian"),
new ListaItem("sd", "Sindhi", "Sindhi"),
new ListaItem("SD", "Sindhi", "Sindhi"),
new ListaItem("se", "Northern Sami", "Northern Sami"),
new ListaItem("SE", "Northern Sami", "Northern Sami"),
new ListaItem("sg", "Sango", "Sango"),
new ListaItem("SG", "Sango", "Sango"),
new ListaItem("si", "Sinhala; Sinhalese", "Sinhala; Sinhalese"),
new ListaItem("SI", "Sinhala; Sinhalese", "Sinhala; Sinhalese"),
new ListaItem("sk", "Slovak", "Slovak"),
new ListaItem("SK", "Slovak", "Slovak"),
new ListaItem("sl", "Slovenian", "Slovenian"),
new ListaItem("SL", "Slovenian", "Slovenian"),
new ListaItem("sm", "Samoan", "Samoan"),
new ListaItem("SM", "Samoan", "Samoan"),
new ListaItem("sn", "Shona", "Shona"),
new ListaItem("SN", "Shona", "Shona"),
new ListaItem("so", "Somali", "Somali"),
new ListaItem("SO", "Somali", "Somali"),
new ListaItem("sq", "Albanian", "Albanian"),
new ListaItem("SQ", "Albanian", "Albanian"),
new ListaItem("sr", "Serbian", "Serbian"),
new ListaItem("SR", "Serbian", "Serbian"),
new ListaItem("ss", "Swati", "Swati"),
new ListaItem("SS", "Swati", "Swati"),
new ListaItem("st", "Sotho, Southern", "Sotho, Southern"),
new ListaItem("ST", "Sotho, Southern", "Sotho, Southern"),
new ListaItem("su", "Sundanese", "Sundanese"),
new ListaItem("SU", "Sundanese", "Sundanese"),
new ListaItem("sv", "Swedish", "Swedish"),
new ListaItem("SV", "Swedish", "Swedish"),
new ListaItem("sw", "Swahili", "Swahili"),
new ListaItem("SW", "Swahili", "Swahili"),
new ListaItem("ta", "Tamil", "Tamil"),
new ListaItem("TA", "Tamil", "Tamil"),
new ListaItem("te", "Telugu", "Telugu"),
new ListaItem("TE", "Telugu", "Telugu"),
new ListaItem("tg", "Tajik", "Tajik"),
new ListaItem("TG", "Tajik", "Tajik"),
new ListaItem("th", "Thai", "Thai"),
new ListaItem("TH", "Thai", "Thai"),
new ListaItem("ti", "Tigrinya", "Tigrinya"),
new ListaItem("TI", "Tigrinya", "Tigrinya"),
new ListaItem("tk", "Turkmen", "Turkmen"),
new ListaItem("TK", "Turkmen", "Turkmen"),
new ListaItem("tl", "Tagalog", "Tagalog"),
new ListaItem("TL", "Tagalog", "Tagalog"),
new ListaItem("tn", "Tswana", "Tswana"),
new ListaItem("TN", "Tswana", "Tswana"),
new ListaItem("to", "Tonga (Tonga Islands)", "Tonga (Tonga Islands)"),
new ListaItem("TO", "Tonga (Tonga Islands)", "Tonga (Tonga Islands)"),
new ListaItem("tr", "Turkish", "Turkish"),
new ListaItem("TR", "Turkish", "Turkish"),
new ListaItem("ts", "Tsonga", "Tsonga"),
new ListaItem("TS", "Tsonga", "Tsonga"),
new ListaItem("tt", "Tatar", "Tatar"),
new ListaItem("TT", "Tatar", "Tatar"),
new ListaItem("tw", "Twi", "Twi"),
new ListaItem("TW", "Twi", "Twi"),
new ListaItem("ty", "Tahitian", "Tahitian"),
new ListaItem("TY", "Tahitian", "Tahitian"),
new ListaItem("ug", "Uighur; Uyghur", "Uighur; Uyghur"),
new ListaItem("UG", "Uighur; Uyghur", "Uighur; Uyghur"),
new ListaItem("uk", "Ukrainian", "Ukrainian"),
new ListaItem("UK", "Ukrainian", "Ukrainian"),
new ListaItem("ur", "Urdu", "Urdu"),
new ListaItem("UR", "Urdu", "Urdu"),
new ListaItem("uz", "Uzbek", "Uzbek"),
new ListaItem("UZ", "Uzbek", "Uzbek"),
new ListaItem("ve", "Venda", "Venda"),
new ListaItem("VE", "Venda", "Venda"),
new ListaItem("vi", "Vietnamese", "Vietnamese"),
new ListaItem("VI", "Vietnamese", "Vietnamese"),
new ListaItem("vo", "Volapük", "Volapük"),
new ListaItem("VO", "Volapük", "Volapük"),
new ListaItem("wa", "Walloon", "Walloon"),
new ListaItem("WA", "Walloon", "Walloon"),
new ListaItem("wo", "Wolof", "Wolof"),
new ListaItem("WO", "Wolof", "Wolof"),
new ListaItem("xh", "Xhosa", "Xhosa"),
new ListaItem("XH", "Xhosa", "Xhosa"),
new ListaItem("yi", "Yiddish", "Yiddish"),
new ListaItem("YI", "Yiddish", "Yiddish"),
new ListaItem("yo", "Yoruba", "Yoruba"),
new ListaItem("YO", "Yoruba", "Yoruba"),
new ListaItem("za", "Zhuang; Chuang", "Zhuang; Chuang"),
new ListaItem("ZA", "Zhuang; Chuang", "Zhuang; Chuang"),
new ListaItem("zh", "Chinese", "Chinese"),
new ListaItem("ZH", "Chinese", "Chinese"),
new ListaItem("zu", "Zulu", "Zulu"),
new ListaItem("ZU", "Zulu", "Zulu"),

		};

	}
}
