using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HGInetUBLv2_1.DianListas
{
	public class ListaMunicipio
	{
		public string ShortName = "Municipio";
		public string LongName = "Municipios de Colombia";
		public string Version = "1";
		public string CanonicalUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:Municipio-2.1";
		public string CanonicalVersionUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:Municipio-2.1";
		public string LocationUri = "http://dian.gov.co/ubl/os-ubl-2.0/cl/gc/default/Municipio-2.1.gc";
		public string AgencyName = "DIAN (Dirección de Impuestos y Aduanas Nacionales)";
		public string AgencyIdentifier = "195";

		public List<ListaItem> Items = new List<ListaItem>()
		{
			new ListaItem("05001", "Medellín", "Medellín"),
			new ListaItem("05002", "Abejorral", "Abejorral"),
			new ListaItem("05004", "Abriaquí", "Abriaquí"),
			new ListaItem("05021", "Alejandría", "Alejandría"),
			new ListaItem("05030", "Amagá", "Amagá"),
			new ListaItem("05031", "Amalfi", "Amalfi"),
			new ListaItem("05034", "Andes", "Andes"),
			new ListaItem("05036", "Angelópolis", "Angelópolis"),
			new ListaItem("05038", "Angostura", "Angostura"),
			new ListaItem("05040", "Anorí", "Anorí"),
			new ListaItem("05042", "Santa Fé De Antioquia", "Santa Fé De Antioquia"),
			new ListaItem("05044", "Anzá", "Anzá"),
			new ListaItem("05045", "Apartadó", "Apartadó"),
			new ListaItem("05051", "Arboletes", "Arboletes"),
			new ListaItem("05055", "Argelia", "Argelia"),
			new ListaItem("05059", "Armenia", "Armenia"),
			new ListaItem("05079", "Barbosa", "Barbosa"),
			new ListaItem("05086", "Belmira", "Belmira"),
			new ListaItem("05088", "Bello", "Bello"),
			new ListaItem("05091", "Betania", "Betania"),
			new ListaItem("05093", "Betulia", "Betulia"),
			new ListaItem("05101", "Ciudad Bolívar ", "Ciudad Bolívar "),
			new ListaItem("05107", "Briceño", "Briceño"),
			new ListaItem("05113", "Buriticá", "Buriticá"),
			new ListaItem("05120", "Cáceres", "Cáceres"),
			new ListaItem("05125", "Caicedo", "Caicedo"),
			new ListaItem("05129", "Caldas", "Caldas"),
			new ListaItem("05134", "Campamento", "Campamento"),
			new ListaItem("05138", "Cañasgordas", "Cañasgordas"),
			new ListaItem("05142", "Caracolí", "Caracolí"),
			new ListaItem("05145", "Caramanta", "Caramanta"),
			new ListaItem("05147", "Carepa", "Carepa"),
			new ListaItem("05148", "El Carmen De Viboral", "El Carmen De Viboral"),
			new ListaItem("05150", "Carolina", "Carolina"),
			new ListaItem("05154", "Caucasia", "Caucasia"),
			new ListaItem("05172", "Chigorodó", "Chigorodó"),
			new ListaItem("05190", "Cisneros", "Cisneros"),
			new ListaItem("05197", "Cocorná", "Cocorná"),
			new ListaItem("05206", "Concepción", "Concepción"),
			new ListaItem("05209", "Concordia", "Concordia"),
			new ListaItem("05212", "Copacabana", "Copacabana"),
			new ListaItem("05234", "Dabeiba", "Dabeiba"),
			new ListaItem("05237", "Donmatías", "Donmatías"),
			new ListaItem("05240", "Ebéjico", "Ebéjico"),
			new ListaItem("05250", "El Bagre ", "El Bagre "),
			new ListaItem("05264", "Entrerríos", "Entrerríos"),
			new ListaItem("05266", "Envigado", "Envigado"),
			new ListaItem("05282", "Fredonia", "Fredonia"),
			new ListaItem("05284", "Frontino", "Frontino"),
			new ListaItem("05306", "Giraldo", "Giraldo"),
			new ListaItem("05308", "Girardota", "Girardota"),
			new ListaItem("05310", "Gómez Plata ", "Gómez Plata "),
			new ListaItem("05313", "Granada", "Granada"),
			new ListaItem("05315", "Guadalupe", "Guadalupe"),
			new ListaItem("05318", "Guarne", "Guarne"),
			new ListaItem("05321", "Guatapé", "Guatapé"),
			new ListaItem("05347", "Heliconia", "Heliconia"),
			new ListaItem("05353", "Hispania", "Hispania"),
			new ListaItem("05360", "Itagüí", "Itagüí"),
			new ListaItem("05361", "Ituango", "Ituango"),
			new ListaItem("05364", "Jardín", "Jardín"),
			new ListaItem("05368", "Jericó", "Jericó"),
			new ListaItem("05376", "La Ceja ", "La Ceja "),
			new ListaItem("05380", "La Estrella ", "La Estrella "),
			new ListaItem("05390", "La Pintada ", "La Pintada "),
			new ListaItem("05400", "La Unión ", "La Unión "),
			new ListaItem("05411", "Liborina", "Liborina"),
			new ListaItem("05425", "Maceo", "Maceo"),
			new ListaItem("05440", "Marinilla", "Marinilla"),
			new ListaItem("05467", "Montebello", "Montebello"),
			new ListaItem("05475", "Murindó", "Murindó"),
			new ListaItem("05480", "Mutatá", "Mutatá"),
			new ListaItem("05483", "Nariño", "Nariño"),
			new ListaItem("05490", "Necoclí", "Necoclí"),
			new ListaItem("05495", "Nechí", "Nechí"),
			new ListaItem("05501", "Olaya", "Olaya"),
			new ListaItem("05541", "Peñol", "Peñol"),
			new ListaItem("05543", "Peque", "Peque"),
			new ListaItem("05576", "Pueblorrico", "Pueblorrico"),
			new ListaItem("05579", "Puerto Berrío ", "Puerto Berrío "),
			new ListaItem("05585", "Puerto Nare ", "Puerto Nare "),
			new ListaItem("05591", "Puerto Triunfo ", "Puerto Triunfo "),
			new ListaItem("05604", "Remedios", "Remedios"),
			new ListaItem("05607", "Retiro", "Retiro"),
			new ListaItem("05615", "Rionegro", "Rionegro"),
			new ListaItem("05628", "Sabanalarga", "Sabanalarga"),
			new ListaItem("05631", "Sabaneta", "Sabaneta"),
			new ListaItem("05642", "Salgar", "Salgar"),
			new ListaItem("05647", "San Andrés De Cuerquía", "San Andrés De Cuerquía"),
			new ListaItem("05649", "San Carlos ", "San Carlos "),
			new ListaItem("05652", "San Francisco ", "San Francisco "),
			new ListaItem("05656", "San Jerónimo ", "San Jerónimo "),
			new ListaItem("05658", "San José De La Montaña ", "San José De La Montaña "),
			new ListaItem("05659", "San Juan De Urabá", "San Juan De Urabá"),
			new ListaItem("05660", "San Luis ", "San Luis "),
			new ListaItem("05664", "San Pedro De Los Milagros ", "San Pedro De Los Milagros "),
			new ListaItem("05665", "San Pedro De Urabá", "San Pedro De Urabá"),
			new ListaItem("05667", "San Rafael ", "San Rafael "),
			new ListaItem("05670", "San Roque ", "San Roque "),
			new ListaItem("05674", "San Vicente Ferrer", "San Vicente Ferrer"),
			new ListaItem("05679", "Santa Bárbara ", "Santa Bárbara "),
			new ListaItem("05686", "Santa Rosa De Osos", "Santa Rosa De Osos"),
			new ListaItem("05690", "Santo Domingo ", "Santo Domingo "),
			new ListaItem("05697", "El Santuario ", "El Santuario "),
			new ListaItem("05736", "Segovia", "Segovia"),
			new ListaItem("05756", "Sonsón", "Sonsón"),
			new ListaItem("05761", "Sopetrán", "Sopetrán"),
			new ListaItem("05789", "Támesis", "Támesis"),
			new ListaItem("05790", "Tarazá", "Tarazá"),
			new ListaItem("05792", "Tarso", "Tarso"),
			new ListaItem("05809", "Titiribí", "Titiribí"),
			new ListaItem("05819", "Toledo", "Toledo"),
			new ListaItem("05837", "Turbo", "Turbo"),
			new ListaItem("05842", "Uramita", "Uramita"),
			new ListaItem("05847", "Urrao", "Urrao"),
			new ListaItem("05854", "Valdivia", "Valdivia"),
			new ListaItem("05856", "Valparaíso", "Valparaíso"),
			new ListaItem("05858", "Vegachí", "Vegachí"),
			new ListaItem("05861", "Venecia", "Venecia"),
			new ListaItem("05873", "Vigía Del Fuerte", "Vigía Del Fuerte"),
			new ListaItem("05885", "Yalí", "Yalí"),
			new ListaItem("05887", "Yarumal", "Yarumal"),
			new ListaItem("05890", "Yolombó", "Yolombó"),
			new ListaItem("05893", "Yondó", "Yondó"),
			new ListaItem("05895", "Zaragoza", "Zaragoza"),
			new ListaItem("08001", "Barranquilla", "Barranquilla"),
			new ListaItem("08078", "Baranoa", "Baranoa"),
			new ListaItem("08137", "Campo De La Cruz", "Campo De La Cruz"),
			new ListaItem("08141", "Candelaria", "Candelaria"),
			new ListaItem("08296", "Galapa", "Galapa"),
			new ListaItem("08372", "Juan De Acosta", "Juan De Acosta"),
			new ListaItem("08421", "Luruaco", "Luruaco"),
			new ListaItem("08433", "Malambo", "Malambo"),
			new ListaItem("08436", "Manatí", "Manatí"),
			new ListaItem("08520", "Palmar De Varela", "Palmar De Varela"),
			new ListaItem("08549", "Piojó", "Piojó"),
			new ListaItem("08558", "Polonuevo", "Polonuevo"),
			new ListaItem("08560", "Ponedera", "Ponedera"),
			new ListaItem("08573", "Puerto Colombia ", "Puerto Colombia "),
			new ListaItem("08606", "Repelón", "Repelón"),
			new ListaItem("08634", "Sabanagrande", "Sabanagrande"),
			new ListaItem("08638", "Sabanalarga", "Sabanalarga"),
			new ListaItem("08675", "Santa Lucía ", "Santa Lucía "),
			new ListaItem("08685", "Santo Tomás ", "Santo Tomás "),
			new ListaItem("08758", "Soledad", "Soledad"),
			new ListaItem("08770", "Suan", "Suan"),
			new ListaItem("08832", "Tubará", "Tubará"),
			new ListaItem("08849", "Usiacurí", "Usiacurí"),
			new ListaItem("11001", "Bogotá, D.c. ", "Bogotá, D.c. "),
			new ListaItem("13001", "Cartagena De Indias", "Cartagena De Indias"),
			new ListaItem("13006", "Achí", "Achí"),
			new ListaItem("13030", "Altos Del Rosario", "Altos Del Rosario"),
			new ListaItem("13042", "Arenal", "Arenal"),
			new ListaItem("13052", "Arjona", "Arjona"),
			new ListaItem("13062", "Arroyohondo", "Arroyohondo"),
			new ListaItem("13074", "Barranco De Loba", "Barranco De Loba"),
			new ListaItem("13140", "Calamar", "Calamar"),
			new ListaItem("13160", "Cantagallo", "Cantagallo"),
			new ListaItem("13188", "Cicuco", "Cicuco"),
			new ListaItem("13212", "Córdoba", "Córdoba"),
			new ListaItem("13222", "Clemencia", "Clemencia"),
			new ListaItem("13244", "El Carmen De Bolívar", "El Carmen De Bolívar"),
			new ListaItem("13248", "El Guamo ", "El Guamo "),
			new ListaItem("13268", "El Peñón ", "El Peñón "),
			new ListaItem("13300", "Hatillo De Loba", "Hatillo De Loba"),
			new ListaItem("13430", "Magangué", "Magangué"),
			new ListaItem("13433", "Mahates", "Mahates"),
			new ListaItem("13440", "Margarita", "Margarita"),
			new ListaItem("13442", "María La Baja", "María La Baja"),
			new ListaItem("13458", "Montecristo", "Montecristo"),
			new ListaItem("13468", "Mompós", "Mompós"),
			new ListaItem("13473", "Morales", "Morales"),
			new ListaItem("13490", "Norosí", "Norosí"),
			new ListaItem("13549", "Pinillos", "Pinillos"),
			new ListaItem("13580", "Regidor", "Regidor"),
			new ListaItem("13600", "Río Viejo ", "Río Viejo "),
			new ListaItem("13620", "San Cristóbal ", "San Cristóbal "),
			new ListaItem("13647", "San Estanislao ", "San Estanislao "),
			new ListaItem("13650", "San Fernando ", "San Fernando "),
			new ListaItem("13654", "San Jacinto ", "San Jacinto "),
			new ListaItem("13655", "San Jacinto Del Cauca", "San Jacinto Del Cauca"),
			new ListaItem("13657", "San Juan Nepomuceno", "San Juan Nepomuceno"),
			new ListaItem("13667", "San Martín De Loba", "San Martín De Loba"),
			new ListaItem("13670", "San Pablo ", "San Pablo "),
			new ListaItem("13673", "Santa Catalina ", "Santa Catalina "),
			new ListaItem("13683", "Santa Rosa ", "Santa Rosa "),
			new ListaItem("13688", "Santa Rosa Del Sur", "Santa Rosa Del Sur"),
			new ListaItem("13744", "Simití", "Simití"),
			new ListaItem("13760", "Soplaviento", "Soplaviento"),
			new ListaItem("13780", "Talaigua Nuevo ", "Talaigua Nuevo "),
			new ListaItem("13810", "Tiquisio", "Tiquisio"),
			new ListaItem("13836", "Turbaco", "Turbaco"),
			new ListaItem("13838", "Turbaná", "Turbaná"),
			new ListaItem("13873", "Villanueva", "Villanueva"),
			new ListaItem("13894", "Zambrano", "Zambrano"),
			new ListaItem("15001", "Tunja", "Tunja"),
			new ListaItem("15022", "Almeida", "Almeida"),
			new ListaItem("15047", "Aquitania", "Aquitania"),
			new ListaItem("15051", "Arcabuco", "Arcabuco"),
			new ListaItem("15087", "Belén", "Belén"),
			new ListaItem("15090", "Berbeo", "Berbeo"),
			new ListaItem("15092", "Betéitiva", "Betéitiva"),
			new ListaItem("15097", "Boavita", "Boavita"),
			new ListaItem("15104", "Boyacá", "Boyacá"),
			new ListaItem("15106", "Briceño", "Briceño"),
			new ListaItem("15109", "Buenavista", "Buenavista"),
			new ListaItem("15114", "Busbanzá", "Busbanzá"),
			new ListaItem("15131", "Caldas", "Caldas"),
			new ListaItem("15135", "Campohermoso", "Campohermoso"),
			new ListaItem("15162", "Cerinza", "Cerinza"),
			new ListaItem("15172", "Chinavita", "Chinavita"),
			new ListaItem("15176", "Chiquinquirá", "Chiquinquirá"),
			new ListaItem("15180", "Chiscas", "Chiscas"),
			new ListaItem("15183", "Chita", "Chita"),
			new ListaItem("15185", "Chitaraque", "Chitaraque"),
			new ListaItem("15187", "Chivatá", "Chivatá"),
			new ListaItem("15189", "Ciénega", "Ciénega"),
			new ListaItem("15204", "Cómbita", "Cómbita"),
			new ListaItem("15212", "Coper", "Coper"),
			new ListaItem("15215", "Corrales", "Corrales"),
			new ListaItem("15218", "Covarachía", "Covarachía"),
			new ListaItem("15223", "Cubará", "Cubará"),
			new ListaItem("15224", "Cucaita", "Cucaita"),
			new ListaItem("15226", "Cuítiva", "Cuítiva"),
			new ListaItem("15232", "Chíquiza", "Chíquiza"),
			new ListaItem("15236", "Chivor", "Chivor"),
			new ListaItem("15238", "Duitama", "Duitama"),
			new ListaItem("15244", "El Cocuy ", "El Cocuy "),
			new ListaItem("15248", "El Espino ", "El Espino "),
			new ListaItem("15272", "Firavitoba", "Firavitoba"),
			new ListaItem("15276", "Floresta", "Floresta"),
			new ListaItem("15293", "Gachantivá", "Gachantivá"),
			new ListaItem("15296", "Gámeza", "Gámeza"),
			new ListaItem("15299", "Garagoa", "Garagoa"),
			new ListaItem("15317", "Guacamayas", "Guacamayas"),
			new ListaItem("15322", "Guateque", "Guateque"),
			new ListaItem("15325", "Guayatá", "Guayatá"),
			new ListaItem("15332", "Güicán De La Sierra", "Güicán De La Sierra"),
			new ListaItem("15362", "Iza", "Iza"),
			new ListaItem("15367", "Jenesano", "Jenesano"),
			new ListaItem("15368", "Jericó", "Jericó"),
			new ListaItem("15377", "Labranzagrande", "Labranzagrande"),
			new ListaItem("15380", "La Capilla ", "La Capilla "),
			new ListaItem("15401", "La Victoria ", "La Victoria "),
			new ListaItem("15403", "La Uvita ", "La Uvita "),
			new ListaItem("15407", "Villa De Leyva", "Villa De Leyva"),
			new ListaItem("15425", "Macanal", "Macanal"),
			new ListaItem("15442", "Maripí", "Maripí"),
			new ListaItem("15455", "Miraflores", "Miraflores"),
			new ListaItem("15464", "Mongua", "Mongua"),
			new ListaItem("15466", "Monguí", "Monguí"),
			new ListaItem("15469", "Moniquirá", "Moniquirá"),
			new ListaItem("15476", "Motavita", "Motavita"),
			new ListaItem("15480", "Muzo", "Muzo"),
			new ListaItem("15491", "Nobsa", "Nobsa"),
			new ListaItem("15494", "Nuevo Colón ", "Nuevo Colón "),
			new ListaItem("15500", "Oicatá", "Oicatá"),
			new ListaItem("15507", "Otanche", "Otanche"),
			new ListaItem("15511", "Pachavita", "Pachavita"),
			new ListaItem("15514", "Páez", "Páez"),
			new ListaItem("15516", "Paipa", "Paipa"),
			new ListaItem("15518", "Pajarito", "Pajarito"),
			new ListaItem("15522", "Panqueba", "Panqueba"),
			new ListaItem("15531", "Pauna", "Pauna"),
			new ListaItem("15533", "Paya", "Paya"),
			new ListaItem("15537", "Paz De Río", "Paz De Río"),
			new ListaItem("15542", "Pesca", "Pesca"),
			new ListaItem("15550", "Pisba", "Pisba"),
			new ListaItem("15572", "Puerto Boyacá ", "Puerto Boyacá "),
			new ListaItem("15580", "Quípama", "Quípama"),
			new ListaItem("15599", "Ramiriquí", "Ramiriquí"),
			new ListaItem("15600", "Ráquira", "Ráquira"),
			new ListaItem("15621", "Rondón", "Rondón"),
			new ListaItem("15632", "Saboyá", "Saboyá"),
			new ListaItem("15638", "Sáchica", "Sáchica"),
			new ListaItem("15646", "Samacá", "Samacá"),
			new ListaItem("15660", "San Eduardo ", "San Eduardo "),
			new ListaItem("15664", "San José De Pare", "San José De Pare"),
			new ListaItem("15667", "San Luis De Gaceno", "San Luis De Gaceno"),
			new ListaItem("15673", "San Mateo ", "San Mateo "),
			new ListaItem("15676", "San Miguel De Sema", "San Miguel De Sema"),
			new ListaItem("15681", "San Pablo De Borbur", "San Pablo De Borbur"),
			new ListaItem("15686", "Santana", "Santana"),
			new ListaItem("15690", "Santa María ", "Santa María "),
			new ListaItem("15693", "Santa Rosa De Viterbo", "Santa Rosa De Viterbo"),
			new ListaItem("15696", "Santa Sofía ", "Santa Sofía "),
			new ListaItem("15720", "Sativanorte", "Sativanorte"),
			new ListaItem("15723", "Sativasur", "Sativasur"),
			new ListaItem("15740", "Siachoque", "Siachoque"),
			new ListaItem("15753", "Soatá", "Soatá"),
			new ListaItem("15755", "Socotá", "Socotá"),
			new ListaItem("15757", "Socha", "Socha"),
			new ListaItem("15759", "Sogamoso", "Sogamoso"),
			new ListaItem("15761", "Somondoco", "Somondoco"),
			new ListaItem("15762", "Sora", "Sora"),
			new ListaItem("15763", "Sotaquirá", "Sotaquirá"),
			new ListaItem("15764", "Soracá", "Soracá"),
			new ListaItem("15774", "Susacón", "Susacón"),
			new ListaItem("15776", "Sutamarchán", "Sutamarchán"),
			new ListaItem("15778", "Sutatenza", "Sutatenza"),
			new ListaItem("15790", "Tasco", "Tasco"),
			new ListaItem("15798", "Tenza", "Tenza"),
			new ListaItem("15804", "Tibaná", "Tibaná"),
			new ListaItem("15806", "Tibasosa", "Tibasosa"),
			new ListaItem("15808", "Tinjacá", "Tinjacá"),
			new ListaItem("15810", "Tipacoque", "Tipacoque"),
			new ListaItem("15814", "Toca", "Toca"),
			new ListaItem("15816", "Togüí", "Togüí"),
			new ListaItem("15820", "Tópaga", "Tópaga"),
			new ListaItem("15822", "Tota", "Tota"),
			new ListaItem("15832", "Tununguá", "Tununguá"),
			new ListaItem("15835", "Turmequé", "Turmequé"),
			new ListaItem("15837", "Tuta", "Tuta"),
			new ListaItem("15839", "Tutazá", "Tutazá"),
			new ListaItem("15842", "Úmbita", "Úmbita"),
			new ListaItem("15861", "Ventaquemada", "Ventaquemada"),
			new ListaItem("15879", "Viracachá", "Viracachá"),
			new ListaItem("15897", "Zetaquira", "Zetaquira"),
			new ListaItem("17001", "Manizales", "Manizales"),
			new ListaItem("17013", "Aguadas", "Aguadas"),
			new ListaItem("17042", "Anserma", "Anserma"),
			new ListaItem("17050", "Aranzazu", "Aranzazu"),
			new ListaItem("17088", "Belalcázar", "Belalcázar"),
			new ListaItem("17174", "Chinchiná", "Chinchiná"),
			new ListaItem("17272", "Filadelfia", "Filadelfia"),
			new ListaItem("17380", "La Dorada ", "La Dorada "),
			new ListaItem("17388", "La Merced ", "La Merced "),
			new ListaItem("17433", "Manzanares", "Manzanares"),
			new ListaItem("17442", "Marmato", "Marmato"),
			new ListaItem("17444", "Marquetalia", "Marquetalia"),
			new ListaItem("17446", "Marulanda", "Marulanda"),
			new ListaItem("17486", "Neira", "Neira"),
			new ListaItem("17495", "Norcasia", "Norcasia"),
			new ListaItem("17513", "Pácora", "Pácora"),
			new ListaItem("17524", "Palestina", "Palestina"),
			new ListaItem("17541", "Pensilvania", "Pensilvania"),
			new ListaItem("17614", "Riosucio", "Riosucio"),
			new ListaItem("17616", "Risaralda", "Risaralda"),
			new ListaItem("17653", "Salamina", "Salamina"),
			new ListaItem("17662", "Samaná", "Samaná"),
			new ListaItem("17665", "San José ", "San José "),
			new ListaItem("17777", "Supía", "Supía"),
			new ListaItem("17867", "Victoria", "Victoria"),
			new ListaItem("17873", "Villamaría", "Villamaría"),
			new ListaItem("17877", "Viterbo", "Viterbo"),
			new ListaItem("18001", "Florencia", "Florencia"),
			new ListaItem("18029", "Albania", "Albania"),
			new ListaItem("18094", "Belén De Los Andaquíes", "Belén De Los Andaquíes"),
			new ListaItem("18150", "Cartagena Del Chairá", "Cartagena Del Chairá"),
			new ListaItem("18205", "Curillo", "Curillo"),
			new ListaItem("18247", "El Doncello ", "El Doncello "),
			new ListaItem("18256", "El Paujíl ", "El Paujíl "),
			new ListaItem("18410", "La Montañita ", "La Montañita "),
			new ListaItem("18460", "Milán", "Milán"),
			new ListaItem("18479", "Morelia", "Morelia"),
			new ListaItem("18592", "Puerto Rico ", "Puerto Rico "),
			new ListaItem("18610", "San José Del Fragua", "San José Del Fragua"),
			new ListaItem("18753", "San Vicente Del Caguán", "San Vicente Del Caguán"),
			new ListaItem("18756", "Solano", "Solano"),
			new ListaItem("18785", "Solita", "Solita"),
			new ListaItem("18860", "Valparaíso", "Valparaíso"),
			new ListaItem("19001", "Popayán", "Popayán"),
			new ListaItem("19022", "Almaguer", "Almaguer"),
			new ListaItem("19050", "Argelia", "Argelia"),
			new ListaItem("19075", "Balboa", "Balboa"),
			new ListaItem("19100", "Bolívar", "Bolívar"),
			new ListaItem("19110", "Buenos Aires ", "Buenos Aires "),
			new ListaItem("19130", "Cajibío", "Cajibío"),
			new ListaItem("19137", "Caldono", "Caldono"),
			new ListaItem("19142", "Caloto", "Caloto"),
			new ListaItem("19212", "Corinto", "Corinto"),
			new ListaItem("19256", "El Tambo ", "El Tambo "),
			new ListaItem("19290", "Florencia", "Florencia"),
			new ListaItem("19300", "Guachené", "Guachené"),
			new ListaItem("19318", "Guapí", "Guapí"),
			new ListaItem("19355", "Inzá", "Inzá"),
			new ListaItem("19364", "Jambaló", "Jambaló"),
			new ListaItem("19392", "La Sierra ", "La Sierra "),
			new ListaItem("19397", "La Vega ", "La Vega "),
			new ListaItem("19418", "López De Micay", "López De Micay"),
			new ListaItem("19450", "Mercaderes", "Mercaderes"),
			new ListaItem("19455", "Miranda", "Miranda"),
			new ListaItem("19473", "Morales", "Morales"),
			new ListaItem("19513", "Padilla", "Padilla"),
			new ListaItem("19517", "Páez", "Páez"),
			new ListaItem("19532", "Patía", "Patía"),
			new ListaItem("19533", "Piamonte", "Piamonte"),
			new ListaItem("19548", "Piendamó - Tunía", "Piendamó - Tunía"),
			new ListaItem("19573", "Puerto Tejada ", "Puerto Tejada "),
			new ListaItem("19585", "Puracé", "Puracé"),
			new ListaItem("19622", "Rosas", "Rosas"),
			new ListaItem("19693", "San Sebastián ", "San Sebastián "),
			new ListaItem("19698", "Santander De Quilichao", "Santander De Quilichao"),
			new ListaItem("19701", "Santa Rosa ", "Santa Rosa "),
			new ListaItem("19743", "Silvia", "Silvia"),
			new ListaItem("19760", "Sotara", "Sotara"),
			new ListaItem("19780", "Suárez", "Suárez"),
			new ListaItem("19785", "Sucre", "Sucre"),
			new ListaItem("19807", "Timbío", "Timbío"),
			new ListaItem("19809", "Timbiquí", "Timbiquí"),
			new ListaItem("19821", "Toribío", "Toribío"),
			new ListaItem("19824", "Totoró", "Totoró"),
			new ListaItem("19845", "Villa Rica ", "Villa Rica "),
			new ListaItem("20001", "Valledupar", "Valledupar"),
			new ListaItem("20011", "Aguachica", "Aguachica"),
			new ListaItem("20013", "Agustín Codazzi ", "Agustín Codazzi "),
			new ListaItem("20032", "Astrea", "Astrea"),
			new ListaItem("20045", "Becerril", "Becerril"),
			new ListaItem("20060", "Bosconia", "Bosconia"),
			new ListaItem("20175", "Chimichagua", "Chimichagua"),
			new ListaItem("20178", "Chiriguaná", "Chiriguaná"),
			new ListaItem("20228", "Curumaní", "Curumaní"),
			new ListaItem("20238", "El Copey ", "El Copey "),
			new ListaItem("20250", "El Paso ", "El Paso "),
			new ListaItem("20295", "Gamarra", "Gamarra"),
			new ListaItem("20310", "González", "González"),
			new ListaItem("20383", "La Gloria ", "La Gloria "),
			new ListaItem("20400", "La Jagua De Ibirico", "La Jagua De Ibirico"),
			new ListaItem("20443", "Manaure Balcón Del Cesar", "Manaure Balcón Del Cesar"),
			new ListaItem("20517", "Pailitas", "Pailitas"),
			new ListaItem("20550", "Pelaya", "Pelaya"),
			new ListaItem("20570", "Pueblo Bello ", "Pueblo Bello "),
			new ListaItem("20614", "Río De Oro", "Río De Oro"),
			new ListaItem("20621", "La Paz ", "La Paz "),
			new ListaItem("20710", "San Alberto ", "San Alberto "),
			new ListaItem("20750", "San Diego ", "San Diego "),
			new ListaItem("20770", "San Martín ", "San Martín "),
			new ListaItem("20787", "Tamalameque", "Tamalameque"),
			new ListaItem("23001", "Montería", "Montería"),
			new ListaItem("23068", "Ayapel", "Ayapel"),
			new ListaItem("23079", "Buenavista", "Buenavista"),
			new ListaItem("23090", "Canalete", "Canalete"),
			new ListaItem("23162", "Cereté", "Cereté"),
			new ListaItem("23168", "Chimá", "Chimá"),
			new ListaItem("23182", "Chinú", "Chinú"),
			new ListaItem("23189", "Ciénaga De Oro", "Ciénaga De Oro"),
			new ListaItem("23300", "Cotorra", "Cotorra"),
			new ListaItem("23350", "La Apartada ", "La Apartada "),
			new ListaItem("23417", "Lorica", "Lorica"),
			new ListaItem("23419", "Los Córdobas ", "Los Córdobas "),
			new ListaItem("23464", "Momil", "Momil"),
			new ListaItem("23466", "Montelíbano", "Montelíbano"),
			new ListaItem("23500", "Moñitos", "Moñitos"),
			new ListaItem("23555", "Planeta Rica ", "Planeta Rica "),
			new ListaItem("23570", "Pueblo Nuevo ", "Pueblo Nuevo "),
			new ListaItem("23574", "Puerto Escondido ", "Puerto Escondido "),
			new ListaItem("23580", "Puerto Libertador ", "Puerto Libertador "),
			new ListaItem("23586", "Purísima De La Concepción", "Purísima De La Concepción"),
			new ListaItem("23660", "Sahagún", "Sahagún"),
			new ListaItem("23670", "San Andrés De Sotavento", "San Andrés De Sotavento"),
			new ListaItem("23672", "San Antero ", "San Antero "),
			new ListaItem("23675", "San Bernardo Del Viento", "San Bernardo Del Viento"),
			new ListaItem("23678", "San Carlos ", "San Carlos "),
			new ListaItem("23682", "San José De Uré", "San José De Uré"),
			new ListaItem("23686", "San Pelayo ", "San Pelayo "),
			new ListaItem("23807", "Tierralta", "Tierralta"),
			new ListaItem("23815", "Tuchín", "Tuchín"),
			new ListaItem("23855", "Valencia", "Valencia"),
			new ListaItem("25001", "Agua De Dios", "Agua De Dios"),
			new ListaItem("25019", "Albán", "Albán"),
			new ListaItem("25035", "Anapoima", "Anapoima"),
			new ListaItem("25040", "Anolaima", "Anolaima"),
			new ListaItem("25053", "Arbeláez", "Arbeláez"),
			new ListaItem("25086", "Beltrán", "Beltrán"),
			new ListaItem("25095", "Bituima", "Bituima"),
			new ListaItem("25099", "Bojacá", "Bojacá"),
			new ListaItem("25120", "Cabrera", "Cabrera"),
			new ListaItem("25123", "Cachipay", "Cachipay"),
			new ListaItem("25126", "Cajicá", "Cajicá"),
			new ListaItem("25148", "Caparrapí", "Caparrapí"),
			new ListaItem("25151", "Cáqueza", "Cáqueza"),
			new ListaItem("25154", "Carmen De Carupa", "Carmen De Carupa"),
			new ListaItem("25168", "Chaguaní", "Chaguaní"),
			new ListaItem("25175", "Chía", "Chía"),
			new ListaItem("25178", "Chipaque", "Chipaque"),
			new ListaItem("25181", "Choachí", "Choachí"),
			new ListaItem("25183", "Chocontá", "Chocontá"),
			new ListaItem("25200", "Cogua", "Cogua"),
			new ListaItem("25214", "Cota", "Cota"),
			new ListaItem("25224", "Cucunubá", "Cucunubá"),
			new ListaItem("25245", "El Colegio ", "El Colegio "),
			new ListaItem("25258", "El Peñón ", "El Peñón "),
			new ListaItem("25260", "El Rosal ", "El Rosal "),
			new ListaItem("25269", "Facatativá", "Facatativá"),
			new ListaItem("25279", "Fómeque", "Fómeque"),
			new ListaItem("25281", "Fosca", "Fosca"),
			new ListaItem("25286", "Funza", "Funza"),
			new ListaItem("25288", "Fúquene", "Fúquene"),
			new ListaItem("25290", "Fusagasugá", "Fusagasugá"),
			new ListaItem("25293", "Gachalá", "Gachalá"),
			new ListaItem("25295", "Gachancipá", "Gachancipá"),
			new ListaItem("25297", "Gachetá", "Gachetá"),
			new ListaItem("25299", "Gama", "Gama"),
			new ListaItem("25307", "Girardot", "Girardot"),
			new ListaItem("25312", "Granada", "Granada"),
			new ListaItem("25317", "Guachetá", "Guachetá"),
			new ListaItem("25320", "Guaduas", "Guaduas"),
			new ListaItem("25322", "Guasca", "Guasca"),
			new ListaItem("25324", "Guataquí", "Guataquí"),
			new ListaItem("25326", "Guatavita", "Guatavita"),
			new ListaItem("25328", "Guayabal De Síquima", "Guayabal De Síquima"),
			new ListaItem("25335", "Guayabetal", "Guayabetal"),
			new ListaItem("25339", "Gutiérrez", "Gutiérrez"),
			new ListaItem("25368", "Jerusalén", "Jerusalén"),
			new ListaItem("25372", "Junín", "Junín"),
			new ListaItem("25377", "La Calera ", "La Calera "),
			new ListaItem("25386", "La Mesa ", "La Mesa "),
			new ListaItem("25394", "La Palma ", "La Palma "),
			new ListaItem("25398", "La Peña ", "La Peña "),
			new ListaItem("25402", "La Vega ", "La Vega "),
			new ListaItem("25407", "Lenguazaque", "Lenguazaque"),
			new ListaItem("25426", "Machetá", "Machetá"),
			new ListaItem("25430", "Madrid", "Madrid"),
			new ListaItem("25436", "Manta", "Manta"),
			new ListaItem("25438", "Medina", "Medina"),
			new ListaItem("25473", "Mosquera", "Mosquera"),
			new ListaItem("25483", "Nariño", "Nariño"),
			new ListaItem("25486", "Nemocón", "Nemocón"),
			new ListaItem("25488", "Nilo", "Nilo"),
			new ListaItem("25489", "Nimaima", "Nimaima"),
			new ListaItem("25491", "Nocaima", "Nocaima"),
			new ListaItem("25506", "Venecia", "Venecia"),
			new ListaItem("25513", "Pacho", "Pacho"),
			new ListaItem("25518", "Paime", "Paime"),
			new ListaItem("25524", "Pandi", "Pandi"),
			new ListaItem("25530", "Paratebueno", "Paratebueno"),
			new ListaItem("25535", "Pasca", "Pasca"),
			new ListaItem("25572", "Puerto Salgar ", "Puerto Salgar "),
			new ListaItem("25580", "Pulí", "Pulí"),
			new ListaItem("25592", "Quebradanegra", "Quebradanegra"),
			new ListaItem("25594", "Quetame", "Quetame"),
			new ListaItem("25596", "Quipile", "Quipile"),
			new ListaItem("25599", "Apulo", "Apulo"),
			new ListaItem("25612", "Ricaurte", "Ricaurte"),
			new ListaItem("25645", "San Antonio Del Tequendama", "San Antonio Del Tequendama"),
			new ListaItem("25649", "San Bernardo ", "San Bernardo "),
			new ListaItem("25653", "San Cayetano ", "San Cayetano "),
			new ListaItem("25658", "San Francisco ", "San Francisco "),
			new ListaItem("25662", "San Juan De Rioseco", "San Juan De Rioseco"),
			new ListaItem("25718", "Sasaima", "Sasaima"),
			new ListaItem("25736", "Sesquilé", "Sesquilé"),
			new ListaItem("25740", "Sibaté", "Sibaté"),
			new ListaItem("25743", "Silvania", "Silvania"),
			new ListaItem("25745", "Simijaca", "Simijaca"),
			new ListaItem("25754", "Soacha", "Soacha"),
			new ListaItem("25758", "Sopó", "Sopó"),
			new ListaItem("25769", "Subachoque", "Subachoque"),
			new ListaItem("25772", "Suesca", "Suesca"),
			new ListaItem("25777", "Supatá", "Supatá"),
			new ListaItem("25779", "Susa", "Susa"),
			new ListaItem("25781", "Sutatausa", "Sutatausa"),
			new ListaItem("25785", "Tabio", "Tabio"),
			new ListaItem("25793", "Tausa", "Tausa"),
			new ListaItem("25797", "Tena", "Tena"),
			new ListaItem("25799", "Tenjo", "Tenjo"),
			new ListaItem("25805", "Tibacuy", "Tibacuy"),
			new ListaItem("25807", "Tibirita", "Tibirita"),
			new ListaItem("25815", "Tocaima", "Tocaima"),
			new ListaItem("25817", "Tocancipá", "Tocancipá"),
			new ListaItem("25823", "Topaipí", "Topaipí"),
			new ListaItem("25839", "Ubalá", "Ubalá"),
			new ListaItem("25841", "Ubaque", "Ubaque"),
			new ListaItem("25843", "Villa De San Diego De Ubaté", "Villa De San Diego De Ubaté"),
			new ListaItem("25845", "Une", "Une"),
			new ListaItem("25851", "Útica", "Útica"),
			new ListaItem("25862", "Vergara", "Vergara"),
			new ListaItem("25867", "Vianí", "Vianí"),
			new ListaItem("25871", "Villagómez", "Villagómez"),
			new ListaItem("25873", "Villapinzón", "Villapinzón"),
			new ListaItem("25875", "Villeta", "Villeta"),
			new ListaItem("25878", "Viotá", "Viotá"),
			new ListaItem("25885", "Yacopí", "Yacopí"),
			new ListaItem("25898", "Zipacón", "Zipacón"),
			new ListaItem("25899", "Zipaquirá", "Zipaquirá"),
			new ListaItem("27001", "Quibdó", "Quibdó"),
			new ListaItem("27006", "Acandí", "Acandí"),
			new ListaItem("27025", "Alto Baudó ", "Alto Baudó "),
			new ListaItem("27050", "Atrato", "Atrato"),
			new ListaItem("27073", "Bagadó", "Bagadó"),
			new ListaItem("27075", "Bahía Solano ", "Bahía Solano "),
			new ListaItem("27077", "Bajo Baudó ", "Bajo Baudó "),
			new ListaItem("27099", "Bojayá", "Bojayá"),
			new ListaItem("27135", "El Cantón Del San Pablo ", "El Cantón Del San Pablo "),
			new ListaItem("27150", "Carmen Del Darién", "Carmen Del Darién"),
			new ListaItem("27160", "Cértegui", "Cértegui"),
			new ListaItem("27205", "Condoto", "Condoto"),
			new ListaItem("27245", "El Carmen De Atrato", "El Carmen De Atrato"),
			new ListaItem("27250", "El Litoral Del San Juan ", "El Litoral Del San Juan "),
			new ListaItem("27361", "Istmina", "Istmina"),
			new ListaItem("27372", "Juradó", "Juradó"),
			new ListaItem("27413", "Lloró", "Lloró"),
			new ListaItem("27425", "Medio Atrato ", "Medio Atrato "),
			new ListaItem("27430", "Medio Baudó ", "Medio Baudó "),
			new ListaItem("27450", "Medio San Juan", "Medio San Juan"),
			new ListaItem("27491", "Nóvita", "Nóvita"),
			new ListaItem("27495", "Nuquí", "Nuquí"),
			new ListaItem("27580", "Río Iró ", "Río Iró "),
			new ListaItem("27600", "Río Quito ", "Río Quito "),
			new ListaItem("27615", "Riosucio", "Riosucio"),
			new ListaItem("27660", "San José Del Palmar", "San José Del Palmar"),
			new ListaItem("27745", "Sipí", "Sipí"),
			new ListaItem("27787", "Tadó", "Tadó"),
			new ListaItem("27800", "Unguía", "Unguía"),
			new ListaItem("27810", "Unión Panamericana ", "Unión Panamericana "),
			new ListaItem("41001", "Neiva", "Neiva"),
			new ListaItem("41006", "Acevedo", "Acevedo"),
			new ListaItem("41013", "Agrado", "Agrado"),
			new ListaItem("41016", "Aipe", "Aipe"),
			new ListaItem("41020", "Algeciras", "Algeciras"),
			new ListaItem("41026", "Altamira", "Altamira"),
			new ListaItem("41078", "Baraya", "Baraya"),
			new ListaItem("41132", "Campoalegre", "Campoalegre"),
			new ListaItem("41206", "Colombia", "Colombia"),
			new ListaItem("41244", "Elías", "Elías"),
			new ListaItem("41298", "Garzón", "Garzón"),
			new ListaItem("41306", "Gigante", "Gigante"),
			new ListaItem("41319", "Guadalupe", "Guadalupe"),
			new ListaItem("41349", "Hobo", "Hobo"),
			new ListaItem("41357", "Íquira", "Íquira"),
			new ListaItem("41359", "Isnos", "Isnos"),
			new ListaItem("41378", "La Argentina ", "La Argentina "),
			new ListaItem("41396", "La Plata ", "La Plata "),
			new ListaItem("41483", "Nátaga", "Nátaga"),
			new ListaItem("41503", "Oporapa", "Oporapa"),
			new ListaItem("41518", "Paicol", "Paicol"),
			new ListaItem("41524", "Palermo", "Palermo"),
			new ListaItem("41530", "Palestina", "Palestina"),
			new ListaItem("41548", "Pital", "Pital"),
			new ListaItem("41551", "Pitalito", "Pitalito"),
			new ListaItem("41615", "Rivera", "Rivera"),
			new ListaItem("41660", "Saladoblanco", "Saladoblanco"),
			new ListaItem("41668", "San Agustín ", "San Agustín "),
			new ListaItem("41676", "Santa María ", "Santa María "),
			new ListaItem("41770", "Suaza", "Suaza"),
			new ListaItem("41791", "Tarqui", "Tarqui"),
			new ListaItem("41797", "Tesalia", "Tesalia"),
			new ListaItem("41799", "Tello", "Tello"),
			new ListaItem("41801", "Teruel", "Teruel"),
			new ListaItem("41807", "Timaná", "Timaná"),
			new ListaItem("41872", "Villavieja", "Villavieja"),
			new ListaItem("41885", "Yaguará", "Yaguará"),
			new ListaItem("44001", "Riohacha", "Riohacha"),
			new ListaItem("44035", "Albania", "Albania"),
			new ListaItem("44078", "Barrancas", "Barrancas"),
			new ListaItem("44090", "Dibulla", "Dibulla"),
			new ListaItem("44098", "Distracción", "Distracción"),
			new ListaItem("44110", "El Molino ", "El Molino "),
			new ListaItem("44279", "Fonseca", "Fonseca"),
			new ListaItem("44378", "Hatonuevo", "Hatonuevo"),
			new ListaItem("44420", "La Jagua Del Pilar", "La Jagua Del Pilar"),
			new ListaItem("44430", "Maicao", "Maicao"),
			new ListaItem("44560", "Manaure", "Manaure"),
			new ListaItem("44650", "San Juan Del Cesar", "San Juan Del Cesar"),
			new ListaItem("44847", "Uribia", "Uribia"),
			new ListaItem("44855", "Urumita", "Urumita"),
			new ListaItem("44874", "Villanueva", "Villanueva"),
			new ListaItem("47001", "Santa Marta ", "Santa Marta "),
			new ListaItem("47030", "Algarrobo", "Algarrobo"),
			new ListaItem("47053", "Aracataca", "Aracataca"),
			new ListaItem("47058", "Ariguaní", "Ariguaní"),
			new ListaItem("47161", "Cerro De San Antonio", "Cerro De San Antonio"),
			new ListaItem("47170", "Chivolo", "Chivolo"),
			new ListaItem("47189", "Ciénaga", "Ciénaga"),
			new ListaItem("47205", "Concordia", "Concordia"),
			new ListaItem("47245", "El Banco ", "El Banco "),
			new ListaItem("47258", "El Piñón ", "El Piñón "),
			new ListaItem("47268", "El Retén ", "El Retén "),
			new ListaItem("47288", "Fundación", "Fundación"),
			new ListaItem("47318", "Guamal", "Guamal"),
			new ListaItem("47460", "Nueva Granada ", "Nueva Granada "),
			new ListaItem("47541", "Pedraza", "Pedraza"),
			new ListaItem("47545", "Pijiño Del Carmen", "Pijiño Del Carmen"),
			new ListaItem("47551", "Pivijay", "Pivijay"),
			new ListaItem("47555", "Plato", "Plato"),
			new ListaItem("47570", "Puebloviejo", "Puebloviejo"),
			new ListaItem("47605", "Remolino", "Remolino"),
			new ListaItem("47660", "Sabanas De San Ángel", "Sabanas De San Ángel"),
			new ListaItem("47675", "Salamina", "Salamina"),
			new ListaItem("47692", "San Sebastián De Buenavista", "San Sebastián De Buenavista"),
			new ListaItem("47703", "San Zenón ", "San Zenón "),
			new ListaItem("47707", "Santa Ana ", "Santa Ana "),
			new ListaItem("47720", "Santa Bárbara De Pinto", "Santa Bárbara De Pinto"),
			new ListaItem("47745", "Sitionuevo", "Sitionuevo"),
			new ListaItem("47798", "Tenerife", "Tenerife"),
			new ListaItem("47960", "Zapayán", "Zapayán"),
			new ListaItem("47980", "Zona Bananera ", "Zona Bananera "),
			new ListaItem("50001", "Villavicencio", "Villavicencio"),
			new ListaItem("50006", "Acacías", "Acacías"),
			new ListaItem("50110", "Barranca De Upía", "Barranca De Upía"),
			new ListaItem("50124", "Cabuyaro", "Cabuyaro"),
			new ListaItem("50150", "Castilla La Nueva", "Castilla La Nueva"),
			new ListaItem("50223", "Cubarral", "Cubarral"),
			new ListaItem("50226", "Cumaral", "Cumaral"),
			new ListaItem("50245", "El Calvario ", "El Calvario "),
			new ListaItem("50251", "El Castillo ", "El Castillo "),
			new ListaItem("50270", "El Dorado ", "El Dorado "),
			new ListaItem("50287", "Fuente De Oro", "Fuente De Oro"),
			new ListaItem("50313", "Granada", "Granada"),
			new ListaItem("50318", "Guamal", "Guamal"),
			new ListaItem("50325", "Mapiripán", "Mapiripán"),
			new ListaItem("50330", "Mesetas", "Mesetas"),
			new ListaItem("50350", "La Macarena ", "La Macarena "),
			new ListaItem("50370", "Uribe", "Uribe"),
			new ListaItem("50400", "Lejanías", "Lejanías"),
			new ListaItem("50450", "Puerto Concordia ", "Puerto Concordia "),
			new ListaItem("50568", "Puerto Gaitán ", "Puerto Gaitán "),
			new ListaItem("50573", "Puerto López ", "Puerto López "),
			new ListaItem("50577", "Puerto Lleras ", "Puerto Lleras "),
			new ListaItem("50590", "Puerto Rico ", "Puerto Rico "),
			new ListaItem("50606", "Restrepo", "Restrepo"),
			new ListaItem("50680", "San Carlos De Guaroa", "San Carlos De Guaroa"),
			new ListaItem("50683", "San Juan De Arama", "San Juan De Arama"),
			new ListaItem("50686", "San Juanito ", "San Juanito "),
			new ListaItem("50689", "San Martín ", "San Martín "),
			new ListaItem("50711", "Vistahermosa", "Vistahermosa"),
			new ListaItem("52001", "Pasto", "Pasto"),
			new ListaItem("52019", "Albán", "Albán"),
			new ListaItem("52022", "Aldana", "Aldana"),
			new ListaItem("52036", "Ancuyá", "Ancuyá"),
			new ListaItem("52051", "Arboleda", "Arboleda"),
			new ListaItem("52079", "Barbacoas", "Barbacoas"),
			new ListaItem("52083", "Belén", "Belén"),
			new ListaItem("52110", "Buesaco", "Buesaco"),
			new ListaItem("52203", "Colón", "Colón"),
			new ListaItem("52207", "Consacá", "Consacá"),
			new ListaItem("52210", "Contadero", "Contadero"),
			new ListaItem("52215", "Córdoba", "Córdoba"),
			new ListaItem("52224", "Cuaspúd", "Cuaspúd"),
			new ListaItem("52227", "Cumbal", "Cumbal"),
			new ListaItem("52233", "Cumbitara", "Cumbitara"),
			new ListaItem("52240", "Chachagüí", "Chachagüí"),
			new ListaItem("52250", "El Charco ", "El Charco "),
			new ListaItem("52254", "El Peñol ", "El Peñol "),
			new ListaItem("52256", "El Rosario ", "El Rosario "),
			new ListaItem("52258", "El Tablón De Gómez", "El Tablón De Gómez"),
			new ListaItem("52260", "El Tambo ", "El Tambo "),
			new ListaItem("52287", "Funes", "Funes"),
			new ListaItem("52317", "Guachucal", "Guachucal"),
			new ListaItem("52320", "Guaitarilla", "Guaitarilla"),
			new ListaItem("52323", "Gualmatán", "Gualmatán"),
			new ListaItem("52352", "Iles", "Iles"),
			new ListaItem("52354", "Imués", "Imués"),
			new ListaItem("52356", "Ipiales", "Ipiales"),
			new ListaItem("52378", "La Cruz ", "La Cruz "),
			new ListaItem("52381", "La Florida ", "La Florida "),
			new ListaItem("52385", "La Llanada ", "La Llanada "),
			new ListaItem("52390", "La Tola ", "La Tola "),
			new ListaItem("52399", "La Unión ", "La Unión "),
			new ListaItem("52405", "Leiva", "Leiva"),
			new ListaItem("52411", "Linares", "Linares"),
			new ListaItem("52418", "Los Andes ", "Los Andes "),
			new ListaItem("52427", "Magüí", "Magüí"),
			new ListaItem("52435", "Mallama", "Mallama"),
			new ListaItem("52473", "Mosquera", "Mosquera"),
			new ListaItem("52480", "Nariño", "Nariño"),
			new ListaItem("52490", "Olaya Herrera ", "Olaya Herrera "),
			new ListaItem("52506", "Ospina", "Ospina"),
			new ListaItem("52520", "Francisco Pizarro ", "Francisco Pizarro "),
			new ListaItem("52540", "Policarpa", "Policarpa"),
			new ListaItem("52560", "Potosí", "Potosí"),
			new ListaItem("52565", "Providencia", "Providencia"),
			new ListaItem("52573", "Puerres", "Puerres"),
			new ListaItem("52585", "Pupiales", "Pupiales"),
			new ListaItem("52612", "Ricaurte", "Ricaurte"),
			new ListaItem("52621", "Roberto Payán ", "Roberto Payán "),
			new ListaItem("52678", "Samaniego", "Samaniego"),
			new ListaItem("52683", "Sandoná", "Sandoná"),
			new ListaItem("52685", "San Bernardo ", "San Bernardo "),
			new ListaItem("52687", "San Lorenzo ", "San Lorenzo "),
			new ListaItem("52693", "San Pablo ", "San Pablo "),
			new ListaItem("52694", "San Pedro De Cartago", "San Pedro De Cartago"),
			new ListaItem("52696", "Santa Bárbara ", "Santa Bárbara "),
			new ListaItem("52699", "Santacruz", "Santacruz"),
			new ListaItem("52720", "Sapuyes", "Sapuyes"),
			new ListaItem("52786", "Taminango", "Taminango"),
			new ListaItem("52788", "Tangua", "Tangua"),
			new ListaItem("52835", "San Andrés De Tumaco", "San Andrés De Tumaco"),
			new ListaItem("52838", "Túquerres", "Túquerres"),
			new ListaItem("52885", "Yacuanquer", "Yacuanquer"),
			new ListaItem("54001", "San José De Cúcuta", "San José De Cúcuta"),
			new ListaItem("54003", "Ábrego", "Ábrego"),
			new ListaItem("54051", "Arboledas", "Arboledas"),
			new ListaItem("54099", "Bochalema", "Bochalema"),
			new ListaItem("54109", "Bucarasica", "Bucarasica"),
			new ListaItem("54125", "Cácota", "Cácota"),
			new ListaItem("54128", "Cáchira", "Cáchira"),
			new ListaItem("54172", "Chinácota", "Chinácota"),
			new ListaItem("54174", "Chitagá", "Chitagá"),
			new ListaItem("54206", "Convención", "Convención"),
			new ListaItem("54223", "Cucutilla", "Cucutilla"),
			new ListaItem("54239", "Durania", "Durania"),
			new ListaItem("54245", "El Carmen ", "El Carmen "),
			new ListaItem("54250", "El Tarra ", "El Tarra "),
			new ListaItem("54261", "El Zulia ", "El Zulia "),
			new ListaItem("54313", "Gramalote", "Gramalote"),
			new ListaItem("54344", "Hacarí", "Hacarí"),
			new ListaItem("54347", "Herrán", "Herrán"),
			new ListaItem("54377", "Labateca", "Labateca"),
			new ListaItem("54385", "La Esperanza ", "La Esperanza "),
			new ListaItem("54398", "La Playa ", "La Playa "),
			new ListaItem("54405", "Los Patios ", "Los Patios "),
			new ListaItem("54418", "Lourdes", "Lourdes"),
			new ListaItem("54480", "Mutiscua", "Mutiscua"),
			new ListaItem("54498", "Ocaña", "Ocaña"),
			new ListaItem("54518", "Pamplona", "Pamplona"),
			new ListaItem("54520", "Pamplonita", "Pamplonita"),
			new ListaItem("54553", "Puerto Santander ", "Puerto Santander "),
			new ListaItem("54599", "Ragonvalia", "Ragonvalia"),
			new ListaItem("54660", "Salazar", "Salazar"),
			new ListaItem("54670", "San Calixto ", "San Calixto "),
			new ListaItem("54673", "San Cayetano ", "San Cayetano "),
			new ListaItem("54680", "Santiago", "Santiago"),
			new ListaItem("54720", "Sardinata", "Sardinata"),
			new ListaItem("54743", "Silos", "Silos"),
			new ListaItem("54800", "Teorama", "Teorama"),
			new ListaItem("54810", "Tibú", "Tibú"),
			new ListaItem("54820", "Toledo", "Toledo"),
			new ListaItem("54871", "Villa Caro ", "Villa Caro "),
			new ListaItem("54874", "Villa Del Rosario", "Villa Del Rosario"),
			new ListaItem("63001", "Armenia", "Armenia"),
			new ListaItem("63111", "Buenavista", "Buenavista"),
			new ListaItem("63130", "Calarcá", "Calarcá"),
			new ListaItem("63190", "Circasia", "Circasia"),
			new ListaItem("63212", "Córdoba", "Córdoba"),
			new ListaItem("63272", "Filandia", "Filandia"),
			new ListaItem("63302", "Génova", "Génova"),
			new ListaItem("63401", "La Tebaida ", "La Tebaida "),
			new ListaItem("63470", "Montenegro", "Montenegro"),
			new ListaItem("63548", "Pijao", "Pijao"),
			new ListaItem("63594", "Quimbaya", "Quimbaya"),
			new ListaItem("63690", "Salento", "Salento"),
			new ListaItem("66001", "Pereira", "Pereira"),
			new ListaItem("66045", "Apía", "Apía"),
			new ListaItem("66075", "Balboa", "Balboa"),
			new ListaItem("66088", "Belén De Umbría", "Belén De Umbría"),
			new ListaItem("66170", "Dosquebradas", "Dosquebradas"),
			new ListaItem("66318", "Guática", "Guática"),
			new ListaItem("66383", "La Celia ", "La Celia "),
			new ListaItem("66400", "La Virginia ", "La Virginia "),
			new ListaItem("66440", "Marsella", "Marsella"),
			new ListaItem("66456", "Mistrató", "Mistrató"),
			new ListaItem("66572", "Pueblo Rico ", "Pueblo Rico "),
			new ListaItem("66594", "Quinchía", "Quinchía"),
			new ListaItem("66682", "Santa Rosa De Cabal", "Santa Rosa De Cabal"),
			new ListaItem("66687", "Santuario", "Santuario"),
			new ListaItem("68001", "Bucaramanga", "Bucaramanga"),
			new ListaItem("68013", "Aguada", "Aguada"),
			new ListaItem("68020", "Albania", "Albania"),
			new ListaItem("68051", "Aratoca", "Aratoca"),
			new ListaItem("68077", "Barbosa", "Barbosa"),
			new ListaItem("68079", "Barichara", "Barichara"),
			new ListaItem("68081", "Barrancabermeja", "Barrancabermeja"),
			new ListaItem("68092", "Betulia", "Betulia"),
			new ListaItem("68101", "Bolívar", "Bolívar"),
			new ListaItem("68121", "Cabrera", "Cabrera"),
			new ListaItem("68132", "California", "California"),
			new ListaItem("68147", "Capitanejo", "Capitanejo"),
			new ListaItem("68152", "Carcasí", "Carcasí"),
			new ListaItem("68160", "Cepitá", "Cepitá"),
			new ListaItem("68162", "Cerrito", "Cerrito"),
			new ListaItem("68167", "Charalá", "Charalá"),
			new ListaItem("68169", "Charta", "Charta"),
			new ListaItem("68176", "Chima", "Chima"),
			new ListaItem("68179", "Chipatá", "Chipatá"),
			new ListaItem("68190", "Cimitarra", "Cimitarra"),
			new ListaItem("68207", "Concepción", "Concepción"),
			new ListaItem("68209", "Confines", "Confines"),
			new ListaItem("68211", "Contratación", "Contratación"),
			new ListaItem("68217", "Coromoro", "Coromoro"),
			new ListaItem("68229", "Curití", "Curití"),
			new ListaItem("68235", "El Carmen De Chucurí", "El Carmen De Chucurí"),
			new ListaItem("68245", "El Guacamayo ", "El Guacamayo "),
			new ListaItem("68250", "El Peñón ", "El Peñón "),
			new ListaItem("68255", "El Playón ", "El Playón "),
			new ListaItem("68264", "Encino", "Encino"),
			new ListaItem("68266", "Enciso", "Enciso"),
			new ListaItem("68271", "Florián", "Florián"),
			new ListaItem("68276", "Floridablanca", "Floridablanca"),
			new ListaItem("68296", "Galán", "Galán"),
			new ListaItem("68298", "Gámbita", "Gámbita"),
			new ListaItem("68307", "Girón", "Girón"),
			new ListaItem("68318", "Guaca", "Guaca"),
			new ListaItem("68320", "Guadalupe", "Guadalupe"),
			new ListaItem("68322", "Guapotá", "Guapotá"),
			new ListaItem("68324", "Guavatá", "Guavatá"),
			new ListaItem("68327", "Güepsa", "Güepsa"),
			new ListaItem("68344", "Hato", "Hato"),
			new ListaItem("68368", "Jesús María ", "Jesús María "),
			new ListaItem("68370", "Jordán", "Jordán"),
			new ListaItem("68377", "La Belleza ", "La Belleza "),
			new ListaItem("68385", "Landázuri", "Landázuri"),
			new ListaItem("68397", "La Paz ", "La Paz "),
			new ListaItem("68406", "Lebrija", "Lebrija"),
			new ListaItem("68418", "Los Santos ", "Los Santos "),
			new ListaItem("68425", "Macaravita", "Macaravita"),
			new ListaItem("68432", "Málaga", "Málaga"),
			new ListaItem("68444", "Matanza", "Matanza"),
			new ListaItem("68464", "Mogotes", "Mogotes"),
			new ListaItem("68468", "Molagavita", "Molagavita"),
			new ListaItem("68498", "Ocamonte", "Ocamonte"),
			new ListaItem("68500", "Oiba", "Oiba"),
			new ListaItem("68502", "Onzaga", "Onzaga"),
			new ListaItem("68522", "Palmar", "Palmar"),
			new ListaItem("68524", "Palmas Del Socorro", "Palmas Del Socorro"),
			new ListaItem("68533", "Páramo", "Páramo"),
			new ListaItem("68547", "Piedecuesta", "Piedecuesta"),
			new ListaItem("68549", "Pinchote", "Pinchote"),
			new ListaItem("68572", "Puente Nacional ", "Puente Nacional "),
			new ListaItem("68573", "Puerto Parra ", "Puerto Parra "),
			new ListaItem("68575", "Puerto Wilches ", "Puerto Wilches "),
			new ListaItem("68615", "Rionegro", "Rionegro"),
			new ListaItem("68655", "Sabana De Torres", "Sabana De Torres"),
			new ListaItem("68669", "San Andrés ", "San Andrés "),
			new ListaItem("68673", "San Benito ", "San Benito "),
			new ListaItem("68679", "San Gil ", "San Gil "),
			new ListaItem("68682", "San Joaquín ", "San Joaquín "),
			new ListaItem("68684", "San José De Miranda", "San José De Miranda"),
			new ListaItem("68686", "San Miguel ", "San Miguel "),
			new ListaItem("68689", "San Vicente De Chucurí", "San Vicente De Chucurí"),
			new ListaItem("68705", "Santa Bárbara ", "Santa Bárbara "),
			new ListaItem("68720", "Santa Helena Del Opón", "Santa Helena Del Opón"),
			new ListaItem("68745", "Simacota", "Simacota"),
			new ListaItem("68755", "Socorro", "Socorro"),
			new ListaItem("68770", "Suaita", "Suaita"),
			new ListaItem("68773", "Sucre", "Sucre"),
			new ListaItem("68780", "Suratá", "Suratá"),
			new ListaItem("68820", "Tona", "Tona"),
			new ListaItem("68855", "Valle De San José", "Valle De San José"),
			new ListaItem("68861", "Vélez", "Vélez"),
			new ListaItem("68867", "Vetas", "Vetas"),
			new ListaItem("68872", "Villanueva", "Villanueva"),
			new ListaItem("68895", "Zapatoca", "Zapatoca"),
			new ListaItem("70001", "Sincelejo", "Sincelejo"),
			new ListaItem("70110", "Buenavista", "Buenavista"),
			new ListaItem("70124", "Caimito", "Caimito"),
			new ListaItem("70204", "Colosó", "Colosó"),
			new ListaItem("70215", "Corozal", "Corozal"),
			new ListaItem("70221", "Coveñas", "Coveñas"),
			new ListaItem("70230", "Chalán", "Chalán"),
			new ListaItem("70233", "El Roble ", "El Roble "),
			new ListaItem("70235", "Galeras", "Galeras"),
			new ListaItem("70265", "Guaranda", "Guaranda"),
			new ListaItem("70400", "La Unión ", "La Unión "),
			new ListaItem("70418", "Los Palmitos ", "Los Palmitos "),
			new ListaItem("70429", "Majagual", "Majagual"),
			new ListaItem("70473", "Morroa", "Morroa"),
			new ListaItem("70508", "Ovejas", "Ovejas"),
			new ListaItem("70523", "Palmito", "Palmito"),
			new ListaItem("70670", "Sampués", "Sampués"),
			new ListaItem("70678", "San Benito Abad", "San Benito Abad"),
			new ListaItem("70702", "San Juan De Betulia", "San Juan De Betulia"),
			new ListaItem("70708", "San Marcos ", "San Marcos "),
			new ListaItem("70713", "San Onofre ", "San Onofre "),
			new ListaItem("70717", "San Pedro ", "San Pedro "),
			new ListaItem("70742", "San Luis De Sincé", "San Luis De Sincé"),
			new ListaItem("70771", "Sucre", "Sucre"),
			new ListaItem("70820", "Santiago De Tolú", "Santiago De Tolú"),
			new ListaItem("70823", "Tolú Viejo ", "Tolú Viejo "),
			new ListaItem("73001", "Ibagué", "Ibagué"),
			new ListaItem("73024", "Alpujarra", "Alpujarra"),
			new ListaItem("73026", "Alvarado", "Alvarado"),
			new ListaItem("73030", "Ambalema", "Ambalema"),
			new ListaItem("73043", "Anzoátegui", "Anzoátegui"),
			new ListaItem("73055", "Armero", "Armero"),
			new ListaItem("73067", "Ataco", "Ataco"),
			new ListaItem("73124", "Cajamarca", "Cajamarca"),
			new ListaItem("73148", "Carmen De Apicalá", "Carmen De Apicalá"),
			new ListaItem("73152", "Casabianca", "Casabianca"),
			new ListaItem("73168", "Chaparral", "Chaparral"),
			new ListaItem("73200", "Coello", "Coello"),
			new ListaItem("73217", "Coyaima", "Coyaima"),
			new ListaItem("73226", "Cunday", "Cunday"),
			new ListaItem("73236", "Dolores", "Dolores"),
			new ListaItem("73268", "Espinal", "Espinal"),
			new ListaItem("73270", "Falan", "Falan"),
			new ListaItem("73275", "Flandes", "Flandes"),
			new ListaItem("73283", "Fresno", "Fresno"),
			new ListaItem("73319", "Guamo", "Guamo"),
			new ListaItem("73347", "Herveo", "Herveo"),
			new ListaItem("73349", "Honda", "Honda"),
			new ListaItem("73352", "Icononzo", "Icononzo"),
			new ListaItem("73408", "Lérida", "Lérida"),
			new ListaItem("73411", "Líbano", "Líbano"),
			new ListaItem("73443", "San Sebastián De Mariquita", "San Sebastián De Mariquita"),
			new ListaItem("73449", "Melgar", "Melgar"),
			new ListaItem("73461", "Murillo", "Murillo"),
			new ListaItem("73483", "Natagaima", "Natagaima"),
			new ListaItem("73504", "Ortega", "Ortega"),
			new ListaItem("73520", "Palocabildo", "Palocabildo"),
			new ListaItem("73547", "Piedras", "Piedras"),
			new ListaItem("73555", "Planadas", "Planadas"),
			new ListaItem("73563", "Prado", "Prado"),
			new ListaItem("73585", "Purificación", "Purificación"),
			new ListaItem("73616", "Rioblanco", "Rioblanco"),
			new ListaItem("73622", "Roncesvalles", "Roncesvalles"),
			new ListaItem("73624", "Rovira", "Rovira"),
			new ListaItem("73671", "Saldaña", "Saldaña"),
			new ListaItem("73675", "San Antonio ", "San Antonio "),
			new ListaItem("73678", "San Luis ", "San Luis "),
			new ListaItem("73686", "Santa Isabel ", "Santa Isabel "),
			new ListaItem("73770", "Suárez", "Suárez"),
			new ListaItem("73854", "Valle De San Juan", "Valle De San Juan"),
			new ListaItem("73861", "Venadillo", "Venadillo"),
			new ListaItem("73870", "Villahermosa", "Villahermosa"),
			new ListaItem("73873", "Villarrica", "Villarrica"),
			new ListaItem("76001", "Cali", "Cali"),
			new ListaItem("76020", "Alcalá", "Alcalá"),
			new ListaItem("76036", "Andalucía", "Andalucía"),
			new ListaItem("76041", "Ansermanuevo", "Ansermanuevo"),
			new ListaItem("76054", "Argelia", "Argelia"),
			new ListaItem("76100", "Bolívar", "Bolívar"),
			new ListaItem("76109", "Buenaventura", "Buenaventura"),
			new ListaItem("76111", "Guadalajara De Buga", "Guadalajara De Buga"),
			new ListaItem("76113", "Bugalagrande", "Bugalagrande"),
			new ListaItem("76122", "Caicedonia", "Caicedonia"),
			new ListaItem("76126", "Calima", "Calima"),
			new ListaItem("76130", "Candelaria", "Candelaria"),
			new ListaItem("76147", "Cartago", "Cartago"),
			new ListaItem("76233", "Dagua", "Dagua"),
			new ListaItem("76243", "El Águila ", "El Águila "),
			new ListaItem("76246", "El Cairo ", "El Cairo "),
			new ListaItem("76248", "El Cerrito ", "El Cerrito "),
			new ListaItem("76250", "El Dovio ", "El Dovio "),
			new ListaItem("76275", "Florida", "Florida"),
			new ListaItem("76306", "Ginebra", "Ginebra"),
			new ListaItem("76318", "Guacarí", "Guacarí"),
			new ListaItem("76364", "Jamundí", "Jamundí"),
			new ListaItem("76377", "La Cumbre ", "La Cumbre "),
			new ListaItem("76400", "La Unión ", "La Unión "),
			new ListaItem("76403", "La Victoria ", "La Victoria "),
			new ListaItem("76497", "Obando", "Obando"),
			new ListaItem("76520", "Palmira", "Palmira"),
			new ListaItem("76563", "Pradera", "Pradera"),
			new ListaItem("76606", "Restrepo", "Restrepo"),
			new ListaItem("76616", "Riofrío", "Riofrío"),
			new ListaItem("76622", "Roldanillo", "Roldanillo"),
			new ListaItem("76670", "San Pedro ", "San Pedro "),
			new ListaItem("76736", "Sevilla", "Sevilla"),
			new ListaItem("76823", "Toro", "Toro"),
			new ListaItem("76828", "Trujillo", "Trujillo"),
			new ListaItem("76834", "Tuluá", "Tuluá"),
			new ListaItem("76845", "Ulloa", "Ulloa"),
			new ListaItem("76863", "Versalles", "Versalles"),
			new ListaItem("76869", "Vijes", "Vijes"),
			new ListaItem("76890", "Yotoco", "Yotoco"),
			new ListaItem("76892", "Yumbo", "Yumbo"),
			new ListaItem("76895", "Zarzal", "Zarzal"),
			new ListaItem("81001", "Arauca", "Arauca"),
			new ListaItem("81065", "Arauquita", "Arauquita"),
			new ListaItem("81220", "Cravo Norte ", "Cravo Norte "),
			new ListaItem("81300", "Fortul", "Fortul"),
			new ListaItem("81591", "Puerto Rondón ", "Puerto Rondón "),
			new ListaItem("81736", "Saravena", "Saravena"),
			new ListaItem("81794", "Tame", "Tame"),
			new ListaItem("85001", "Yopal", "Yopal"),
			new ListaItem("85010", "Aguazul", "Aguazul"),
			new ListaItem("85015", "Chámeza", "Chámeza"),
			new ListaItem("85125", "Hato Corozal ", "Hato Corozal "),
			new ListaItem("85136", "La Salina ", "La Salina "),
			new ListaItem("85139", "Maní", "Maní"),
			new ListaItem("85162", "Monterrey", "Monterrey"),
			new ListaItem("85225", "Nunchía", "Nunchía"),
			new ListaItem("85230", "Orocué", "Orocué"),
			new ListaItem("85250", "Paz De Ariporo", "Paz De Ariporo"),
			new ListaItem("85263", "Pore", "Pore"),
			new ListaItem("85279", "Recetor", "Recetor"),
			new ListaItem("85300", "Sabanalarga", "Sabanalarga"),
			new ListaItem("85315", "Sácama", "Sácama"),
			new ListaItem("85325", "San Luis De Palenque", "San Luis De Palenque"),
			new ListaItem("85400", "Támara", "Támara"),
			new ListaItem("85410", "Tauramena", "Tauramena"),
			new ListaItem("85430", "Trinidad", "Trinidad"),
			new ListaItem("85440", "Villanueva", "Villanueva"),
			new ListaItem("86001", "Mocoa", "Mocoa"),
			new ListaItem("86219", "Colón", "Colón"),
			new ListaItem("86320", "Orito", "Orito"),
			new ListaItem("86568", "Puerto Asís ", "Puerto Asís "),
			new ListaItem("86569", "Puerto Caicedo ", "Puerto Caicedo "),
			new ListaItem("86571", "Puerto Guzmán ", "Puerto Guzmán "),
			new ListaItem("86573", "Puerto Leguízamo ", "Puerto Leguízamo "),
			new ListaItem("86749", "Sibundoy", "Sibundoy"),
			new ListaItem("86755", "San Francisco ", "San Francisco "),
			new ListaItem("86757", "San Miguel ", "San Miguel "),
			new ListaItem("86760", "Santiago", "Santiago"),
			new ListaItem("86865", "Valle Del Guamuez", "Valle Del Guamuez"),
			new ListaItem("86885", "Villagarzón", "Villagarzón"),
			new ListaItem("88001", "San Andrés ", "San Andrés "),
			new ListaItem("88564", "Providencia", "Providencia"),
			new ListaItem("91001", "Leticia", "Leticia"),
			new ListaItem("91263", "El Encanto ", "El Encanto "),
			new ListaItem("91405", "La Chorrera ", "La Chorrera "),
			new ListaItem("91407", "La Pedrera ", "La Pedrera "),
			new ListaItem("91430", "La Victoria ", "La Victoria "),
			new ListaItem("91460", "Mirití - Paraná", "Mirití - Paraná"),
			new ListaItem("91530", "Puerto Alegría ", "Puerto Alegría "),
			new ListaItem("91536", "Puerto Arica ", "Puerto Arica "),
			new ListaItem("91540", "Puerto Nariño ", "Puerto Nariño "),
			new ListaItem("91669", "Puerto Santander ", "Puerto Santander "),
			new ListaItem("91798", "Tarapacá", "Tarapacá"),
			new ListaItem("94001", "Inírida", "Inírida"),
			new ListaItem("94343", "Barranco Minas ", "Barranco Minas "),
			new ListaItem("94663", "Mapiripana", "Mapiripana"),
			new ListaItem("94883", "San Felipe ", "San Felipe "),
			new ListaItem("94884", "Puerto Colombia ", "Puerto Colombia "),
			new ListaItem("94885", "La Guadalupe ", "La Guadalupe "),
			new ListaItem("94886", "Cacahual", "Cacahual"),
			new ListaItem("94887", "Pana Pana ", "Pana Pana "),
			new ListaItem("94888", "Morichal", "Morichal"),
			new ListaItem("95001", "San José Del Guaviare", "San José Del Guaviare"),
			new ListaItem("95015", "Calamar", "Calamar"),
			new ListaItem("95025", "El Retorno ", "El Retorno "),
			new ListaItem("95200", "Miraflores", "Miraflores"),
			new ListaItem("97001", "Mitú", "Mitú"),
			new ListaItem("97161", "Carurú", "Carurú"),
			new ListaItem("97511", "Pacoa", "Pacoa"),
			new ListaItem("97666", "Taraira", "Taraira"),
			new ListaItem("97777", "Papunahua", "Papunahua"),
			new ListaItem("97889", "Yavaraté", "Yavaraté"),
			new ListaItem("99001", "Puerto Carreño ", "Puerto Carreño "),
			new ListaItem("99524", "La Primavera ", "La Primavera "),
			new ListaItem("99624", "Santa Rosalía ", "Santa Rosalía "),
			new ListaItem("99773", "Cumaribo", "Cumaribo"),
			new ListaItem("27086", "Belén de Bajirá", "Belén de Bajirá"),

		};

	}
}
