using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HGInetUBLv2_1.DianListas
{
	public class ListaPaises
	{
		public string ShortName = "Paises";
		public string LongName = "Paises";
		public string Version = "1";
		public string CanonicalUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:Paises-2.1";
		public string CanonicalVersionUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:Paises-2.1";
		public string LocationUri = "http://dian.gov.co/ubl/os-ubl-2.0/cl/gc/default/Paises-2.1.gc";
		public string AgencyName = "DIAN (Dirección de Impuestos y Aduanas Nacionales)";
		public string AgencyIdentifier = "195";

		public List<ListaItem> Items = new List<ListaItem>()
		{
			new ListaItem("AF", "Afganistán", "Afganistán"),
new ListaItem("AX", "Åland", "Åland"),
new ListaItem("AL", "Albania", "Albania"),
new ListaItem("DE", "Alemania", "Alemania"),
new ListaItem("AD", "Andorra", "Andorra"),
new ListaItem("AO", "Angola", "Angola"),
new ListaItem("AI", "Anguila", "Anguila"),
new ListaItem("AQ", "Antártida", "Antártida"),
new ListaItem("AG", "Antigua y Barbuda", "Antigua y Barbuda"),
new ListaItem("SA", "Arabia Saudita", "Arabia Saudita"),
new ListaItem("DZ", "Argelia", "Argelia"),
new ListaItem("AR", "Argentina", "Argentina"),
new ListaItem("AM", "Armenia", "Armenia"),
new ListaItem("AW", "Aruba", "Aruba"),
new ListaItem("AU", "Australia", "Australia"),
new ListaItem("AT", "Austria", "Austria"),
new ListaItem("AZ", "Azerbaiyán", "Azerbaiyán"),
new ListaItem("BS", "Bahamas", "Bahamas"),
new ListaItem("BD", "Bangladés", "Bangladés"),
new ListaItem("BB", "Barbados", "Barbados"),
new ListaItem("BH", "Baréin", "Baréin"),
new ListaItem("BE", "Bélgica", "Bélgica"),
new ListaItem("BZ", "Belice", "Belice"),
new ListaItem("BJ", "Benín", "Benín"),
new ListaItem("BM", "Bermudas", "Bermudas"),
new ListaItem("BY", "Bielorrusia", "Bielorrusia"),
new ListaItem("BO", "Bolivia", "Bolivia"),
new ListaItem("BQ", "Bonaire, San Eustaquio y Saba", "Bonaire, San Eustaquio y Saba"),
new ListaItem("BA", "Bosnia y Herzegovina", "Bosnia y Herzegovina"),
new ListaItem("BW", "Botsuana", "Botsuana"),
new ListaItem("BR", "Brasil", "Brasil"),
new ListaItem("BN", "Brunéi", "Brunéi"),
new ListaItem("BG", "Bulgaria", "Bulgaria"),
new ListaItem("BF", "Burkina Faso", "Burkina Faso"),
new ListaItem("BI", "Burundi", "Burundi"),
new ListaItem("BT", "Bután", "Bután"),
new ListaItem("CV", "Cabo Verde", "Cabo Verde"),
new ListaItem("KH", "Camboya", "Camboya"),
new ListaItem("CM", "Camerún", "Camerún"),
new ListaItem("CA", "Canadá", "Canadá"),
new ListaItem("QA", "Catar", "Catar"),
new ListaItem("TD", "Chad", "Chad"),
new ListaItem("CL", "Chile", "Chile"),
new ListaItem("CN", "China", "China"),
new ListaItem("CY", "Chipre", "Chipre"),
new ListaItem("CO", "Colombia", "Colombia"),
new ListaItem("KM", "Comoras", "Comoras"),
new ListaItem("KP", "Corea del Norte", "Corea del Norte"),
new ListaItem("KR", "Corea del Sur", "Corea del Sur"),
new ListaItem("CI", "Costa de Marfil", "Costa de Marfil"),
new ListaItem("CR", "Costa Rica", "Costa Rica"),
new ListaItem("HR", "Croacia", "Croacia"),
new ListaItem("CU", "Cuba", "Cuba"),
new ListaItem("CW", "Curazao", "Curazao"),
new ListaItem("DK", "Dinamarca", "Dinamarca"),
new ListaItem("DM", "Dominica", "Dominica"),
new ListaItem("EC", "Ecuador", "Ecuador"),
new ListaItem("EG", "Egipto", "Egipto"),
new ListaItem("SV", "El Salvador", "El Salvador"),
new ListaItem("AE", "Emiratos Árabes Unidos", "Emiratos Árabes Unidos"),
new ListaItem("ER", "Eritrea", "Eritrea"),
new ListaItem("SK", "Eslovaquia", "Eslovaquia"),
new ListaItem("SI", "Eslovenia", "Eslovenia"),
new ListaItem("ES", "España", "España"),
new ListaItem("US", "Estados Unidos", "Estados Unidos"),
new ListaItem("EE", "Estonia", "Estonia"),
new ListaItem("ET", "Etiopía", "Etiopía"),
new ListaItem("PH", "Filipinas", "Filipinas"),
new ListaItem("FI", "Finlandia", "Finlandia"),
new ListaItem("FJ", "Fiyi", "Fiyi"),
new ListaItem("FR", "Francia", "Francia"),
new ListaItem("GA", "Gabón", "Gabón"),
new ListaItem("GM", "Gambia", "Gambia"),
new ListaItem("GE", "Georgia", "Georgia"),
new ListaItem("GH", "Ghana", "Ghana"),
new ListaItem("GI", "Gibraltar", "Gibraltar"),
new ListaItem("GD", "Granada", "Granada"),
new ListaItem("GR", "Grecia", "Grecia"),
new ListaItem("GL", "Groenlandia", "Groenlandia"),
new ListaItem("GP", "Guadalupe", "Guadalupe"),
new ListaItem("GU", "Guam", "Guam"),
new ListaItem("GT", "Guatemala", "Guatemala"),
new ListaItem("GF", "Guayana Francesa", "Guayana Francesa"),
new ListaItem("GG", "Guernsey", "Guernsey"),
new ListaItem("GN", "Guinea", "Guinea"),
new ListaItem("GW", "Guinea-Bisáu", "Guinea-Bisáu"),
new ListaItem("GQ", "Guinea Ecuatorial", "Guinea Ecuatorial"),
new ListaItem("GY", "Guyana", "Guyana"),
new ListaItem("HT", "Haití", "Haití"),
new ListaItem("HN", "Honduras", "Honduras"),
new ListaItem("HK", "Hong Kong", "Hong Kong"),
new ListaItem("HU", "Hungría", "Hungría"),
new ListaItem("IN", "India", "India"),
new ListaItem("ID", "Indonesia", "Indonesia"),
new ListaItem("IQ", "Irak", "Irak"),
new ListaItem("IR", "Irán", "Irán"),
new ListaItem("IE", "Irlanda", "Irlanda"),
new ListaItem("BV", "Isla Bouvet", "Isla Bouvet"),
new ListaItem("IM", "Isla de Man", "Isla de Man"),
new ListaItem("CX", "Isla de Navidad", "Isla de Navidad"),
new ListaItem("IS", "Islandia", "Islandia"),
new ListaItem("KY", "Islas Caimán", "Islas Caimán"),
new ListaItem("CC", "Islas Cocos", "Islas Cocos"),
new ListaItem("CK", "Islas Cook", "Islas Cook"),
new ListaItem("FO", "Islas Feroe", "Islas Feroe"),
new ListaItem("GS", "Islas Georgias del Sur y Sandwich del Sur", "Islas Georgias del Sur y Sandwich del Sur"),
new ListaItem("HM", "Islas Heard y McDonald", "Islas Heard y McDonald"),
new ListaItem("FK", "Islas Malvinas", "Islas Malvinas"),
new ListaItem("MP", "Islas Marianas del Norte", "Islas Marianas del Norte"),
new ListaItem("MH", "Islas Marshall", "Islas Marshall"),
new ListaItem("PN", "Islas Pitcairn", "Islas Pitcairn"),
new ListaItem("SB", "Islas Salomón", "Islas Salomón"),
new ListaItem("TC", "Islas Turcas y Caicos", "Islas Turcas y Caicos"),
new ListaItem("UM", "Islas ultramarinas de Estados Unidos", "Islas ultramarinas de Estados Unidos"),
new ListaItem("VG", "Islas Vírgenes Británicas", "Islas Vírgenes Británicas"),
new ListaItem("VI", "Islas Vírgenes de los Estados Unidos", "Islas Vírgenes de los Estados Unidos"),
new ListaItem("IL", "Israel", "Israel"),
new ListaItem("IT", "Italia", "Italia"),
new ListaItem("JM", "Jamaica", "Jamaica"),
new ListaItem("JP", "Japón", "Japón"),
new ListaItem("JE", "Jersey", "Jersey"),
new ListaItem("JO", "Jordania", "Jordania"),
new ListaItem("KZ", "Kazajistán", "Kazajistán"),
new ListaItem("KE", "Kenia", "Kenia"),
new ListaItem("KG", "Kirguistán", "Kirguistán"),
new ListaItem("KI", "Kiribati", "Kiribati"),
new ListaItem("KW", "Kuwait", "Kuwait"),
new ListaItem("LA", "Laos", "Laos"),
new ListaItem("LS", "Lesoto", "Lesoto"),
new ListaItem("LV", "Letonia", "Letonia"),
new ListaItem("LB", "Líbano", "Líbano"),
new ListaItem("LR", "Liberia", "Liberia"),
new ListaItem("LY", "Libia", "Libia"),
new ListaItem("LI", "Liechtenstein", "Liechtenstein"),
new ListaItem("LT", "Lituania", "Lituania"),
new ListaItem("LU", "Luxemburgo", "Luxemburgo"),
new ListaItem("MO", "Macao", "Macao"),
new ListaItem("MK", "Macedonia", "Macedonia"),
new ListaItem("MG", "Madagascar", "Madagascar"),
new ListaItem("MY", "Malasia", "Malasia"),
new ListaItem("MW", "Malaui", "Malaui"),
new ListaItem("MV", "Maldivas", "Maldivas"),
new ListaItem("ML", "Malí", "Malí"),
new ListaItem("MT", "Malta", "Malta"),
new ListaItem("MA", "Marruecos", "Marruecos"),
new ListaItem("MQ", "Martinica", "Martinica"),
new ListaItem("MU", "Mauricio", "Mauricio"),
new ListaItem("MR", "Mauritania", "Mauritania"),
new ListaItem("YT", "Mayotte", "Mayotte"),
new ListaItem("MX", "México", "México"),
new ListaItem("FM", "Micronesia", "Micronesia"),
new ListaItem("MD", "Moldavia", "Moldavia"),
new ListaItem("MC", "Mónaco", "Mónaco"),
new ListaItem("MN", "Mongolia", "Mongolia"),
new ListaItem("ME", "Montenegro", "Montenegro"),
new ListaItem("MS", "Montserrat", "Montserrat"),
new ListaItem("MZ", "Mozambique", "Mozambique"),
new ListaItem("MM", "Myanmar", "Myanmar"),
new ListaItem("NA", "Namibia", "Namibia"),
new ListaItem("NR", "Nauru", "Nauru"),
new ListaItem("NP", "Nepal", "Nepal"),
new ListaItem("NI", "Nicaragua", "Nicaragua"),
new ListaItem("NE", "Níger", "Níger"),
new ListaItem("NG", "Nigeria", "Nigeria"),
new ListaItem("UN", "Niue", "Niue"),
new ListaItem("NF", "Norfolk", "Norfolk"),
new ListaItem("NO", "Noruega", "Noruega"),
new ListaItem("NC", "Nueva Caledonia", "Nueva Caledonia"),
new ListaItem("NZ", "Nueva Zelanda", "Nueva Zelanda"),
new ListaItem("OM", "Omán", "Omán"),
new ListaItem("NL", "Países Bajos", "Países Bajos"),
new ListaItem("PK", "Pakistán", "Pakistán"),
new ListaItem("PW", "Palaos", "Palaos"),
new ListaItem("PS", "Palestina", "Palestina"),
new ListaItem("PA", "Panamá", "Panamá"),
new ListaItem("PG", "Papúa Nueva Guinea", "Papúa Nueva Guinea"),
new ListaItem("PY", "Paraguay", "Paraguay"),
new ListaItem("PE", "Perú", "Perú"),
new ListaItem("PF", "Polinesia Francesa", "Polinesia Francesa"),
new ListaItem("PL", "Polonia", "Polonia"),
new ListaItem("PT", "Portugal", "Portugal"),
new ListaItem("PR", "Puerto Rico", "Puerto Rico"),
new ListaItem("GB", "Reino Unido", "Reino Unido"),
new ListaItem("EH", "República Árabe Saharaui Democrática", "República Árabe Saharaui Democrática"),
new ListaItem("CF", "República Centroafricana", "República Centroafricana"),
new ListaItem("CZ", "República Checa", "República Checa"),
new ListaItem("CG", "República del Congo", "República del Congo"),
new ListaItem("CD", "República Democrática del Congo", "República Democrática del Congo"),
new ListaItem("DO", "República Dominicana", "República Dominicana"),
new ListaItem("RE", "Reunión", "Reunión"),
new ListaItem("RW", "Ruanda", "Ruanda"),
new ListaItem("RO", "Rumania", "Rumania"),
new ListaItem("RU", "Rusia", "Rusia"),
new ListaItem("WS", "Samoa", "Samoa"),
new ListaItem("AS", "Samoa Americana", "Samoa Americana"),
new ListaItem("BL", "San Bartolomé", "San Bartolomé"),
new ListaItem("KN", "San Cristóbal y Nieves", "San Cristóbal y Nieves"),
new ListaItem("SM", "San Marino", "San Marino"),
new ListaItem("MF", "San Martín", "San Martín"),
new ListaItem("PM", "San Pedro y Miquelón", "San Pedro y Miquelón"),
new ListaItem("VC", "San Vicente y las Granadinas", "San Vicente y las Granadinas"),
new ListaItem("SH", "Santa Elena, Ascensión y Tristán de Acuña", "Santa Elena, Ascensión y Tristán de Acuña"),
new ListaItem("LC", "Santa Lucía", "Santa Lucía"),
new ListaItem("ST", "Santo Tomé y Príncipe", "Santo Tomé y Príncipe"),
new ListaItem("SN", "Senegal", "Senegal"),
new ListaItem("RS", "Serbia", "Serbia"),
new ListaItem("SC", "Seychelles", "Seychelles"),
new ListaItem("SL", "Sierra Leona", "Sierra Leona"),
new ListaItem("SG", "Singapur", "Singapur"),
new ListaItem("SX", "Sint Maarten", "Sint Maarten"),
new ListaItem("SY", "Siria", "Siria"),
new ListaItem("SO", "Somalia", "Somalia"),
new ListaItem("LK", "Sri Lanka", "Sri Lanka"),
new ListaItem("SZ", "Suazilandia", "Suazilandia"),
new ListaItem("ZA", "Sudáfrica", "Sudáfrica"),
new ListaItem("SD", "Sudán", "Sudán"),
new ListaItem("SS", "Sudán del Sur", "Sudán del Sur"),
new ListaItem("SI", "Suecia", "Suecia"),
new ListaItem("CH", "Suiza", "Suiza"),
new ListaItem("SR", "Surinam", "Surinam"),
new ListaItem("SJ", "Svalbard y Jan Mayen", "Svalbard y Jan Mayen"),
new ListaItem("TH", "Tailandia", "Tailandia"),
new ListaItem("TW", "Taiwán (República de China)", "Taiwán (República de China)"),
new ListaItem("TZ", "Tanzania", "Tanzania"),
new ListaItem("TJ", "Tayikistán", "Tayikistán"),
new ListaItem("IO", "Territorio Británico del Océano Índico", "Territorio Británico del Océano Índico"),
new ListaItem("TF", "Tierras Australes y Antárticas Francesas", "Tierras Australes y Antárticas Francesas"),
new ListaItem("TL", "Timor Oriental", "Timor Oriental"),
new ListaItem("TG", "Togo", "Togo"),
new ListaItem("TK", "Tokelau", "Tokelau"),
new ListaItem("TO", "Tonga", "Tonga"),
new ListaItem("TT", "Trinidad y Tobago", "Trinidad y Tobago"),
new ListaItem("TN", "Túnez", "Túnez"),
new ListaItem("TM", "Turkmenistán", "Turkmenistán"),
new ListaItem("TR", "Turquía", "Turquía"),
new ListaItem("TV", "Tuvalu", "Tuvalu"),
new ListaItem("UA", "Ucrania", "Ucrania"),
new ListaItem("UG", "Uganda", "Uganda"),
new ListaItem("UY", "Uruguay", "Uruguay"),
new ListaItem("UZ", "Uzbekistán", "Uzbekistán"),
new ListaItem("VU", "Vanuatu", "Vanuatu"),
new ListaItem("VA", "Vaticano, Ciudad del", "Vaticano, Ciudad del"),
new ListaItem("VE", "Venezuela", "Venezuela"),
new ListaItem("VN", "Vietnam", "Vietnam"),
new ListaItem("WF", "Wallis y Futuna", "Wallis y Futuna"),
new ListaItem("YE", "Yemen", "Yemen"),
new ListaItem("DJ", "Yibuti", "Yibuti"),
new ListaItem("ZM", "Zambia", "Zambia"),
new ListaItem("ZW", "Zimbabue", "Zimbabue"),

		};

	}
}
