using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HGInetUBLv2_1.DianListas
{
	public class ListaTipoMoneda
	{
		public string ShortName = "TipoMoneda";
		public string LongName = "Moneda";
		public string Version = "1";
		public string CanonicalUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:TipoMoneda-2.1";
		public string CanonicalVersionUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:TipoMoneda-2.1";
		public string LocationUri = "http://dian.gov.co/ubl/os-ubl-2.0/cl/gc/default/TipoMoneda-2.1.gc";
		public string AgencyName = "DIAN (Dirección de Impuestos y Aduanas Nacionales)";
		public string AgencyIdentifier = "195";

		public List<ListaItem> Items = new List<ListaItem>()
		{
			new ListaItem("AED", "Dírham de los Emiratos Árabes Unidos", "Dírham de los Emiratos Árabes Unidos"),
			new ListaItem("AFN", "Afgani", "Afgani"),
			new ListaItem("ALL", "Lek", "Lek"),
			new ListaItem("AMD", "Dram armenio", "Dram armenio"),
			new ListaItem("ANG", "Florín antillano neerlandés", "Florín antillano neerlandés"),
			new ListaItem("AOA", "Kwanza", "Kwanza"),
			new ListaItem("ARS", "Peso argentino", "Peso argentino"),
			new ListaItem("AUD", "Dólar australiano", "Dólar australiano"),
			new ListaItem("AWG", "Florín arubeño", "Florín arubeño"),
			new ListaItem("AZN", "Manat azerbaiyano", "Manat azerbaiyano"),
			new ListaItem("BAM", "Marco convertible", "Marco convertible"),
			new ListaItem("BBD", "Dólar de Barbados", "Dólar de Barbados"),
			new ListaItem("BDT", "Taka", "Taka"),
			new ListaItem("BGN", "Lev búlgaro", "Lev búlgaro"),
			new ListaItem("BHD", "Dinar bareiní", "Dinar bareiní"),
			new ListaItem("BIF", "Franco de Burundi", "Franco de Burundi"),
			new ListaItem("BMD", "Dólar bermudeño", "Dólar bermudeño"),
			new ListaItem("BND", "Dólar de Brunéi", "Dólar de Brunéi"),
			new ListaItem("BOB", "Boliviano", "Boliviano"),
			new ListaItem("BOV", "MVDOL", "MVDOL"),
			new ListaItem("BRL", "Real brasileño", "Real brasileño"),
			new ListaItem("BSD", "Dólar bahameño", "Dólar bahameño"),
			new ListaItem("BTN", "Ngultrum", "Ngultrum"),
			new ListaItem("BWP", "Pula", "Pula"),
			new ListaItem("BYR", "Rublo bielorruso", "Rublo bielorruso"),
			new ListaItem("BZD", "Dólar beliceño", "Dólar beliceño"),
			new ListaItem("CAD", "Dólar canadiense", "Dólar canadiense"),
			new ListaItem("CDF", "Franco congoleño", "Franco congoleño"),
			new ListaItem("CHE", "Euro WIR", "Euro WIR"),
			new ListaItem("CHF", "Franco suizo", "Franco suizo"),
			new ListaItem("CHW", "Franco WIR", "Franco WIR"),
			new ListaItem("CLF", "Unidad de fomento", "Unidad de fomento"),
			new ListaItem("CLP", "Peso chileno", "Peso chileno"),
			new ListaItem("CNY", "Yuan chino", "Yuan chino"),
			new ListaItem("COP", "Peso colombiano", "Peso colombiano"),
			new ListaItem("COU", "Unidad de valor real", "Unidad de valor real"),
			new ListaItem("CRC", "Colón costarricense", "Colón costarricense"),
			new ListaItem("CUC", "Peso convertible", "Peso convertible"),
			new ListaItem("CUP", "Peso cubano", "Peso cubano"),
			new ListaItem("CVE", "Escudo caboverdiano", "Escudo caboverdiano"),
			new ListaItem("CZK", "Corona checa", "Corona checa"),
			new ListaItem("DJF", "Franco yibutiano", "Franco yibutiano"),
			new ListaItem("DKK", "Corona danesa", "Corona danesa"),
			new ListaItem("DOP", "Peso dominicano", "Peso dominicano"),
			new ListaItem("DZD", "Dinar argelino", "Dinar argelino"),
			new ListaItem("EGP", "Libra egipcia", "Libra egipcia"),
			new ListaItem("ERN", "Nakfa", "Nakfa"),
			new ListaItem("ETB", "Birr etíope", "Birr etíope"),
			new ListaItem("EUR", "Euro", "Euro"),
			new ListaItem("FJD", "Dólar fiyiano", "Dólar fiyiano"),
			new ListaItem("FKP", "Libra malvinense", "Libra malvinense"),
			new ListaItem("GBP", "Libra esterlina", "Libra esterlina"),
			new ListaItem("GEL", "Lari", "Lari"),
			new ListaItem("GHS", "Cedi ghanés", "Cedi ghanés"),
			new ListaItem("GIP", "Libra de Gibraltar", "Libra de Gibraltar"),
			new ListaItem("GMD", "Dalasi", "Dalasi"),
			new ListaItem("GNF", "Franco guineano", "Franco guineano"),
			new ListaItem("GTQ", "Quetzal", "Quetzal"),
			new ListaItem("GYD", "Dólar guyanés", "Dólar guyanés"),
			new ListaItem("HKD", "Dólar de Hong Kong", "Dólar de Hong Kong"),
			new ListaItem("HNL", "Lempira", "Lempira"),
			new ListaItem("HRK", "Kuna", "Kuna"),
			new ListaItem("HTG", "Gourde", "Gourde"),
			new ListaItem("HUF", "Forinto", "Forinto"),
			new ListaItem("IDR", "Rupia indonesia", "Rupia indonesia"),
			new ListaItem("ILS", "Nuevo shéquel israelí", "Nuevo shéquel israelí"),
			new ListaItem("INR", "Rupia india", "Rupia india"),
			new ListaItem("IQD", "Dinar iraquí", "Dinar iraquí"),
			new ListaItem("IRR", "Rial iraní", "Rial iraní"),
			new ListaItem("ISK", "Corona islandesa", "Corona islandesa"),
			new ListaItem("JMD", "Dólar jamaiquino", "Dólar jamaiquino"),
			new ListaItem("JOD", "Dinar jordano", "Dinar jordano"),
			new ListaItem("JPY", "Yen", "Yen"),
			new ListaItem("KES", "Chelín keniano", "Chelín keniano"),
			new ListaItem("KGS", "Som", "Som"),
			new ListaItem("KHR", "Riel", "Riel"),
			new ListaItem("KMF", "Franco comorense", "Franco comorense"),
			new ListaItem("KPW", "Won norcoreano", "Won norcoreano"),
			new ListaItem("KRW", "Won", "Won"),
			new ListaItem("KWD", "Dinar kuwaití", "Dinar kuwaití"),
			new ListaItem("KYD", "Dólar de las Islas Caimán", "Dólar de las Islas Caimán"),
			new ListaItem("KZT", "Tenge", "Tenge"),
			new ListaItem("LAK", "Kip", "Kip"),
			new ListaItem("LBP", "Libra libanesa", "Libra libanesa"),
			new ListaItem("LKR", "Rupia de Sri Lanka", "Rupia de Sri Lanka"),
			new ListaItem("LRD", "Dólar liberiano", "Dólar liberiano"),
			new ListaItem("LSL", "Loti", "Loti"),
			new ListaItem("LYD", "Dinar libio", "Dinar libio"),
			new ListaItem("MAD", "Dírham marroquí", "Dírham marroquí"),
			new ListaItem("MDL", "Leu moldavo", "Leu moldavo"),
			new ListaItem("MGA", "Ariary malgache", "Ariary malgache"),
			new ListaItem("MKD", "Denar", "Denar"),
			new ListaItem("MMK", "Kyat", "Kyat"),
			new ListaItem("MNT", "Tugrik", "Tugrik"),
			new ListaItem("MOP", "Pataca", "Pataca"),
			new ListaItem("MRO", "Uguiya", "Uguiya"),
			new ListaItem("MUR", "Rupia de Mauricio", "Rupia de Mauricio"),
			new ListaItem("MVR", "Rufiyaa", "Rufiyaa"),
			new ListaItem("MWK", "Kwacha", "Kwacha"),
			new ListaItem("MXN", "Peso mexicano", "Peso mexicano"),
			new ListaItem("MXV", "Unidad de Inversión (UDI) mexicana", "Unidad de Inversión (UDI) mexicana"),
			new ListaItem("MYR", "Ringgit malayo", "Ringgit malayo"),
			new ListaItem("MZN", "Metical mozambiqueño", "Metical mozambiqueño"),
			new ListaItem("NAD", "Dólar namibio", "Dólar namibio"),
			new ListaItem("NGN", "Naira", "Naira"),
			new ListaItem("NIO", "Córdoba", "Córdoba"),
			new ListaItem("NOK", "Corona noruega", "Corona noruega"),
			new ListaItem("NPR", "Rupia nepalí", "Rupia nepalí"),
			new ListaItem("NZD", "Dólar neozelandés", "Dólar neozelandés"),
			new ListaItem("OMR", "Rial omaní", "Rial omaní"),
			new ListaItem("PAB", "Balboa", "Balboa"),
			new ListaItem("PEN", "Sol", "Sol"),
			new ListaItem("PGK", "Kina", "Kina"),
			new ListaItem("PHP", "Peso filipino", "Peso filipino"),
			new ListaItem("PKR", "Rupia pakistaní", "Rupia pakistaní"),
			new ListaItem("PLN", "Złoty", "Złoty"),
			new ListaItem("PYG", "Guaraní", "Guaraní"),
			new ListaItem("QAR", "Riyal qatarí", "Riyal qatarí"),
			new ListaItem("RON", "Leu rumano", "Leu rumano"),
			new ListaItem("RSD", "Dinar serbio", "Dinar serbio"),
			new ListaItem("RUB", "Rublo ruso", "Rublo ruso"),
			new ListaItem("RWF", "Franco ruandés", "Franco ruandés"),
			new ListaItem("SAR", "Riyal saudí", "Riyal saudí"),
			new ListaItem("SBD", "Dólar de las Islas Salomón", "Dólar de las Islas Salomón"),
			new ListaItem("SCR", "Rupia seychelense", "Rupia seychelense"),
			new ListaItem("SDG", "Dinar sudanés", "Dinar sudanés"),
			new ListaItem("SEK", "Corona sueca", "Corona sueca"),
			new ListaItem("SGD", "Dólar de Singapur", "Dólar de Singapur"),
			new ListaItem("SHP", "Libra de Santa Elena", "Libra de Santa Elena"),
			new ListaItem("SLL", "Leone", "Leone"),
			new ListaItem("SOS", "Chelín somalí", "Chelín somalí"),
			new ListaItem("SRD", "Dólar surinamés", "Dólar surinamés"),
			new ListaItem("SSP", "Libra sursudanesa", "Libra sursudanesa"),
			new ListaItem("STD", "Dobra", "Dobra"),
			new ListaItem("SVC", "Colon Salvadoreño", "Colon Salvadoreño"),
			new ListaItem("SYP", "Libra siria", "Libra siria"),
			new ListaItem("SZL", "Lilangeni", "Lilangeni"),
			new ListaItem("THB", "Baht", "Baht"),
			new ListaItem("TJS", "Somoni tayiko", "Somoni tayiko"),
			new ListaItem("TMT", "Manat turcomano", "Manat turcomano"),
			new ListaItem("TND", "Dinar tunecino", "Dinar tunecino"),
			new ListaItem("TOP", "Paʻanga", "Paʻanga"),
			new ListaItem("TRY", "Lira turca", "Lira turca"),
			new ListaItem("TTD", "Dólar de Trinidad y Tobago", "Dólar de Trinidad y Tobago"),
			new ListaItem("TWD", "Nuevo dólar taiwanés", "Nuevo dólar taiwanés"),
			new ListaItem("TZS", "Chelín tanzano", "Chelín tanzano"),
			new ListaItem("UAH", "Grivna", "Grivna"),
			new ListaItem("UGX", "Chelín ugandés", "Chelín ugandés"),
			new ListaItem("USD", "Dólar estadounidense", "Dólar estadounidense"),
			new ListaItem("USN", "Dólar estadounidense (Siguiente día)", "Dólar estadounidense (Siguiente día)"),
			new ListaItem("UYI", "Peso en Unidades Indexadas (Uruguay)", "Peso en Unidades Indexadas (Uruguay)"),
			new ListaItem("UYU", "Peso uruguayo", "Peso uruguayo"),
			new ListaItem("UZS", "Som uzbeko", "Som uzbeko"),
			new ListaItem("VEF", "Bolívar", "Bolívar"),
			new ListaItem("VES7", "Bolívar soberano", "Bolívar soberano"),
			new ListaItem("VND", "Dong vietnamita", "Dong vietnamita"),
			new ListaItem("VUV", "Vatu", "Vatu"),
			new ListaItem("WST", "Tala", "Tala"),
			new ListaItem("XAF", "Franco CFA de África Central", "Franco CFA de África Central"),
			new ListaItem("XAG", "Plata (una onza troy)", "Plata (una onza troy)"),
			new ListaItem("XAU", "Oro (una onza troy)", "Oro (una onza troy)"),
			new ListaItem("XBA", "Unidad compuesta europea (EURCO) (Unidad del mercado de bonos)", "Unidad compuesta europea (EURCO) (Unidad del mercado de bonos)"),
			new ListaItem("XBB", "Unidad Monetaria europea (E.M.U.-6) (Unidad del mercado de bonos)", "Unidad Monetaria europea (E.M.U.-6) (Unidad del mercado de bonos)"),
			new ListaItem("XBC", "Unidad europea de cuenta 9 (E.U.A.-9) (Unidad del mercado de bonos)", "Unidad europea de cuenta 9 (E.U.A.-9) (Unidad del mercado de bonos)"),
			new ListaItem("XBD", "Unidad europea de cuenta 17 (E.U.A.-17) (Unidad del mercado de bonos)", "Unidad europea de cuenta 17 (E.U.A.-17) (Unidad del mercado de bonos)"),
			new ListaItem("XCD", "Dólar del Caribe Oriental", "Dólar del Caribe Oriental"),
			new ListaItem("XDR", "Derechos especiales de giro", "Derechos especiales de giro"),
			new ListaItem("XOF", "Franco CFA de África Occidental", "Franco CFA de África Occidental"),
			new ListaItem("XPD", "Paladio (una onza troy)", "Paladio (una onza troy)"),
			new ListaItem("XPF", "Franco CFP", "Franco CFP"),
			new ListaItem("XPT", "Platino (una onza troy)", "Platino (una onza troy)"),
			new ListaItem("XSU", "SUCRE", "SUCRE"),
			new ListaItem("XTS", "Reservado para pruebas", "Reservado para pruebas"),
			new ListaItem("XUA", "Unidad de cuenta BAD", "Unidad de cuenta BAD"),
			new ListaItem("XXX", "Sin divisa", "Sin divisa"),
			new ListaItem("YER", "Rial yemení", "Rial yemení"),
			new ListaItem("ZAR", "Rand", "Rand"),
			new ListaItem("ZMW", "Kwacha zambiano", "Kwacha zambiano"),
			new ListaItem("ZWL", "Dólar zimbabuense", "Dólar zimbabuense"),

		};

	}
}
