using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HGInetUBLv2_1.DianListas
{
	public class ListaUnidadesMedida
	{
		public string ShortName = "UnidadesCantidad";
		public string LongName = "Unidades de Cantidad";
		public string Version = "1";
		public string CanonicalUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:UnidadesCantidad-2.1";
		public string CanonicalVersionUri = "urn:dian:names:especificacion:ubl:listacodigos:gc:UnidadesCantidad-2.1";
		public string LocationUri = "http://dian.gov.co/ubl/os-ubl-2.0/cl/gc/default/UnidadesCantidad-2.1.gc";
		public string AgencyName = "DIAN (Dirección de Impuestos y Aduanas Nacionales)";
		public string AgencyIdentifier = "195";

		public List<ListaItem> Items = new List<ListaItem>()
		{
			new ListaItem("04", "spray pequeño", "spray pequeño"),
			new ListaItem("05", "levantar", "levantar"),
			new ListaItem("08", "Lote calor", "Lote calor"),
			new ListaItem("10", "grupo", "grupo"),
			new ListaItem("11", "equipar", "equipar"),
			new ListaItem("13", "ración", "ración"),
			new ListaItem("14", "Disparo", "Disparo"),
			new ListaItem("15", "palo", "palo"),
			new ListaItem("16", "tambor de ciento quince kg", "tambor de ciento quince kg"),
			new ListaItem("17", "tambor de cien libras", "tambor de cien libras"),
			new ListaItem("18", "tambor de cincuenta y cinco galones (US)", "tambor de cincuenta y cinco galones (US)"),
			new ListaItem("19", "camión cisterna", "camión cisterna"),
			new ListaItem("20", "contenedor de veinte pies", "contenedor de veinte pies"),
			new ListaItem("21", "contenedor de cuarenta pies", "contenedor de cuarenta pies"),
			new ListaItem("22", "decilitro por gramo", "decilitro por gramo"),
			new ListaItem("23", "gramo por centímetro cúbico", "gramo por centímetro cúbico"),
			new ListaItem("24", "libra teórica", "libra teórica"),
			new ListaItem("25", "gramo por centímetro cuadrado", "gramo por centímetro cuadrado"),
			new ListaItem("26", "tonelada real", "tonelada real"),
			new ListaItem("27", "tonelada teórica", "tonelada teórica"),
			new ListaItem("28", "kilogramo por metro cuadrado", "kilogramo por metro cuadrado"),
			new ListaItem("29", "libra por mil pies cuadrados", "libra por mil pies cuadrados"),
			new ListaItem("30", "Día de potencia del caballo por tonelada métrica seca al aire.", "Día de potencia del caballo por tonelada métrica seca al aire."),
			new ListaItem("31", "coger peso", "coger peso"),
			new ListaItem("32", "kilogramo por aire seco tonelada métrica", "kilogramo por aire seco tonelada métrica"),
			new ListaItem("33", "kilopascales metros cuadrados por gramo", "kilopascales metros cuadrados por gramo"),
			new ListaItem("34", "kilopascales por milímetro", "kilopascales por milímetro"),
			new ListaItem("35", "mililitros por centímetro cuadrado segundo", "mililitros por centímetro cuadrado segundo"),
			new ListaItem("36", "pies cúbicos por minuto por pie cuadrado", "pies cúbicos por minuto por pie cuadrado"),
			new ListaItem("37", "onza por pie cuadrado", "onza por pie cuadrado"),
			new ListaItem("38", "onzas por pie cuadrado por 0,01 pulgadas", "onzas por pie cuadrado por 0,01 pulgadas"),
			new ListaItem("40", "mililitro por segundo", "mililitro por segundo"),
			new ListaItem("41", "mililitro por minuto", "mililitro por minuto"),
			new ListaItem("43", "bolsa súper a granel", "bolsa súper a granel"),
			new ListaItem("44", "bolsa a granel de quinientos kg", "bolsa a granel de quinientos kg"),
			new ListaItem("45", "bolsa a granel de trescientos kg", "bolsa a granel de trescientos kg"),
			new ListaItem("46", "bolsa a granel de cincuenta libras", "bolsa a granel de cincuenta libras"),
			new ListaItem("47", "bolsa de cincuenta libras", "bolsa de cincuenta libras"),
			new ListaItem("48", "carga de automóviles a granel", "carga de automóviles a granel"),
			new ListaItem("53", "kilogramos teóricos", "kilogramos teóricos"),
			new ListaItem("54", "tonelada teórica", "tonelada teórica"),
			new ListaItem("56", "sitas", "sitas"),
			new ListaItem("57", "malla", "malla"),
			new ListaItem("58", "kilogramo neto", "kilogramo neto"),
			new ListaItem("59", "parte por millón", "parte por millón"),
			new ListaItem("60", "porcentaje de peso", "porcentaje de peso"),
			new ListaItem("61", "parte por billón (US)", "parte por billón (US)"),
			new ListaItem("62", "porcentaje por 1000 horas", "porcentaje por 1000 horas"),
			new ListaItem("63", "tasa de fracaso en el tiempo", "tasa de fracaso en el tiempo"),
			new ListaItem("64", "libra por pulgada cuadrada, calibre", "libra por pulgada cuadrada, calibre"),
			new ListaItem("66", "Oersted", "Oersted"),
			new ListaItem("69", "prueba de escala específica", "prueba de escala específica"),
			new ListaItem("71", "voltio amperio por libra", "voltio amperio por libra"),
			new ListaItem("72", "vatio por libra", "vatio por libra"),
			new ListaItem("73", "amperio tum por centímetro", "amperio tum por centímetro"),
			new ListaItem("74", "milipascal", "milipascal"),
			new ListaItem("76", "gauss", "gauss"),
			new ListaItem("77", "mili pulgadas", "mili pulgadas"),
			new ListaItem("78", "kilogauss", "kilogauss"),
			new ListaItem("80", "libras por pulgada cuadrada absoluta", "libras por pulgada cuadrada absoluta"),
			new ListaItem("81", "Enrique", "Enrique"),
			new ListaItem("84", "kilopound por pulgada cuadrada", "kilopound por pulgada cuadrada"),
			new ListaItem("85", "fuerza libra pie", "fuerza libra pie"),
			new ListaItem("87", "libra por pie cúbico", "libra por pie cúbico"),
			new ListaItem("89", "equilibrio", "equilibrio"),
			new ListaItem("90", "Saybold segundo universal", "Saybold segundo universal"),
			new ListaItem("91", "alimenta", "alimenta"),
			new ListaItem("92", "calorías por centímetro cúbico", "calorías por centímetro cúbico"),
			new ListaItem("93", "calorías por gramo", "calorías por gramo"),
			new ListaItem("94", "unidad", "unidad"),
			new ListaItem("95", "veinte mil galones (US) de carros", "veinte mil galones (US) de carros"),
			new ListaItem("96", "diez mil galones (US) de carros", "diez mil galones (US) de carros"),
			new ListaItem("97", "tambor de diez kg", "tambor de diez kg"),
			new ListaItem("98", "tambor de quince kg", "tambor de quince kg"),
			new ListaItem("1ª", "milla de coche", "milla de coche"),
			new ListaItem("1B", "recuento de coches", "recuento de coches"),
			new ListaItem("1C", "recuento de locomotoras", "recuento de locomotoras"),
			new ListaItem("1D", "recuento de cabos", "recuento de cabos"),
			new ListaItem("1E", "carro vacio", "carro vacio"),
			new ListaItem("1F", "millas de tren", "millas de tren"),
			new ListaItem("1G", "uso de combustible galón (US)", "uso de combustible galón (US)"),
			new ListaItem("1H", "milla del caboose", "milla del caboose"),
			new ListaItem("1I", "tipo de interés fijo", "tipo de interés fijo"),
			new ListaItem("1J", "tonelada milla", "tonelada milla"),
			new ListaItem("1K", "milla locomotora", "milla locomotora"),
			new ListaItem("1L", "recuento total de coches", "recuento total de coches"),
			new ListaItem("1M", "milla de coche total", "milla de coche total"),
			new ListaItem("1X", "cuarto de milla", "cuarto de milla"),
			new ListaItem("2ª", "radianes por segundo", "radianes por segundo"),
			new ListaItem("2B", "radianes por segundo al cuadrado", "radianes por segundo al cuadrado"),
			new ListaItem("2C", "Röntgen", "Röntgen"),
			new ListaItem("2I", "Unidad térmica británica por hora.", "Unidad térmica británica por hora."),
			new ListaItem("2J", "centímetro cúbico por segundo", "centímetro cúbico por segundo"),
			new ListaItem("2K", "pie cúbico por hora", "pie cúbico por hora"),
			new ListaItem("2L", "pie cúbico por minuto", "pie cúbico por minuto"),
			new ListaItem("2M", "centímetro por segundo", "centímetro por segundo"),
			new ListaItem("2N", "decibel", "decibel"),
			new ListaItem("2P", "kilobyte", "kilobyte"),
			new ListaItem("2Q", "kilobecquerel", "kilobecquerel"),
			new ListaItem("2R", "kilocurie", "kilocurie"),
			new ListaItem("2U", "megagramo", "megagramo"),
			new ListaItem("2V", "megagramo por hora", "megagramo por hora"),
			new ListaItem("2W", "compartimiento", "compartimiento"),
			new ListaItem("2X", "metro por minuto", "metro por minuto"),
			new ListaItem("2Y", "milliröntgen", "milliröntgen"),
			new ListaItem("2Z", "milivoltios", "milivoltios"),
			new ListaItem("3B", "megajulio", "megajulio"),
			new ListaItem("3C", "manmonth", "manmonth"),
			new ListaItem("3E", "libra por libra de producto", "libra por libra de producto"),
			new ListaItem("3G", "libra por pieza de producto", "libra por pieza de producto"),
			new ListaItem("3H", "kilogramo por kilogramo de producto", "kilogramo por kilogramo de producto"),
			new ListaItem("3I", "kilogramo por pieza de producto", "kilogramo por pieza de producto"),
			new ListaItem("4ª", "bobina", "bobina"),
			new ListaItem("4B", "gorra", "gorra"),
			new ListaItem("4C", "centistokes", "centistokes"),
			new ListaItem("4E", "paquete de veinte", "paquete de veinte"),
			new ListaItem("4G", "microlitro", "microlitro"),
			new ListaItem("4H", "micrometro", "micrometro"),
			new ListaItem("4K", "miliamperio", "miliamperio"),
			new ListaItem("4L", "megabyte", "megabyte"),
			new ListaItem("4M", "miligramo por hora", "miligramo por hora"),
			new ListaItem("4N", "megabecquerel", "megabecquerel"),
			new ListaItem("4º", "microfarad", "microfarad"),
			new ListaItem("4P", "newton por metro", "newton por metro"),
			new ListaItem("4Q", "onza pulgada", "onza pulgada"),
			new ListaItem("4R", "pie onza", "pie onza"),
			new ListaItem("4T", "picofarad", "picofarad"),
			new ListaItem("4U", "libra por hora", "libra por hora"),
			new ListaItem("4W", "tonelada (US) por hora", "tonelada (US) por hora"),
			new ListaItem("4X", "kilolitro por hora", "kilolitro por hora"),
			new ListaItem("5ª", "barril por minuto", "barril por minuto"),
			new ListaItem("5B", "lote", "lote"),
			new ListaItem("5C", "galón (US) por mil", "galón (US) por mil"),
			new ListaItem("5E", "MMSCF / día", "MMSCF / día"),
			new ListaItem("5F", "libras por mil", "libras por mil"),
			new ListaItem("5G", "bomba", "bomba"),
			new ListaItem("5H", "escenario", "escenario"),
			new ListaItem("5I", "pie cúbico estándar", "pie cúbico estándar"),
			new ListaItem("5J", "potencia hidráulica de caballos", "potencia hidráulica de caballos"),
			new ListaItem("5K", "contar por minuto", "contar por minuto"),
			new ListaItem("5P", "nivel sismico", "nivel sismico"),
			new ListaItem("5Q", "nfor sismica", "nfor sismica"),
			new ListaItem("A1", "15 calorías C", "15 calorías C"),
			new ListaItem("A10", "amperio metro cuadrado por joule segundo", "amperio metro cuadrado por joule segundo"),
			new ListaItem("A11", "Ã ¥ ngström", "Ã ¥ ngström"),
			new ListaItem("A12", "unidad astronómica", "unidad astronómica"),
			new ListaItem("A13", "attojoule", "attojoule"),
			new ListaItem("A14", "granero", "granero"),
			new ListaItem("A15", "granero por electrón voltio", "granero por electrón voltio"),
			new ListaItem("A16", "granero por voltio de electrones esteradiano,", "granero por voltio de electrones esteradiano,"),
			new ListaItem("A17", "granero por sterdian", "granero por sterdian"),
			new ListaItem("A18", "becquerel por kilogramo", "becquerel por kilogramo"),
			new ListaItem("A19", "becquerel por metro cúbico", "becquerel por metro cúbico"),
			new ListaItem("A2", "amperio por centímetro", "amperio por centímetro"),
			new ListaItem("A20", "Unidad térmica británica por segundo pie cuadrado grado Rankin", "Unidad térmica británica por segundo pie cuadrado grado Rankin"),
			new ListaItem("A21", "Unidad térmica británica por libra grado Rankin", "Unidad térmica británica por libra grado Rankin"),
			new ListaItem("A22", "Unidad térmica británica por segundo pie grado Rankin", "Unidad térmica británica por segundo pie grado Rankin"),
			new ListaItem("A23", "Unidad térmica británica por hora pie cuadrado grado Rankin", "Unidad térmica británica por hora pie cuadrado grado Rankin"),
			new ListaItem("A24", "candela por metro cuadrado", "candela por metro cuadrado"),
			new ListaItem("A25", "cheval vapeur", "cheval vapeur"),
			new ListaItem("A26", "medidor de culombio", "medidor de culombio"),
			new ListaItem("A27", "medidor de culombio al cuadrado por voltio", "medidor de culombio al cuadrado por voltio"),
			new ListaItem("A28", "Coulomb por centímetro cúbico", "Coulomb por centímetro cúbico"),
			new ListaItem("A29", "Coulomb por metro cúbico", "Coulomb por metro cúbico"),
			new ListaItem("A3", "amperio por milímetro", "amperio por milímetro"),
			new ListaItem("A30", "Coulomb por milímetro cúbico", "Coulomb por milímetro cúbico"),
			new ListaItem("A31", "Coulomb por kilogramo segundo", "Coulomb por kilogramo segundo"),
			new ListaItem("A32", "Coulomb por mol", "Coulomb por mol"),
			new ListaItem("A33", "Coulomb por centímetro cuadrado", "Coulomb por centímetro cuadrado"),
			new ListaItem("A34", "Coulomb por metro cuadrado", "Coulomb por metro cuadrado"),
			new ListaItem("A35", "Coulomb por milímetro cuadrado", "Coulomb por milímetro cuadrado"),
			new ListaItem("A36", "centímetro cúbico por mol", "centímetro cúbico por mol"),
			new ListaItem("A37", "nformaci cúbico por mol", "nformaci cúbico por mol"),
			new ListaItem("A38", "metro cúbico por coulomb", "metro cúbico por coulomb"),
			new ListaItem("A39", "metro cúbico por kilogramo", "metro cúbico por kilogramo"),
			new ListaItem("A4", "amperio por centímetro cuadrado", "amperio por centímetro cuadrado"),
			new ListaItem("A40", "metro cúbico por mol", "metro cúbico por mol"),
			new ListaItem("A41", "amperio por metro cuadrado", "amperio por metro cuadrado"),
			new ListaItem("A42", "curie por kilogramo", "curie por kilogramo"),
			new ListaItem("A43", "tonelaje de peso muerto", "tonelaje de peso muerto"),
			new ListaItem("A44", "decalitro", "decalitro"),
			new ListaItem("A45", "decámetro", "decámetro"),
			new ListaItem("A47", "decitex", "decitex"),
			new ListaItem("A48", "grado Rankin", "grado Rankin"),
			new ListaItem("A49", "negador", "negador"),
			new ListaItem("A5", "amperio metro cuadrado", "amperio metro cuadrado"),
			new ListaItem("A50", "dyn segundo por centímetro cúbico", "dyn segundo por centímetro cúbico"),
			new ListaItem("A51", "dina segundo por centímetro", "dina segundo por centímetro"),
			new ListaItem("A52", "dina segundo por centímetro al quinto", "dina segundo por centímetro al quinto"),
			new ListaItem("A53", "electronvolt", "electronvolt"),
			new ListaItem("A54", "electronvoltio por metro", "electronvoltio por metro"),
			new ListaItem("A55", "metro electronvolt cuadrado", "metro electronvolt cuadrado"),
			new ListaItem("A56", "electronvoltio de metro cuadrado por kilogramo", "electronvoltio de metro cuadrado por kilogramo"),
			new ListaItem("A57", "ergio", "ergio"),
			new ListaItem("A58", "erg por centímetro", "erg por centímetro"),
			new ListaItem("A6", "amperio por metro cuadrado kelvin al cuadrado", "amperio por metro cuadrado kelvin al cuadrado"),
			new ListaItem("A60", "erg por centímetro cúbico", "erg por centímetro cúbico"),
			new ListaItem("A61", "erg por gramo", "erg por gramo"),
			new ListaItem("A62", "erg por gramo de segundo", "erg por gramo de segundo"),
			new ListaItem("A63", "erg por segundo", "erg por segundo"),
			new ListaItem("A64", "erg por segundo centímetro cuadrado", "erg por segundo centímetro cuadrado"),
			new ListaItem("A65", "erg por centímetro cuadrado segundo", "erg por centímetro cuadrado segundo"),
			new ListaItem("A66", "erg centímetro cuadrado", "erg centímetro cuadrado"),
			new ListaItem("A67", "ergímetro cuadrado por gramo", "ergímetro cuadrado por gramo"),
			new ListaItem("A68", "exajulio", "exajulio"),
			new ListaItem("A69", "faradio por metro", "faradio por metro"),
			new ListaItem("A7", "amperio por milímetro cuadrado", "amperio por milímetro cuadrado"),
			new ListaItem("A70", "femtojoule", "femtojoule"),
			new ListaItem("A71", "femtometro", "femtometro"),
			new ListaItem("A73", "pie por segundo al cuadrado", "pie por segundo al cuadrado"),
			new ListaItem("A74", "pie-fuerza de la libra por segundo", "pie-fuerza de la libra por segundo"),
			new ListaItem("A75", "tonelada de carga", "tonelada de carga"),
			new ListaItem("A76", "galón", "galón"),
			new ListaItem("A77", "Unidad de desplazamiento CGS gaussiana", "Unidad de desplazamiento CGS gaussiana"),
			new ListaItem("A78", "Unidad gaussiana CGS de corriente eléctrica.", "Unidad gaussiana CGS de corriente eléctrica."),
			new ListaItem("A79", "Unidad Gaussian CGS de carga eléctrica.", "Unidad Gaussian CGS de carga eléctrica."),
			new ListaItem("A8", "amperio segundo", "amperio segundo"),
			new ListaItem("A80", "Unidad Gaussian CGS de intensidad de campo eléctrico.", "Unidad Gaussian CGS de intensidad de campo eléctrico."),
			new ListaItem("A81", "Unidad Gaussian CGS de polarización eléctrica.", "Unidad Gaussian CGS de polarización eléctrica."),
			new ListaItem("A82", "Unidad Gaussian CGS de potencial eléctrico.", "Unidad Gaussian CGS de potencial eléctrico."),
			new ListaItem("A83", "Unidad Gaussiana CGS de magnetización.", "Unidad Gaussiana CGS de magnetización."),
			new ListaItem("A84", "gigacoulomb por metro cúbico", "gigacoulomb por metro cúbico"),
			new ListaItem("A85", "Gigaelectronvolt", "Gigaelectronvolt"),
			new ListaItem("A86", "gigahercios", "gigahercios"),
			new ListaItem("A87", "gigaohm", "gigaohm"),
			new ListaItem("A88", "medidor de gigaohm", "medidor de gigaohm"),
			new ListaItem("A89", "gigapascal", "gigapascal"),
			new ListaItem("A9", "tarifa", "tarifa"),
			new ListaItem("A90", "gigavatios", "gigavatios"),
			new ListaItem("A91", "gon", "gon"),
			new ListaItem("A93", "gramo por metro cúbico", "gramo por metro cúbico"),
			new ListaItem("A94", "gramo por mol", "gramo por mol"),
			new ListaItem("A95", "gris", "gris"),
			new ListaItem("A96", "gris por segundo", "gris por segundo"),
			new ListaItem("A97", "hectopascal", "hectopascal"),
			new ListaItem("A98", "Henry por metro", "Henry por metro"),
			new ListaItem("AA", "bola", "bola"),
			new ListaItem("AB", "paquete a granel", "paquete a granel"),
			new ListaItem("ACR", "acre", "acre"),
			new ListaItem("AD", "byte", "byte"),
			new ListaItem("AE", "amperio por metro", "amperio por metro"),
			new ListaItem("AH", "minuto adicional", "minuto adicional"),
			new ListaItem("AI", "minuto promedio por llamada", "minuto promedio por llamada"),
			new ListaItem("AJ", "policía", "policía"),
			new ListaItem("AK", "braza", "braza"),
			new ListaItem("AL", "nfor de acceso", "nfor de acceso"),
			new ListaItem("AM", "ampolla", "ampolla"),
			new ListaItem("AMH", "hora amperio", "hora amperio"),
			new ListaItem("AMP", "amperio", "amperio"),
			new ListaItem("ANA", "año", "año"),
			new ListaItem("AP", "solo libra de aluminio", "solo libra de aluminio"),
			new ListaItem("APZ", "onza troy o onza de boticarios", "onza troy o onza de boticarios"),
			new ListaItem("AQ", "Unidad de factor antihemofílico (AHF)", "Unidad de factor antihemofílico (AHF)"),
			new ListaItem("AR", "supositorio", "supositorio"),
			new ListaItem("SON", "son", "son"),
			new ListaItem("COMO", "surtido", "surtido"),
			new ListaItem("ASM", "fuerza alcohólica en masa", "fuerza alcohólica en masa"),
			new ListaItem("ASU", "fuerza alcohólica por volumen", "fuerza alcohólica por volumen"),
			new ListaItem("ATM", "ambiente estándar", "ambiente estándar"),
			new ListaItem("ATT", "ambiente técnico", "ambiente técnico"),
			new ListaItem("AV", "cápsula", "cápsula"),
			new ListaItem("AW", "vial lleno de polvo", "vial lleno de polvo"),
			new ListaItem("SÍ", "montaje", "montaje"),
			new ListaItem("AZ", "Unidad térmica británica por libra", "Unidad térmica británica por libra"),
			new ListaItem("B0", "Btu por pie cúbico", "Btu por pie cúbico"),
			new ListaItem("B1", "barril (US) por día", "barril (US) por día"),
			new ListaItem("B11", "julios por kilogramo kelvin", "julios por kilogramo kelvin"),
			new ListaItem("B12", "julios por metro", "julios por metro"),
			new ListaItem("B13", "julios por metro cuadrado", "julios por metro cuadrado"),
			new ListaItem("B14", "julios por metro a la cuarta potencia", "julios por metro a la cuarta potencia"),
			new ListaItem("B15", "julios por mol", "julios por mol"),
			new ListaItem("B16", "julios por mol kelvin", "julios por mol kelvin"),
			new ListaItem("B18", "joule segundo", "joule segundo"),
			new ListaItem("B2", "litera", "litera"),
			new ListaItem("B20", "joule metro cuadrado por kilogramo", "joule metro cuadrado por kilogramo"),
			new ListaItem("B21", "kelvin por vatio", "kelvin por vatio"),
			new ListaItem("B22", "Kiloampere", "Kiloampere"),
			new ListaItem("B23", "kiloampere por metro cuadrado", "kiloampere por metro cuadrado"),
			new ListaItem("B24", "kiloampere por metro", "kiloampere por metro"),
			new ListaItem("B25", "kilobecquerel por kilogramo", "kilobecquerel por kilogramo"),
			new ListaItem("B26", "kilocoulomb", "kilocoulomb"),
			new ListaItem("B27", "kilocoulomb por metro cúbico", "kilocoulomb por metro cúbico"),
			new ListaItem("B28", "kilocoulomb por metro cuadrado", "kilocoulomb por metro cuadrado"),
			new ListaItem("B29", "kiloelectronvolt", "kiloelectronvolt"),
			new ListaItem("B3", "libra de bateo", "libra de bateo"),
			new ListaItem("B31", "kilogramo metro por segundo", "kilogramo metro por segundo"),
			new ListaItem("B32", "kilogramo metro cuadrado", "kilogramo metro cuadrado"),
			new ListaItem("B33", "kilogramo metro cuadrado por segundo", "kilogramo metro cuadrado por segundo"),
			new ListaItem("B34", "kilogramo por decímetro cúbico", "kilogramo por decímetro cúbico"),
			new ListaItem("B35", "kilogramo por litro", "kilogramo por litro"),
			new ListaItem("B36", "caloría termoquímica por gramo", "caloría termoquímica por gramo"),
			new ListaItem("B37", "kilogramo de fuerza", "kilogramo de fuerza"),
			new ListaItem("B38", "metro de fuerza de kilogramo", "metro de fuerza de kilogramo"),
			new ListaItem("B39", "metro de fuerza de kilogramo por segundo", "metro de fuerza de kilogramo por segundo"),
			new ListaItem("B4", "barril, imperial", "barril, imperial"),
			new ListaItem("B40", "kilogramo de fuerza por metro cuadrado", "kilogramo de fuerza por metro cuadrado"),
			new ListaItem("B41", "kilojoule per kelvin", "kilojoule per kelvin"),
			new ListaItem("B42", "kilojoule por kilogramo", "kilojoule por kilogramo"),
			new ListaItem("B43", "kilojoule por kilogramo kelvin", "kilojoule por kilogramo kelvin"),
			new ListaItem("B44", "kilojoule por mol", "kilojoule por mol"),
			new ListaItem("B45", "kilomol", "kilomol"),
			new ListaItem("B46", "kilomol por metro cúbico", "kilomol por metro cúbico"),
			new ListaItem("B47", "Kilonewton", "Kilonewton"),
			new ListaItem("B48", "medidor de kilonewton", "medidor de kilonewton"),
			new ListaItem("B49", "kiloohm", "kiloohm"),
			new ListaItem("B5", "palanquilla", "palanquilla"),
			new ListaItem("B50", "medidor de kiloohm", "medidor de kiloohm"),
			new ListaItem("B51", "kilopond", "kilopond"),
			new ListaItem("B52", "kilosegundo", "kilosegundo"),
			new ListaItem("B53", "kilosiemens", "kilosiemens"),
			new ListaItem("B54", "kilosiemens por metro", "kilosiemens por metro"),
			new ListaItem("B55", "kilovoltios por metro", "kilovoltios por metro"),
			new ListaItem("B56", "kiloveber por metro", "kiloveber por metro"),
			new ListaItem("B57", "año luz", "año luz"),
			new ListaItem("B58", "litro por mol", "litro por mol"),
			new ListaItem("B59", "hora lumen", "hora lumen"),
			new ListaItem("B6", "bollo", "bollo"),
			new ListaItem("B60", "lumen por metro cuadrado", "lumen por metro cuadrado"),
			new ListaItem("B61", "lumen por vatio", "lumen por vatio"),
			new ListaItem("B62", "lumen segundo", "lumen segundo"),
			new ListaItem("B63", "hora de lux", "hora de lux"),
			new ListaItem("B64", "lux segundo", "lux segundo"),
			new ListaItem("B65", "Maxwell", "Maxwell"),
			new ListaItem("B66", "megaamperios por metro cuadrado", "megaamperios por metro cuadrado"),
			new ListaItem("B67", "megabecquerel por kilogramo", "megabecquerel por kilogramo"),
			new ListaItem("B69", "megacoulomb por metro cúbico", "megacoulomb por metro cúbico"),
			new ListaItem("B7", "ciclo", "ciclo"),
			new ListaItem("B70", "megacoulomb por metro cuadrado", "megacoulomb por metro cuadrado"),
			new ListaItem("B71", "megaelectronvolt", "megaelectronvolt"),
			new ListaItem("B72", "megagramo por metro cúbico", "megagramo por metro cúbico"),
			new ListaItem("B73", "meganewton", "meganewton"),
			new ListaItem("B74", "medidor de meganewton", "medidor de meganewton"),
			new ListaItem("B75", "megaohm", "megaohm"),
			new ListaItem("B76", "metro megaohm", "metro megaohm"),
			new ListaItem("B77", "megasiemens por metro", "megasiemens por metro"),
			new ListaItem("B78", "megavoltio", "megavoltio"),
			new ListaItem("B79", "megavolt por metro", "megavolt por metro"),
			new ListaItem("B8", "julios por metro cúbico", "julios por metro cúbico"),
			new ListaItem("B81", "metro recíproco cuadrado recíproco segundo", "metro recíproco cuadrado recíproco segundo"),
			new ListaItem("B83", "metro a la cuarta potencia", "metro a la cuarta potencia"),
			new ListaItem("B84", "microamperios", "microamperios"),
			new ListaItem("B85", "microbar", "microbar"),
			new ListaItem("B86", "microcoulomb", "microcoulomb"),
			new ListaItem("B87", "microcoulomb por metro cúbico", "microcoulomb por metro cúbico"),
			new ListaItem("B88", "microcoulomb por metro cuadrado", "microcoulomb por metro cuadrado"),
			new ListaItem("B89", "microfarada por metro", "microfarada por metro"),
			new ListaItem("B9", "batt", "batt"),
			new ListaItem("B90", "microhenry", "microhenry"),
			new ListaItem("B91", "microhenry por metro", "microhenry por metro"),
			new ListaItem("B92", "micronewton", "micronewton"),
			new ListaItem("B93", "medidor de micronewton", "medidor de micronewton"),
			new ListaItem("B94", "microohm", "microohm"),
			new ListaItem("B95", "medidor de microohmios", "medidor de microohmios"),
			new ListaItem("B96", "micropascal", "micropascal"),
			new ListaItem("B97", "microradiano", "microradiano"),
			new ListaItem("B98", "microsegundo", "microsegundo"),
			new ListaItem("B99", "microsiemens", "microsiemens"),
			new ListaItem("BAR", "bar", "bar"),
			new ListaItem("BB", "caja base", "caja base"),
			new ListaItem("BD", "tablero", "tablero"),
			new ListaItem("SER", "haz", "haz"),
			new ListaItem("BFT", "pie de tabla", "pie de tabla"),
			new ListaItem("BG", "bolso", "bolso"),
			new ListaItem("BH", "cepillo", "cepillo"),
			new ListaItem("BHP", "potencia al freno", "potencia al freno"),
			new ListaItem("BIL", "trillón de dólares", "trillón de dólares"),
			new ListaItem("BJ", "cangilón", "cangilón"),
			new ListaItem("BK", "cesta", "cesta"),
			new ListaItem("BL", "bala", "bala"),
			new ListaItem("BLD", "barril seco", "barril seco"),
			new ListaItem("BLL", "barril (EE. UU.) (petróleo, etc.)", "barril (EE. UU.) (petróleo, etc.)"),
			new ListaItem("BO", "botella", "botella"),
			new ListaItem("BP", "cien pies de tabla", "cien pies de tabla"),
			new ListaItem("BQL", "becquerel", "becquerel"),
			new ListaItem("BR", "bar", "bar"),
			new ListaItem("BT", "tornillo", "tornillo"),
			new ListaItem("BTU", "Unidad Térmica Británica", "Unidad Térmica Británica"),
			new ListaItem("BUA", "bushel (EE. UU.)", "bushel (EE. UU.)"),
			new ListaItem("BUI", "bushel (Reino Unido)", "bushel (Reino Unido)"),
			new ListaItem("BW", "peso base", "peso base"),
			new ListaItem("BX", "caja", "caja"),
			new ListaItem("BZ", "millones de BTUs", "millones de BTUs"),
			new ListaItem("C0", "llamada", "llamada"),
			new ListaItem("C1", "producto compuesto libra (peso total)", "producto compuesto libra (peso total)"),
			new ListaItem("C10", "millifarad", "millifarad"),
			new ListaItem("C11", "miligal", "miligal"),
			new ListaItem("C12", "miligramo por metro", "miligramo por metro"),
			new ListaItem("C13", "miligray", "miligray"),
			new ListaItem("C14", "milihenry", "milihenry"),
			new ListaItem("C15", "milijoule", "milijoule"),
			new ListaItem("C16", "milímetro por segundo", "milímetro por segundo"),
			new ListaItem("C17", "milímetro cuadrado por segundo", "milímetro cuadrado por segundo"),
			new ListaItem("C18", "milimol", "milimol"),
			new ListaItem("C19", "mol por kilogramo", "mol por kilogramo"),
			new ListaItem("C2", "carset", "carset"),
			new ListaItem("C20", "millinewton", "millinewton"),
			new ListaItem("C22", "millinewton por metro", "millinewton por metro"),
			new ListaItem("C23", "medidor de miliohm", "medidor de miliohm"),
			new ListaItem("C24", "segundo milipascal", "segundo milipascal"),
			new ListaItem("C25", "miliradian", "miliradian"),
			new ListaItem("C26", "milisegundo", "milisegundo"),
			new ListaItem("C27", "milisiemens", "milisiemens"),
			new ListaItem("C28", "milisievert", "milisievert"),
			new ListaItem("C29", "millitesla", "millitesla"),
			new ListaItem("C3", "microvoltios por metro", "microvoltios por metro"),
			new ListaItem("C30", "milivoltios por metro", "milivoltios por metro"),
			new ListaItem("C31", "milivatios", "milivatios"),
			new ListaItem("C32", "milivatios por metro cuadrado", "milivatios por metro cuadrado"),
			new ListaItem("C33", "milliweber", "milliweber"),
			new ListaItem("C34", "Topo", "Topo"),
			new ListaItem("C35", "mol por decímetro cúbico", "mol por decímetro cúbico"),
			new ListaItem("C36", "mol por metro cúbico", "mol por metro cúbico"),
			new ListaItem("C38", "mol por litro", "mol por litro"),
			new ListaItem("C39", "Nanoampere", "Nanoampere"),
			new ListaItem("C4", "partido de carga", "partido de carga"),
			new ListaItem("C40", "nanocoulomb", "nanocoulomb"),
			new ListaItem("C41", "nanofarad", "nanofarad"),
			new ListaItem("C42", "nanofarad por metro", "nanofarad por metro"),
			new ListaItem("C43", "nanohenry", "nanohenry"),
			new ListaItem("C44", "nanohenry por metro", "nanohenry por metro"),
			new ListaItem("C45", "nanometro", "nanometro"),
			new ListaItem("C46", "medidor de nanoohm", "medidor de nanoohm"),
			new ListaItem("C47", "nanosegundo", "nanosegundo"),
			new ListaItem("C48", "nanotesla", "nanotesla"),
			new ListaItem("C49", "nanovatio", "nanovatio"),
			new ListaItem("C5", "costo", "costo"),
			new ListaItem("C50", "neper", "neper"),
			new ListaItem("C51", "neper por segundo", "neper por segundo"),
			new ListaItem("C52", "picometro", "picometro"),
			new ListaItem("C53", "metro de newton segundo", "metro de newton segundo"),
			new ListaItem("C54", "newton metro cuadrado kilogramo cuadrado", "newton metro cuadrado kilogramo cuadrado"),
			new ListaItem("C55", "newton por metro cuadrado", "newton por metro cuadrado"),
			new ListaItem("C56", "newton por milímetro cuadrado", "newton por milímetro cuadrado"),
			new ListaItem("C57", "newton segundo", "newton segundo"),
			new ListaItem("C58", "newton segundo por metro", "newton segundo por metro"),
			new ListaItem("C59", "octava", "octava"),
			new ListaItem("C6", "célula", "célula"),
			new ListaItem("C60", "ohm centímetro", "ohm centímetro"),
			new ListaItem("C61", "ohm metro", "ohm metro"),
			new ListaItem("C62", "uno", "uno"),
			new ListaItem("C63", "parsec", "parsec"),
			new ListaItem("C64", "pascal por kelvin", "pascal por kelvin"),
			new ListaItem("C65", "segundo pascal", "segundo pascal"),
			new ListaItem("C66", "segundo pascal por metro cúbico", "segundo pascal por metro cúbico"),
			new ListaItem("C67", "segundo pascal por metro", "segundo pascal por metro"),
			new ListaItem("C68", "petajoule", "petajoule"),
			new ListaItem("C69", "telefono", "telefono"),
			new ListaItem("C7", "centipoise", "centipoise"),
			new ListaItem("C70", "picoampere", "picoampere"),
			new ListaItem("C71", "picocoulomb", "picocoulomb"),
			new ListaItem("C72", "picofarad por metro", "picofarad por metro"),
			new ListaItem("C73", "picohenry", "picohenry"),
			new ListaItem("C75", "picowatt", "picowatt"),
			new ListaItem("C76", "picowatt por metro cuadrado", "picowatt por metro cuadrado"),
			new ListaItem("C77", "medidor de libras", "medidor de libras"),
			new ListaItem("C78", "fuerza de libra", "fuerza de libra"),
			new ListaItem("C8", "Millicoulomb por kilogramo", "Millicoulomb por kilogramo"),
			new ListaItem("C80", "rad", "rad"),
			new ListaItem("C81", "radián", "radián"),
			new ListaItem("C82", "medidor de radianes al cuadrado por mol", "medidor de radianes al cuadrado por mol"),
			new ListaItem("C83", "medidor de radianes al cuadrado por kilogramo", "medidor de radianes al cuadrado por kilogramo"),
			new ListaItem("C84", "radian por metro", "radian por metro"),
			new ListaItem("C85", "â € ngstr recíproco “m", "â € ngstr recíproco “m"),
			new ListaItem("C86", "metro cúbico recíproco", "metro cúbico recíproco"),
			new ListaItem("C87", "metro cúbico recíproco por segundo", "metro cúbico recíproco por segundo"),
			new ListaItem("C88", "voltios de electrones recíprocos por metro cúbico", "voltios de electrones recíprocos por metro cúbico"),
			new ListaItem("C89", "Henry Recíproco", "Henry Recíproco"),
			new ListaItem("C9", "grupo de bobina", "grupo de bobina"),
			new ListaItem("C90", "Joule recíproco por metro cúbico", "Joule recíproco por metro cúbico"),
			new ListaItem("C91", "kelvin recíproco o kelvin al poder menos uno", "kelvin recíproco o kelvin al poder menos uno"),
			new ListaItem("C92", "medidor recíproco", "medidor recíproco"),
			new ListaItem("C93", "metro cuadrado recíproco", "metro cuadrado recíproco"),
			new ListaItem("C94", "minuto recíproco", "minuto recíproco"),
			new ListaItem("C95", "mole recíproco", "mole recíproco"),
			new ListaItem("C96", "Pascal recíproco o pascal a la potencia menos uno.", "Pascal recíproco o pascal a la potencia menos uno."),
			new ListaItem("C97", "segundo recíproco", "segundo recíproco"),
			new ListaItem("C98", "segundo recíproco por metro cúbico", "segundo recíproco por metro cúbico"),
			new ListaItem("C99", "segundo recíproco por metro cuadrado", "segundo recíproco por metro cuadrado"),
			new ListaItem("CA", "Caja", "Caja"),
			new ListaItem("CCT", "Capacidad de carga en toneladas métricas.", "Capacidad de carga en toneladas métricas."),
			new ListaItem("CDL", "candela", "candela"),
			new ListaItem("CEL", "grado Celsius", "grado Celsius"),
			new ListaItem("CEN", "cien", "cien"),
			new ListaItem("CG", "tarjeta", "tarjeta"),
			new ListaItem("CGM", "centigramo", "centigramo"),
			new ListaItem("CH", "envase", "envase"),
			new ListaItem("CJ", "cono", "cono"),
			new ListaItem("CK", "conector", "conector"),
			new ListaItem("CKG", "Coulomb por kilogramo", "Coulomb por kilogramo"),
			new ListaItem("CL", "bobina", "bobina"),
			new ListaItem("CLF", "cientos de licencia", "cientos de licencia"),
			new ListaItem("CLT", "centilitro", "centilitro"),
			new ListaItem("CMK", "centímetro cuadrado", "centímetro cuadrado"),
			new ListaItem("CMQ", "centímetro cúbico", "centímetro cúbico"),
			new ListaItem("CMT", "centímetro", "centímetro"),
			new ListaItem("CNP", "paquete de cien", "paquete de cien"),
			new ListaItem("CNT", "Cental (Reino Unido)", "Cental (Reino Unido)"),
			new ListaItem("CO", "garrafón", "garrafón"),
			new ListaItem("COU", "culombio", "culombio"),
			new ListaItem("CQ", "cartucho", "cartucho"),
			new ListaItem("CR", "caja", "caja"),
			new ListaItem("CS", "caso", "caso"),
			new ListaItem("CT", "caja de cartón", "caja de cartón"),
			new ListaItem("CTM", "quilate métrico", "quilate métrico"),
			new ListaItem("CU", "vaso", "vaso"),
			new ListaItem("CUR", "curie", "curie"),
			new ListaItem("CV", "cubrir", "cubrir"),
			new ListaItem("CWA", "cien libras (quintales) / cien pesos (US)", "cien libras (quintales) / cien pesos (US)"),
			new ListaItem("CWI", "cien pesos (Reino Unido)", "cien pesos (Reino Unido)"),
			new ListaItem("CY", "cilindro", "cilindro"),
			new ListaItem("CZ", "combo", "combo"),
			new ListaItem("D1", "segundo recíproco por esteradiano", "segundo recíproco por esteradiano"),
			new ListaItem("D10", "siemens por metro", "siemens por metro"),
			new ListaItem("D12", "siemens metro cuadrado por mol", "siemens metro cuadrado por mol"),
			new ListaItem("D13", "sievert", "sievert"),
			new ListaItem("D14", "mil yardas lineales", "mil yardas lineales"),
			new ListaItem("D15", "sone", "sone"),
			new ListaItem("D16", "centímetro cuadrado por ergio", "centímetro cuadrado por ergio"),
			new ListaItem("D17", "centímetro cuadrado por erg esterlina", "centímetro cuadrado por erg esterlina"),
			new ListaItem("D18", "metro kelvin", "metro kelvin"),
			new ListaItem("D19", "kelvin metro cuadrado por vatio", "kelvin metro cuadrado por vatio"),
			new ListaItem("D2", "segundo recíproco por metros cuadrados esteradianos", "segundo recíproco por metros cuadrados esteradianos"),
			new ListaItem("D20", "metro cuadrado por julio", "metro cuadrado por julio"),
			new ListaItem("D21", "metro cuadrado por kilogramo", "metro cuadrado por kilogramo"),
			new ListaItem("D22", "metro cuadrado por mol", "metro cuadrado por mol"),
			new ListaItem("D23", "pluma gramo (proteína)", "pluma gramo (proteína)"),
			new ListaItem("D24", "metro cuadrado por esterilizador", "metro cuadrado por esterilizador"),
			new ListaItem("D25", "metro cuadrado por julios esteradianos", "metro cuadrado por julios esteradianos"),
			new ListaItem("D26", "metro cuadrado por voltio segundo", "metro cuadrado por voltio segundo"),
			new ListaItem("D27", "esteradiano", "esteradiano"),
			new ListaItem("D28", "sifón", "sifón"),
			new ListaItem("D29", "terahercios", "terahercios"),
			new ListaItem("D30", "terajulio", "terajulio"),
			new ListaItem("D31", "teravatio", "teravatio"),
			new ListaItem("D32", "hora de teravatio", "hora de teravatio"),
			new ListaItem("D33", "tesla", "tesla"),
			new ListaItem("D34", "Texas", "Texas"),
			new ListaItem("D35", "caloría termoquímica", "caloría termoquímica"),
			new ListaItem("D37", "caloría termoquímica por gramo kelvin", "caloría termoquímica por gramo kelvin"),
			new ListaItem("D38", "calorías termoquímicas por segundo centímetro kelvin", "calorías termoquímicas por segundo centímetro kelvin"),
			new ListaItem("D39", "calorías termoquímicas por segundo centímetro cuadrado kelvin", "calorías termoquímicas por segundo centímetro cuadrado kelvin"),
			new ListaItem("D40", "mil litros", "mil litros"),
			new ListaItem("D41", "tonelada por metro cúbico", "tonelada por metro cúbico"),
			new ListaItem("D42", "año tropical", "año tropical"),
			new ListaItem("D43", "unidad de masa atómica unificada", "unidad de masa atómica unificada"),
			new ListaItem("D44", "var", "var"),
			new ListaItem("D45", "voltios al cuadrado por kelvin al cuadrado", "voltios al cuadrado por kelvin al cuadrado"),
			new ListaItem("D46", "voltio – amperio", "voltio – amperio"),
			new ListaItem("D47", "voltio por centímetro", "voltio por centímetro"),
			new ListaItem("D48", "voltio por kelvin", "voltio por kelvin"),
			new ListaItem("D49", "milivoltios por kelvin", "milivoltios por kelvin"),
			new ListaItem("D5", "kilogramo por centímetro cuadrado", "kilogramo por centímetro cuadrado"),
			new ListaItem("D50", "voltios por metro", "voltios por metro"),
			new ListaItem("D51", "voltios por milímetro", "voltios por milímetro"),
			new ListaItem("D52", "vatios por kelvin", "vatios por kelvin"),
			new ListaItem("D53", "vatios por metro kelvin", "vatios por metro kelvin"),
			new ListaItem("D54", "vatios por metro cuadrado", "vatios por metro cuadrado"),
			new ListaItem("D55", "vatios por metro cuadrado kelvin", "vatios por metro cuadrado kelvin"),
			new ListaItem("D56", "vatios por metro cuadrado de kelvin a la cuarta potencia", "vatios por metro cuadrado de kelvin a la cuarta potencia"),
			new ListaItem("D57", "vatios por steradian", "vatios por steradian"),
			new ListaItem("D58", "vatios por metro cuadrado esterlino", "vatios por metro cuadrado esterlino"),
			new ListaItem("D59", "weber por metro", "weber por metro"),
			new ListaItem("D6", "röntgen por segundo", "röntgen por segundo"),
			new ListaItem("D60", "weber por milímetro", "weber por milímetro"),
			new ListaItem("D61", "minuto", "minuto"),
			new ListaItem("D62", "segundo", "segundo"),
			new ListaItem("D63", "libro", "libro"),
			new ListaItem("D64", "bloquear", "bloquear"),
			new ListaItem("D65", "redondo", "redondo"),
			new ListaItem("D66", "casete", "casete"),
			new ListaItem("D67", "dólar por hora", "dólar por hora"),
			new ListaItem("D69", "pulgada a la cuarta potencia", "pulgada a la cuarta potencia"),
			new ListaItem("D7", "Sandwich", "Sandwich"),
			new ListaItem("D70", "Tabla Internacional (IT) caloría", "Tabla Internacional (IT) caloría"),
			new ListaItem("D71", "Tabla Internacional (IT) calorías por segundo centímetro kelvin", "Tabla Internacional (IT) calorías por segundo centímetro kelvin"),
			new ListaItem("D72", "Tabla Internacional (IT) calorías por segundo centímetro cuadrado kelvin", "Tabla Internacional (IT) calorías por segundo centímetro cuadrado kelvin"),
			new ListaItem("D73", "joule metro cuadrado", "joule metro cuadrado"),
			new ListaItem("D74", "kilogramo por mol", "kilogramo por mol"),
			new ListaItem("D75", "Tabla Internacional (IT) calorías por gramo", "Tabla Internacional (IT) calorías por gramo"),
			new ListaItem("D76", "Tabla Internacional (IT) calorías por gramo kelvin", "Tabla Internacional (IT) calorías por gramo kelvin"),
			new ListaItem("D77", "megacoulomb", "megacoulomb"),
			new ListaItem("D79", "haz", "haz"),
			new ListaItem("D8", "puntaje de drenaje", "puntaje de drenaje"),
			new ListaItem("D80", "microwatt", "microwatt"),
			new ListaItem("D81", "microtesla", "microtesla"),
			new ListaItem("D82", "microvoltio", "microvoltio"),
			new ListaItem("D83", "medidor de millinewton", "medidor de millinewton"),
			new ListaItem("D85", "microwatt por metro cuadrado", "microwatt por metro cuadrado"),
			new ListaItem("D86", "Millicoulomb", "Millicoulomb"),
			new ListaItem("D87", "milimol por kilogramo", "milimol por kilogramo"),
			new ListaItem("D88", "millicoulomb por metro cúbico", "millicoulomb por metro cúbico"),
			new ListaItem("D89", "millicoulomb por metro cuadrado", "millicoulomb por metro cuadrado"),
			new ListaItem("D9", "dina por centímetro cuadrado", "dina por centímetro cuadrado"),
			new ListaItem("D90", "metro cúbico (neto)", "metro cúbico (neto)"),
			new ListaItem("D91", "movimiento rápido del ojo", "movimiento rápido del ojo"),
			new ListaItem("D92", "banda", "banda"),
			new ListaItem("D93", "segundo por metro cúbico", "segundo por metro cúbico"),
			new ListaItem("D94", "segundo por metro cúbico radianes", "segundo por metro cúbico radianes"),
			new ListaItem("D95", "julios por gramo", "julios por gramo"),
			new ListaItem("D96", "libra bruta", "libra bruta"),
			new ListaItem("D97", "carga de palet / unidad", "carga de palet / unidad"),
			new ListaItem("D98", "libra de masa", "libra de masa"),
			new ListaItem("D99", "manga", "manga"),
			new ListaItem("DAA", "despreciar", "despreciar"),
			new ListaItem("DAD", "diez dias", "diez dias"),
			new ListaItem("DAY", "día", "día"),
			new ListaItem("DB", "libra seca", "libra seca"),
			new ListaItem("DC", "disco", "disco"),
			new ListaItem("DD", "la licenciatura", "la licenciatura"),
			new ListaItem("DE", "acuerdo", "acuerdo"),
			new ListaItem("DEC", "década", "década"),
			new ListaItem("DG", "decigramo", "decigramo"),
			new ListaItem("DI", "dispensador", "dispensador"),
			new ListaItem("DJ", "decagramo", "decagramo"),
			new ListaItem("DLT", "decilitro", "decilitro"),
			new ListaItem("DMK", "nformaci cuadrado", "nformaci cuadrado"),
			new ListaItem("DMQ", "decímetro cúbico", "decímetro cúbico"),
			new ListaItem("DMT", "decímetro", "decímetro"),
			new ListaItem("DN", "medidor de decinewton", "medidor de decinewton"),
			new ListaItem("DPC", "docena pieza", "docena pieza"),
			new ListaItem("DPR", "docena par", "docena par"),
			new ListaItem("DPT", "tonelaje de desplazamiento", "tonelaje de desplazamiento"),
			new ListaItem("DQ", "registro de datos", "registro de datos"),
			new ListaItem("DR", "tambor", "tambor"),
			new ListaItem("DRA", "dram (US)", "dram (US)"),
			new ListaItem("DRI", "dram (Reino Unido)", "dram (Reino Unido)"),
			new ListaItem("DRL", "docena rollo", "docena rollo"),
			new ListaItem("DRM", "dracma (Reino Unido)", "dracma (Reino Unido)"),
			new ListaItem("DS", "monitor", "monitor"),
			new ListaItem("DT", "tonelada seca", "tonelada seca"),
			new ListaItem("DTN", "Decitonne", "Decitonne"),
			new ListaItem("DU", "dina", "dina"),
			new ListaItem("DWT", "pennyweight", "pennyweight"),
			new ListaItem("DX", "dina por centímetro", "dina por centímetro"),
			new ListaItem("DY", "libro de directorio", "libro de directorio"),
			new ListaItem("DZN", "docena", "docena"),
			new ListaItem("DZP", "paquete de doce", "paquete de doce"),
			new ListaItem("E2", "cinturón", "cinturón"),
			new ListaItem("E3", "remolque", "remolque"),
			new ListaItem("E4", "kilogramo bruto", "kilogramo bruto"),
			new ListaItem("E5", "tonelada métrica larga", "tonelada métrica larga"),
			new ListaItem("EA", "cada", "cada"),
			new ListaItem("EB", "casilla de correo electrónico", "casilla de correo electrónico"),
			new ListaItem("CE", "cada uno por mes", "cada uno por mes"),
			new ListaItem("EP", "paquete de once", "paquete de once"),
			new ListaItem("EQ", "galón equivalente", "galón equivalente"),
			new ListaItem("EV", "sobre", "sobre"),
			new ListaItem("F1", "mil pies cúbicos por día", "mil pies cúbicos por día"),
			new ListaItem("F9", "Fibra por centímetro cúbico de aire", "Fibra por centímetro cúbico de aire"),
			new ListaItem("FAH", "grado Fahrenheit", "grado Fahrenheit"),
			new ListaItem("FAR", "faradio", "faradio"),
			new ListaItem("FB", "campo", "campo"),
			new ListaItem("FC", "mil pies cúbicos", "mil pies cúbicos"),
			new ListaItem("FD", "millón de partículas por pie cúbico", "millón de partículas por pie cúbico"),
			new ListaItem("FE", "pie de pista", "pie de pista"),
			new ListaItem("FF", "cien metros cúbicos", "cien metros cúbicos"),
			new ListaItem("FG", "parche transdérmico", "parche transdérmico"),
			new ListaItem("FH", "micromol", "micromol"),
			new ListaItem("FL", "tonelada en escamas", "tonelada en escamas"),
			new ListaItem("FM", "millones de pies cúbicos", "millones de pies cúbicos"),
			new ListaItem("FOT", "pie", "pie"),
			new ListaItem("FP", "libra por pie cuadrado", "libra por pie cuadrado"),
			new ListaItem("FR", "pie por minuto", "pie por minuto"),
			new ListaItem("FS", "pie por segundo", "pie por segundo"),
			new ListaItem("FTK", "pie cuadrado", "pie cuadrado"),
			new ListaItem("FTQ", "pie cubico", "pie cubico"),
			new ListaItem("G2", "US galones por minuto", "US galones por minuto"),
			new ListaItem("G3", "Galon imperial por minuto", "Galon imperial por minuto"),
			new ListaItem("G7", "hoja de microficha", "hoja de microficha"),
			new ListaItem("GB", "galón (US) por día", "galón (US) por día"),
			new ListaItem("GBQ", "gigabecquerel", "gigabecquerel"),
			new ListaItem("GC", "gramo por 100 gramo", "gramo por 100 gramo"),
			new ListaItem("GD", "barril bruto", "barril bruto"),
			new ListaItem("GE", "libra por galón (US)", "libra por galón (US)"),
			new ListaItem("GF", "gramo por metro (gramo por 100 centímetros)", "gramo por metro (gramo por 100 centímetros)"),
			new ListaItem("GFI", "gramo de isótopo fisionable", "gramo de isótopo fisionable"),
			new ListaItem("GGR", "gramo", "gramo"),
			new ListaItem("GH", "medio galón (EE. UU.)", "medio galón (EE. UU.)"),
			new ListaItem("GIA", "branquias", "branquias"),
			new ListaItem("GII", "Gill (Reino Unido)", "Gill (Reino Unido)"),
			new ListaItem("GJ", "gramo por mililitro", "gramo por mililitro"),
			new ListaItem("G K", "gramo por kilogramo", "gramo por kilogramo"),
			new ListaItem("GL", "gramo por litro", "gramo por litro"),
			new ListaItem("GLD", "galón seco (EE. UU.)", "galón seco (EE. UU.)"),
			new ListaItem("GLI", "galón (Reino Unido)", "galón (Reino Unido)"),
			new ListaItem("GLL", "galón", "galón"),
			new ListaItem("GM", "gramo por metro cuadrado", "gramo por metro cuadrado"),
			new ListaItem("GN", "galón bruto", "galón bruto"),
			new ListaItem("GO", "miligramos por metro cuadrado", "miligramos por metro cuadrado"),
			new ListaItem("GP", "miligramo por metro cúbico", "miligramo por metro cúbico"),
			new ListaItem("GQ", "microgramos por metro cúbico", "microgramos por metro cúbico"),
			new ListaItem("GRM", "gramo", "gramo"),
			new ListaItem("GRN", "grano", "grano"),
			new ListaItem("GRO", "bruto", "bruto"),
			new ListaItem("GRT", "tonelada de registro bruto", "tonelada de registro bruto"),
			new ListaItem("GT", "tonelada bruta", "tonelada bruta"),
			new ListaItem("GV", "gigajoule", "gigajoule"),
			new ListaItem("GW", "galón por mil pies cúbicos", "galón por mil pies cúbicos"),
			new ListaItem("GWH", "hora de gigavatios", "hora de gigavatios"),
			new ListaItem("GY", "patio bruto", "patio bruto"),
			new ListaItem("GZ", "sistema de medición", "sistema de medición"),
			new ListaItem("H1", "media página – electrónica", "media página – electrónica"),
			new ListaItem("H2", "medio litro", "medio litro"),
			new ListaItem("HA", "madeja", "madeja"),
			new ListaItem("HAR", "hectárea", "hectárea"),
			new ListaItem("HBA", "hectobar", "hectobar"),
			new ListaItem("HBX", "cien cajas", "cien cajas"),
			new ListaItem("HC", "cien cuentas", "cien cuentas"),
			new ListaItem("HD", "media docena", "media docena"),
			new ListaItem("ÉL", "centésima de quilate", "centésima de quilate"),
			new ListaItem("HF", "cien pies", "cien pies"),
			new ListaItem("HGM", "hectogramo", "hectogramo"),
			new ListaItem("HH", "cien pies cúbicos", "cien pies cúbicos"),
			new ListaItem("HI", "cien hojas", "cien hojas"),
			new ListaItem("HIU", "cien unidades internacionales", "cien unidades internacionales"),
			new ListaItem("HJ", "caballo métrico", "caballo métrico"),
			new ListaItem("HK", "cien kilogramos", "cien kilogramos"),
			new ListaItem("HL", "cien pies (lineales)", "cien pies (lineales)"),
			new ListaItem("HLT", "hectolitro", "hectolitro"),
			new ListaItem("HM", "milla por hora", "milla por hora"),
			new ListaItem("HMQ", "millones de metros cúbicos", "millones de metros cúbicos"),
			new ListaItem("HMT", "hectómetro", "hectómetro"),
			new ListaItem("HN", "milímetro convencional de mercurio", "milímetro convencional de mercurio"),
			new ListaItem("HO", "cien onzas troy", "cien onzas troy"),
			new ListaItem("HP", "milímetro convencional de agua", "milímetro convencional de agua"),
			new ListaItem("HPA", "hectolitro de alcohol puro", "hectolitro de alcohol puro"),
			new ListaItem("HS", "cien pies cuadrados", "cien pies cuadrados"),
			new ListaItem("HT", "media hora", "media hora"),
			new ListaItem("HTZ", "hertz", "hertz"),
			new ListaItem("HUR", "hora", "hora"),
			new ListaItem("HY", "cien yardas", "cien yardas"),
			new ListaItem("IA", "pulgada libra", "pulgada libra"),
			new ListaItem("IC", "contar por pulgada", "contar por pulgada"),
			new ListaItem("IE", "persona", "persona"),
			new ListaItem("IF", "pulgadas de agua", "pulgadas de agua"),
			new ListaItem("II", "columna pulgada", "columna pulgada"),
			new ListaItem("IL", "pulgada por minuto", "pulgada por minuto"),
			new ListaItem("IM", "impresión", "impresión"),
			new ListaItem("INH", "pulgada", "pulgada"),
			new ListaItem("INK", "pulgada cuadrada", "pulgada cuadrada"),
			new ListaItem("INQ", "pulgada en cubos", "pulgada en cubos"),
			new ListaItem("IP", "póliza de seguros", "póliza de seguros"),
			new ListaItem("IT", "conteo por centímetro", "conteo por centímetro"),
			new ListaItem("IU", "pulgada por segundo (velocidad lineal)", "pulgada por segundo (velocidad lineal)"),
			new ListaItem("IV", "pulgada por segundo al cuadrado (aceleración)", "pulgada por segundo al cuadrado (aceleración)"),
			new ListaItem("J2", "julios por kilogramo", "julios por kilogramo"),
			new ListaItem("JB", "jumbo", "jumbo"),
			new ListaItem("JE", "joule por kelvin", "joule por kelvin"),
			new ListaItem("JG", "jarra", "jarra"),
			new ListaItem("JK", "megajulio por kilogramo", "megajulio por kilogramo"),
			new ListaItem("JM", "megajulio por metro cúbico", "megajulio por metro cúbico"),
			new ListaItem("JO", "articulación", "articulación"),
			new ListaItem("JOU", "joule", "joule"),
			new ListaItem("JR", "tarro", "tarro"),
			new ListaItem("K1", "demanda de kilovatios", "demanda de kilovatios"),
			new ListaItem("K2", "kilovoltios amperios reactivos de demanda", "kilovoltios amperios reactivos de demanda"),
			new ListaItem("K3", "kilovoltio amperio hora reactiva", "kilovoltio amperio hora reactiva"),
			new ListaItem("K5", "amperios kilovoltios (reactivos)", "amperios kilovoltios (reactivos)"),
			new ListaItem("K6", "kilolitro", "kilolitro"),
			new ListaItem("KA", "pastel", "pastel"),
			new ListaItem("KB", "kilocharacter", "kilocharacter"),
			new ListaItem("KBA", "kilobar", "kilobar"),
			new ListaItem("KD", "kilogramo decimal", "kilogramo decimal"),
			new ListaItem("KEL", "kelvin", "kelvin"),
			new ListaItem("KF", "kilopacket", "kilopacket"),
			new ListaItem("KG", "barrilete", "barrilete"),
			new ListaItem("KGM", "kilogramo", "kilogramo"),
			new ListaItem("KGS", "kilogramo por segundo", "kilogramo por segundo"),
			new ListaItem("KHZ", "kilohercio", "kilohercio"),
			new ListaItem("KI", "Kilogramo por milímetro de ancho", "Kilogramo por milímetro de ancho"),
			new ListaItem("KJ", "kilosegmento", "kilosegmento"),
			new ListaItem("KJO", "kilojoule", "kilojoule"),
			new ListaItem("KL", "kilogramo por metro", "kilogramo por metro"),
			new ListaItem("KMH", "kilómetro por hora", "kilómetro por hora"),
			new ListaItem("KMK", "kilometro cuadrado", "kilometro cuadrado"),
			new ListaItem("KMQ", "kilogramo por metro cúbico", "kilogramo por metro cúbico"),
			new ListaItem("KNI", "kilogramo de nitrógeno", "kilogramo de nitrógeno"),
			new ListaItem("KNS", "kilogramo de sustancia nombrada", "kilogramo de sustancia nombrada"),
			new ListaItem("KNT", "nudo", "nudo"),
			new ListaItem("KO", "Milliequivalencia de potasa cáustica por gramo de producto.", "Milliequivalencia de potasa cáustica por gramo de producto."),
			new ListaItem("KPA", "kilopascal", "kilopascal"),
			new ListaItem("KPH", "kilogramo de hidróxido de potasio (potasa cáustica)", "kilogramo de hidróxido de potasio (potasa cáustica)"),
			new ListaItem("KPO", "kilogramo de óxido de potasio", "kilogramo de óxido de potasio"),
			new ListaItem("KPP", "kilogramo de pentóxido de fósforo (anhídrido fosfórico)", "kilogramo de pentóxido de fósforo (anhídrido fosfórico)"),
			new ListaItem("KR", "KilorÃ¶ntgen", "KilorÃ¶ntgen"),
			new ListaItem("KS", "mil libras por pulgada cuadrada", "mil libras por pulgada cuadrada"),
			new ListaItem("KSD", "kilogramo de sustancia 90% seca", "kilogramo de sustancia 90% seca"),
			new ListaItem("KSH", "kilogramo de hidróxido de sodio (soda cáustica)", "kilogramo de hidróxido de sodio (soda cáustica)"),
			new ListaItem("KT", "equipo", "equipo"),
			new ListaItem("KTM", "kilómetro", "kilómetro"),
			new ListaItem("KTN", "kilotonne", "kilotonne"),
			new ListaItem("KUR", "kilogramo de uranio", "kilogramo de uranio"),
			new ListaItem("KVA", "kilovoltio – ampere", "kilovoltio – ampere"),
			new ListaItem("KVR", "kilovar", "kilovar"),
			new ListaItem("KVT", "kilovoltio", "kilovoltio"),
			new ListaItem("KW", "kilogramos por milímetro", "kilogramos por milímetro"),
			new ListaItem("KWH", "kilovatios hora", "kilovatios hora"),
			new ListaItem("KWT", "kilovatio", "kilovatio"),
			new ListaItem("KX", "mililitro por kilogramo", "mililitro por kilogramo"),
			new ListaItem("L2", "litro por minuto", "litro por minuto"),
			new ListaItem("LA", "libra por pulgada cúbica", "libra por pulgada cúbica"),
			new ListaItem("LBR", "libra", "libra"),
			new ListaItem("LBT", "libra troy", "libra troy"),
			new ListaItem("LC", "centímetro lineal", "centímetro lineal"),
			new ListaItem("LD", "litro por día", "litro por día"),
			new ListaItem("LE", "lite", "lite"),
			new ListaItem("LEF", "hoja", "hoja"),
			new ListaItem("LF", "pie lineal", "pie lineal"),
			new ListaItem("LH", "hora de trabajo", "hora de trabajo"),
			new ListaItem("LI", "pulgada lineal", "pulgada lineal"),
			new ListaItem("LJ", "spray grande", "spray grande"),
			new ListaItem("LK", "enlazar", "enlazar"),
			new ListaItem("LM", "metro lineal", "metro lineal"),
			new ListaItem("LN", "longitud", "longitud"),
			new ListaItem("LO", "mucho", "mucho"),
			new ListaItem("LP", "libra liquida", "libra liquida"),
			new ListaItem("LPA", "litro de alcohol puro", "litro de alcohol puro"),
			new ListaItem("LR", "capa", "capa"),
			new ListaItem("LS", "Suma global", "Suma global"),
			new ListaItem("LTN", "ton (Reino Unido) o longton (EE. UU.)", "ton (Reino Unido) o longton (EE. UU.)"),
			new ListaItem("LTR", "litro", "litro"),
			new ListaItem("LUM", "lumen", "lumen"),
			new ListaItem("LUX", "lux", "lux"),
			new ListaItem("LX", "yarda lineal por libra", "yarda lineal por libra"),
			new ListaItem("LY", "yarda lineal", "yarda lineal"),
			new ListaItem("M0", "cinta magnética", "cinta magnética"),
			new ListaItem("M1", "miligramos por litro", "miligramos por litro"),
			new ListaItem("M4", "valor monetario", "valor monetario"),
			new ListaItem("M5", "microcurie", "microcurie"),
			new ListaItem("M7", "micropulgada", "micropulgada"),
			new ListaItem("M9", "millones de Btu por 1000 pies cúbicos", "millones de Btu por 1000 pies cúbicos"),
			new ListaItem("MA", "máquina por unidad", "máquina por unidad"),
			new ListaItem("MAL", "mega litro", "mega litro"),
			new ListaItem("MAM", "megametro", "megametro"),
			new ListaItem("MAW", "megavatio", "megavatio"),
			new ListaItem("MBE", "mil equivalentes de ladrillo estándar", "mil equivalentes de ladrillo estándar"),
			new ListaItem("MBF", "mil pies de tabla", "mil pies de tabla"),
			new ListaItem("MBR", "milibar", "milibar"),
			new ListaItem("MC", "microgramo", "microgramo"),
			new ListaItem("MCU", "milicurie", "milicurie"),
			new ListaItem("MD", "aire seco tonelada métrica", "aire seco tonelada métrica"),
			new ListaItem("MF", "miligramo por pie cuadrado por lado", "miligramo por pie cuadrado por lado"),
			new ListaItem("MGM", "miligramo", "miligramo"),
			new ListaItem("MGM", "megahercio", "megahercio"),
			new ListaItem("MIK", "milla cuadrada", "milla cuadrada"),
			new ListaItem("MIL", "mil", "mil"),
			new ListaItem("MIN", "minuto", "minuto"),
			new ListaItem("MIO", "millón", "millón"),
			new ListaItem("MIU", "millones de unidades internacionales", "millones de unidades internacionales"),
			new ListaItem("MK", "miligramo por pulgada cuadrada", "miligramo por pulgada cuadrada"),
			new ListaItem("MLD", "mil millones", "mil millones"),
			new ListaItem("MLT", "mililitro", "mililitro"),
			new ListaItem("MMK", "milímetro cuadrado", "milímetro cuadrado"),
			new ListaItem("MMQ", "milímetro cúbico", "milímetro cúbico"),
			new ListaItem("MMT", "milímetro", "milímetro"),
			new ListaItem("LUN", "mes", "mes"),
			new ListaItem("MPA", "megapascal", "megapascal"),
			new ListaItem("MQ", "mil metros", "mil metros"),
			new ListaItem("MQH", "metro cúbico por hora", "metro cúbico por hora"),
			new ListaItem("MQS", "metro cúbico por segundo", "metro cúbico por segundo"),
			new ListaItem("MSK", "metro por segundo al cuadrado", "metro por segundo al cuadrado"),
			new ListaItem("MT", "estera", "estera"),
			new ListaItem("MTK", "metro cuadrado", "metro cuadrado"),
			new ListaItem("MTQ", "Metro cúbico", "Metro cúbico"),
			new ListaItem("MTR", "metro", "metro"),
			new ListaItem("MTS", "metro por segundo", "metro por segundo"),
			new ListaItem("MV", "numero de mults", "numero de mults"),
			new ListaItem("MVA", "megavolt – ampere", "megavolt – ampere"),
			new ListaItem("MWH", "megavatios hora (1000 kW.h)", "megavatios hora (1000 kW.h)"),
			new ListaItem("N1", "calorías de la pluma", "calorías de la pluma"),
			new ListaItem("N2", "número de líneas", "número de líneas"),
			new ListaItem("N3", "punto de impresión", "punto de impresión"),
			new ListaItem("NA", "miligramo por kilogramo", "miligramo por kilogramo"),
			new ListaItem("NAR", "número de artículos", "número de artículos"),
			new ListaItem("NB", "barcaza", "barcaza"),
			new ListaItem("NBB", "número de bobinas", "número de bobinas"),
			new ListaItem("NC", "coche", "coche"),
			new ListaItem("NCL", "número de celdas", "número de celdas"),
			new ListaItem("ND", "barril neto", "barril neto"),
			new ListaItem("NE", "litro neto", "litro neto"),
			new ListaItem("NEW", "newton", "newton"),
			new ListaItem("NF", "mensaje", "mensaje"),
			new ListaItem("NG", "galón neto (nosotros)", "galón neto (nosotros)"),
			new ListaItem("NH", "hora del mensaje", "hora del mensaje"),
			new ListaItem("NI", "galón imperial neto", "galón imperial neto"),
			new ListaItem("NIU", "número de unidades internacionales", "número de unidades internacionales"),
			new ListaItem("NJ", "número de pantallas", "número de pantallas"),
			new ListaItem("NL", "carga", "carga"),
			new ListaItem("MNI", "milla nautica", "milla nautica"),
			new ListaItem("NMP", "número de paquetes", "número de paquetes"),
			new ListaItem("NN", "entrenar", "entrenar"),
			new ListaItem("NPL", "número de parcelas", "número de parcelas"),
			new ListaItem("NPR", "numero de pares", "numero de pares"),
			new ListaItem("TNP", "numero de partes", "numero de partes"),
			new ListaItem("NQ", "mho", "mho"),
			new ListaItem("NR", "micromho", "micromho"),
			new ListaItem("NRL", "número de rollos", "número de rollos"),
			new ListaItem("NT", "tonelada neta", "tonelada neta"),
			new ListaItem("NTT", "registro neto de toneladas", "registro neto de toneladas"),
			new ListaItem("NU", "medidor de newton", "medidor de newton"),
			new ListaItem("NV", "vehículo", "vehículo"),
			new ListaItem("NX", "parte por mil", "parte por mil"),
			new ListaItem("NY", "libra por aire seco tonelada métrica", "libra por aire seco tonelada métrica"),
			new ListaItem("OA", "panel", "panel"),
			new ListaItem("OHM", "ohm", "ohm"),
			new ListaItem("EN", "onza por yarda cuadrada", "onza por yarda cuadrada"),
			new ListaItem("ONZ", "onza", "onza"),
			new ListaItem("OP", "Dos paquetes", "Dos paquetes"),
			new ListaItem("OT", "hora extra", "hora extra"),
			new ListaItem("ONZ", "onza av", "onza av"),
			new ListaItem("OZA", "onza líquida (US)", "onza líquida (US)"),
			new ListaItem("OZI", "onza líquida (Reino Unido)", "onza líquida (Reino Unido)"),
			new ListaItem("P0", "pagina – electronica", "pagina – electronica"),
			new ListaItem("P1", "por ciento", "por ciento"),
			new ListaItem("P2", "libra por pie", "libra por pie"),
			new ListaItem("P3", "paquete de tres", "paquete de tres"),
			new ListaItem("P4", "paquete de cuatro", "paquete de cuatro"),
			new ListaItem("P5", "paquete de cinco", "paquete de cinco"),
			new ListaItem("P6", "paquete de seis", "paquete de seis"),
			new ListaItem("P7", "paquete de siete", "paquete de siete"),
			new ListaItem("P8", "paquete de ocho", "paquete de ocho"),
			new ListaItem("P9", "paquete de nueve", "paquete de nueve"),
			new ListaItem("PA", "paquete", "paquete"),
			new ListaItem("PAL", "pascal", "pascal"),
			new ListaItem("PB", "par de pulgadas", "par de pulgadas"),
			new ListaItem("PD", "almohadilla", "almohadilla"),
			new ListaItem("PE", "equivalente en libras", "equivalente en libras"),
			new ListaItem("PF", "palet (ascensor)", "palet (ascensor)"),
			new ListaItem("PG", "plato", "plato"),
			new ListaItem("PGL", "galón de prueba", "galón de prueba"),
			new ListaItem("Pi", "tono", "tono"),
			new ListaItem("PK", "paquete", "paquete"),
			new ListaItem("PL", "cubo", "cubo"),
			new ListaItem("PM", "porcentaje de libra", "porcentaje de libra"),
			new ListaItem("PN", "libra neta", "libra neta"),
			new ListaItem("PO", "libra por pulgada de longitud", "libra por pulgada de longitud"),
			new ListaItem("PQ", "página por pulgada", "página por pulgada"),
			new ListaItem("PR", "par", "par"),
			new ListaItem("PD", "fuerza de libra por pulgada cuadrada", "fuerza de libra por pulgada cuadrada"),
			new ListaItem("PT", "pinta", "pinta"),
			new ListaItem("PTD", "pinta seca", "pinta seca"),
			new ListaItem("PTI", "pinta (Reino Unido)", "pinta (Reino Unido)"),
			new ListaItem("PTL", "pinta liquida (US)", "pinta liquida (US)"),
			new ListaItem("PU", "bandeja / paquete de bandeja", "bandeja / paquete de bandeja"),
			new ListaItem("PV", "media pinta (US)", "media pinta (US)"),
			new ListaItem("PW", "libra por pulgada de ancho", "libra por pulgada de ancho"),
			new ListaItem("PY", "Peck Dry (US)", "Peck Dry (US)"),
			new ListaItem("PZ", "Peck Dry (Reino Unido)", "Peck Dry (Reino Unido)"),
			new ListaItem("Q3", "comida", "comida"),
			new ListaItem("QA", "página – facsímil", "página – facsímil"),
			new ListaItem("QAN", "cuarto (de un año)", "cuarto (de un año)"),
			new ListaItem("QB", "página – copia impresa", "página – copia impresa"),
			new ListaItem("QD", "cuarto de docena", "cuarto de docena"),
			new ListaItem("QH", "un cuarto de hora", "un cuarto de hora"),
			new ListaItem("QK", "cuarto de kilogramo", "cuarto de kilogramo"),
			new ListaItem("QR", "mano de papel", "mano de papel"),
			new ListaItem("QT", "cuarto de galón (US)", "cuarto de galón (US)"),
			new ListaItem("QTD", "cuarto seco (EE. UU.)", "cuarto seco (EE. UU.)"),
			new ListaItem("QTI", "cuarto de galón (Reino Unido)", "cuarto de galón (Reino Unido)"),
			new ListaItem("QTL", "cuarto líquido (US)", "cuarto líquido (US)"),
			new ListaItem("QTR", "cuarto (UK)", "cuarto (UK)"),
			new ListaItem("R1", "pica", "pica"),
			new ListaItem("R4", "caloría", "caloría"),
			new ListaItem("R9", "mil metros cúbicos", "mil metros cúbicos"),
			new ListaItem("RA", "estante", "estante"),
			new ListaItem("RD", "barra", "barra"),
			new ListaItem("RG", "anillo", "anillo"),
			new ListaItem("RH", "hora de funcionamiento o de funcionamiento", "hora de funcionamiento o de funcionamiento"),
			new ListaItem("RK", "medida métrica rollo", "medida métrica rollo"),
			new ListaItem("RL", "carrete", "carrete"),
			new ListaItem("RM", "resma", "resma"),
			new ListaItem("RN", "medida métrica de resma", "medida métrica de resma"),
			new ListaItem("RO", "rodar", "rodar"),
			new ListaItem("RP", "libra por resma", "libra por resma"),
			new ListaItem("RPM", "revoluciones por minuto", "revoluciones por minuto"),
			new ListaItem("RPS", "revoluciones por segundo", "revoluciones por segundo"),
			new ListaItem("RS", "Reiniciar", "Reiniciar"),
			new ListaItem("RT", "ingreso tonelada milla", "ingreso tonelada milla"),
			new ListaItem("RU", "correr", "correr"),
			new ListaItem("S3", "pie cuadrado por segundo", "pie cuadrado por segundo"),
			new ListaItem("S4", "metro cuadrado por segundo", "metro cuadrado por segundo"),
			new ListaItem("S5", "sesenta cuartos de pulgada", "sesenta cuartos de pulgada"),
			new ListaItem("S6", "sesión", "sesión"),
			new ListaItem("S7", "unidad de almacenamiento", "unidad de almacenamiento"),
			new ListaItem("S8", "unidad de publicidad estándar", "unidad de publicidad estándar"),
			new ListaItem("SA", "saco", "saco"),
			new ListaItem("SAN", "medio año (6 meses)", "medio año (6 meses)"),
			new ListaItem("OCS", "Puntuación", "Puntuación"),
			new ListaItem("SCR", "escrúpulo", "escrúpulo"),
			new ListaItem("SD", "libra solida", "libra solida"),
			new ListaItem("SE", "sección", "sección"),
			new ListaItem("SEC", "segundo", "segundo"),
			new ListaItem("SET", "conjunto", "conjunto"),
			new ListaItem("SG", "segmento", "segmento"),
			new ListaItem("SHT", "tonelada de envío", "tonelada de envío"),
			new ListaItem("SIE", "siemens", "siemens"),
			new ListaItem("SK", "camión cisterna dividido", "camión cisterna dividido"),
			new ListaItem("SL", "hoja de deslizamiento", "hoja de deslizamiento"),
			new ListaItem("SMI", "milla (milla estatutaria)", "milla (milla estatutaria)"),
			new ListaItem("SN", "varilla cuadrada", "varilla cuadrada"),
			new ListaItem("SO", "carrete", "carrete"),
			new ListaItem("SP", "paquete de estante", "paquete de estante"),
			new ListaItem("SQ", "cuadrado", "cuadrado"),
			new ListaItem("SR", "tira", "tira"),
			new ListaItem("SS", "hoja métrica medida", "hoja métrica medida"),
			new ListaItem("SST", "corto estándar (7200 partidos)", "corto estándar (7200 partidos)"),
			new ListaItem("ST", "hoja", "hoja"),
			new ListaItem("ITS", "piedra (Reino Unido)", "piedra (Reino Unido)"),
			new ListaItem("STN", "tonelada (US) o tonelada corta (UK / US)", "tonelada (US) o tonelada corta (UK / US)"),
			new ListaItem("SV", "patinar", "patinar"),
			new ListaItem("SO", "madeja", "madeja"),
			new ListaItem("SX", "envío", "envío"),
			new ListaItem("T0", "Línea de telecomunicaciones en servicio.", "Línea de telecomunicaciones en servicio."),
			new ListaItem("T1", "mil libras brutas", "mil libras brutas"),
			new ListaItem("T3", "mil piezas", "mil piezas"),
			new ListaItem("T4", "bolsa de mil", "bolsa de mil"),
			new ListaItem("T5", "caja de mil", "caja de mil"),
			new ListaItem("T6", "mil galones (US)", "mil galones (US)"),
			new ListaItem("T7", "mil impresiones", "mil impresiones"),
			new ListaItem("T8", "mil pulgadas lineales", "mil pulgadas lineales"),
			new ListaItem("TA", "décimo pie cúbico", "décimo pie cúbico"),
			new ListaItem("TAH", "Kiloampere hora (mil amperios hora)", "Kiloampere hora (mil amperios hora)"),
			new ListaItem("TC", "camion", "camion"),
			new ListaItem("TD", "termia", "termia"),
			new ListaItem("TE", "totalizador", "totalizador"),
			new ListaItem("TF", "diez metros cuadrados", "diez metros cuadrados"),
			new ListaItem("TI", "mil pulgadas cuadradas", "mil pulgadas cuadradas"),
			new ListaItem("TJ", "mil centímetros cuadrados", "mil centímetros cuadrados"),
			new ListaItem("TK", "tanque, rectangular", "tanque, rectangular"),
			new ListaItem("TL", "mil pies (lineales)", "mil pies (lineales)"),
			new ListaItem("TN", "estaño", "estaño"),
			new ListaItem("TNE", "tonelada (tonelada métrica)", "tonelada (tonelada métrica)"),
			new ListaItem("TP", "paquete de diez", "paquete de diez"),
			new ListaItem("TPR", "diez pares", "diez pares"),
			new ListaItem("TQ", "mil pies", "mil pies"),
			new ListaItem("TQD", "mil metros cúbicos por día", "mil metros cúbicos por día"),
			new ListaItem("TR", "diez pies cuadrados", "diez pies cuadrados"),
			new ListaItem("TRL", "trillón (EUR)", "trillón (EUR)"),
			new ListaItem("TS", "mil pies cuadrados", "mil pies cuadrados"),
			new ListaItem("TSD", "tonelada de sustancia 90% seca", "tonelada de sustancia 90% seca"),
			new ListaItem("TSH", "tonelada de vapor por hora", "tonelada de vapor por hora"),
			new ListaItem("TT", "mil metros lineales", "mil metros lineales"),
			new ListaItem("TU", "tubo", "tubo"),
			new ListaItem("TV", "mil kilogramos", "mil kilogramos"),
			new ListaItem("TW", "mil hojas", "mil hojas"),
			new ListaItem("TY", "tanque, cilíndrico", "tanque, cilíndrico"),
			new ListaItem("U1", "tratamiento", "tratamiento"),
			new ListaItem("U2", "tableta", "tableta"),
			new ListaItem("UA", "torr", "torr"),
			new ListaItem("UB", "Línea de telecomunicaciones en servicio promedio.", "Línea de telecomunicaciones en servicio promedio."),
			new ListaItem("UC", "puerto de telecomunicaciones", "puerto de telecomunicaciones"),
			new ListaItem("UD", "décimo minuto", "décimo minuto"),
			new ListaItem("UE", "décima hora", "décima hora"),
			new ListaItem("UF", "uso por línea de telecomunicación promedio", "uso por línea de telecomunicación promedio"),
			new ListaItem("UH", "diez mil yardas", "diez mil yardas"),
			new ListaItem("UM", "millones de unidades", "millones de unidades"),
			new ListaItem("VA", "voltio amperio por kilogramo", "voltio amperio por kilogramo"),
			new ListaItem("VI", "frasco", "frasco"),
			new ListaItem("VLT", "voltio", "voltio"),
			new ListaItem("VQ", "abultar", "abultar"),
			new ListaItem("VS", "visitar", "visitar"),
			new ListaItem("W2", "kilo mojado", "kilo mojado"),
			new ListaItem("W4", "dos semanas", "dos semanas"),
			new ListaItem("WA", "vatio por kilogramo", "vatio por kilogramo"),
			new ListaItem("WB", "libra mojada", "libra mojada"),
			new ListaItem("WCD", "cable", "cable"),
			new ListaItem("WE", "tonelada mojada", "tonelada mojada"),
			new ListaItem("WEB", "weber", "weber"),
			new ListaItem("WEE", "semana", "semana"),
			new ListaItem("WG", "galon de vino", "galon de vino"),
			new ListaItem("WH", "rueda", "rueda"),
			new ListaItem("WHR", "vatios hora", "vatios hora"),
			new ListaItem("WI", "peso por pulgada cuadrada", "peso por pulgada cuadrada"),
			new ListaItem("WM", "mes de trabajo", "mes de trabajo"),
			new ListaItem("WR", "envolver", "envolver"),
			new ListaItem("WSD", "estándar", "estándar"),
			new ListaItem("WTT", "vatio", "vatio"),
			new ListaItem("WW", "mililitro de agua", "mililitro de agua"),
			new ListaItem("X1", "cadena", "cadena"),
			new ListaItem("YDK", "yarda cuadrada", "yarda cuadrada"),
			new ListaItem("YDQ", "Yarda cúbica", "Yarda cúbica"),
			new ListaItem("YL", "cien yardas lineales", "cien yardas lineales"),
			new ListaItem("YRD", "yarda", "yarda"),
			new ListaItem("YT", "diez yardas", "diez yardas"),
			new ListaItem("Z1", "van de elevación", "van de elevación"),
			new ListaItem("Z2", "pecho", "pecho"),
			new ListaItem("Z3", "barril", "barril"),
			new ListaItem("Z4", "pipa", "pipa"),
			new ListaItem("Z5", "arrastrar", "arrastrar"),
			new ListaItem("Z6", "punto de conferencia", "punto de conferencia"),
			new ListaItem("Z8", "línea de noticias de ágata", "línea de noticias de ágata"),
			new ListaItem("ZP", "página", "página"),
			new ListaItem("ZZ", "mutuamente definido", "mutuamente definido"),

		};

	}
}
