//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetDIANServicios.DianFactura {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", ConfigurationName="DianFactura.facturaElectronicaPortName")]
    public interface facturaElectronicaPortName {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta EnvioFacturaElectronica(HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginEnvioFacturaElectronica(HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request, System.AsyncCallback callback, object asyncState);
        
        HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta EndEnvioFacturaElectronica(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")]
    public partial class EnvioFacturaElectronica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nITField;
        
        private string invoiceNumberField;
        
        private System.DateTime issueDateField;
        
        private byte[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
                this.RaisePropertyChanged("NIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")]
    public partial class ReceivedInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroFacturaField;
        
        private string uUIDField;
        
        private int responseField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("NumeroFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")]
    public partial class AcuseRecibo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReceivedInvoice receivedInvoiceField;
        
        private string versionField;
        
        private System.DateTime receivedDateTimeField;
        
        private System.DateTime responseDateTimeField;
        
        private int responseField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReceivedInvoice ReceivedInvoice {
            get {
                return this.receivedInvoiceField;
            }
            set {
                this.receivedInvoiceField = value;
                this.RaisePropertyChanged("ReceivedInvoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReceivedDateTime {
            get {
                return this.receivedDateTimeField;
            }
            set {
                this.receivedDateTimeField = value;
                this.RaisePropertyChanged("ReceivedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ResponseDateTime {
            get {
                return this.responseDateTimeField;
            }
            set {
                this.responseDateTimeField = value;
                this.RaisePropertyChanged("ResponseDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioFacturaElectronicaPeticion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioFacturaElectronicaPeticion", Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", Order=0)]
        public HGInetDIANServicios.DianFactura.EnvioFacturaElectronica EnvioFacturaElectronicaPeticion1;
        
        public EnvioFacturaElectronicaPeticion() {
        }
        
        public EnvioFacturaElectronicaPeticion(HGInetDIANServicios.DianFactura.EnvioFacturaElectronica EnvioFacturaElectronicaPeticion1) {
            this.EnvioFacturaElectronicaPeticion1 = EnvioFacturaElectronicaPeticion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioFacturaElectronicaRespuesta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioFacturaElectronicaRespuesta", Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", Order=0)]
        public HGInetDIANServicios.DianFactura.AcuseRecibo EnvioFacturaElectronicaRespuesta1;
        
        public EnvioFacturaElectronicaRespuesta() {
        }
        
        public EnvioFacturaElectronicaRespuesta(HGInetDIANServicios.DianFactura.AcuseRecibo EnvioFacturaElectronicaRespuesta1) {
            this.EnvioFacturaElectronicaRespuesta1 = EnvioFacturaElectronicaRespuesta1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface facturaElectronicaPortNameChannel : HGInetDIANServicios.DianFactura.facturaElectronicaPortName, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnvioFacturaElectronicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EnvioFacturaElectronicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class facturaElectronicaPortNameClient : System.ServiceModel.ClientBase<HGInetDIANServicios.DianFactura.facturaElectronicaPortName>, HGInetDIANServicios.DianFactura.facturaElectronicaPortName {
        
        private BeginOperationDelegate onBeginEnvioFacturaElectronicaDelegate;
        
        private EndOperationDelegate onEndEnvioFacturaElectronicaDelegate;
        
        private System.Threading.SendOrPostCallback onEnvioFacturaElectronicaCompletedDelegate;
        
        public facturaElectronicaPortNameClient() {
        }
        
        public facturaElectronicaPortNameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public facturaElectronicaPortNameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public facturaElectronicaPortNameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public facturaElectronicaPortNameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<EnvioFacturaElectronicaCompletedEventArgs> EnvioFacturaElectronicaCompleted;
        
        public HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta EnvioFacturaElectronica(HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request) {
            return base.Channel.EnvioFacturaElectronica(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEnvioFacturaElectronica(HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnvioFacturaElectronica(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta EndEnvioFacturaElectronica(System.IAsyncResult result) {
            return base.Channel.EndEnvioFacturaElectronica(result);
        }
        
        private System.IAsyncResult OnBeginEnvioFacturaElectronica(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request = ((HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion)(inValues[0]));
            return this.BeginEnvioFacturaElectronica(request, callback, asyncState);
        }
        
        private object[] OnEndEnvioFacturaElectronica(System.IAsyncResult result) {
            HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaRespuesta retVal = this.EndEnvioFacturaElectronica(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEnvioFacturaElectronicaCompleted(object state) {
            if ((this.EnvioFacturaElectronicaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnvioFacturaElectronicaCompleted(this, new EnvioFacturaElectronicaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnvioFacturaElectronicaAsync(HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request) {
            this.EnvioFacturaElectronicaAsync(request, null);
        }
        
        public void EnvioFacturaElectronicaAsync(HGInetDIANServicios.DianFactura.EnvioFacturaElectronicaPeticion request, object userState) {
            if ((this.onBeginEnvioFacturaElectronicaDelegate == null)) {
                this.onBeginEnvioFacturaElectronicaDelegate = new BeginOperationDelegate(this.OnBeginEnvioFacturaElectronica);
            }
            if ((this.onEndEnvioFacturaElectronicaDelegate == null)) {
                this.onEndEnvioFacturaElectronicaDelegate = new EndOperationDelegate(this.OnEndEnvioFacturaElectronica);
            }
            if ((this.onEnvioFacturaElectronicaCompletedDelegate == null)) {
                this.onEnvioFacturaElectronicaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnvioFacturaElectronicaCompleted);
            }
            base.InvokeAsync(this.onBeginEnvioFacturaElectronicaDelegate, new object[] {
                        request}, this.onEndEnvioFacturaElectronicaDelegate, this.onEnvioFacturaElectronicaCompletedDelegate, userState);
        }
    }
}
