//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloConexion : DbContext
    {
        public ModeloConexion()
            : base("name=ModeloConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblOpcionesUsuario> TblOpcionesUsuario { get; set; }
        public virtual DbSet<TblPlanes> TblPlanes { get; set; }
        public virtual DbSet<TblOpcionesPerfil> TblOpcionesPerfil { get; set; }
        public virtual DbSet<TblOpciones> TblOpciones { get; set; }
        public virtual DbSet<TblPerfiles> TblPerfiles { get; set; }
        public virtual DbSet<TblConfiguracionInteroperabilidad> TblConfiguracionInteroperabilidad { get; set; }
        public virtual DbSet<TblPlanesTransacciones> TblPlanesTransacciones { get; set; }
        public virtual DbSet<TblAlertas> TblAlertas { get; set; }
        public virtual DbSet<TblFormatos> TblFormatos { get; set; }
        public virtual DbSet<TblUsuarios> TblUsuarios { get; set; }
        public virtual DbSet<TblCorreosRecepcion> TblCorreosRecepcion { get; set; }
        public virtual DbSet<TblOpcionesERP> TblOpcionesERP { get; set; }
        public virtual DbSet<TblDocumentos> TblDocumentos { get; set; }
        public virtual DbSet<TblPagosElectronicos> TblPagosElectronicos { get; set; }
        public virtual DbSet<TblEmpresas> TblEmpresas { get; set; }
        public virtual DbSet<TblEmpresasResoluciones> TblEmpresasResoluciones { get; set; }
    }
}
