//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloConexion : DbContext
    {
        public ModeloConexion()
            : base("name=ModeloConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblDocumentos> TblDocumentos { get; set; }
        public virtual DbSet<TblEmpresas> TblEmpresas { get; set; }
        public virtual DbSet<TblEmpresasResoluciones> TblEmpresasResoluciones { get; set; }
        public virtual DbSet<TblOpciones> TblOpciones { get; set; }
        public virtual DbSet<TblOpcionesPerfil> TblOpcionesPerfil { get; set; }
        public virtual DbSet<TblOpcionesUsuario> TblOpcionesUsuario { get; set; }
        public virtual DbSet<TblPerfiles> TblPerfiles { get; set; }
        public virtual DbSet<TblPlanes> TblPlanes { get; set; }
        public virtual DbSet<TblPlanesTransacciones> TblPlanesTransacciones { get; set; }
        public virtual DbSet<TblUsuarios> TblUsuarios { get; set; }
        public virtual DbSet<TblUsuariosPorPerfil> TblUsuariosPorPerfil { get; set; }
    }
}
