//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDocumentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblDocumentos()
        {
            this.TblPagosElectronicos = new HashSet<TblPagosElectronicos>();
        }
    
        public System.Guid StrIdSeguridad { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public int IntDocTipo { get; set; }
        public string StrEmpresaFacturador { get; set; }
        public string StrNumResolucion { get; set; }
        public string StrPrefijo { get; set; }
        public long IntNumero { get; set; }
        public string StrCufe { get; set; }
        public System.DateTime DatFechaDocumento { get; set; }
        public System.DateTime DatFechaVencDocumento { get; set; }
        public string StrObligadoIdRegistro { get; set; }
        public string StrEmpresaAdquiriente { get; set; }
        public short IntAdquirienteRecibo { get; set; }
        public Nullable<System.DateTime> DatAdquirienteFechaRecibo { get; set; }
        public string StrAdquirienteMvoRechazo { get; set; }
        public decimal IntVlrTotal { get; set; }
        public string StrUrlArchivoUbl { get; set; }
        public string StrUrlArchivoPdf { get; set; }
        public string StrUrlArchivoZip { get; set; }
        public Nullable<System.Guid> StrIdPlanTransaccion { get; set; }
        public short IntIdEstado { get; set; }
        public System.DateTime DatFechaActualizaEstado { get; set; }
    
        public virtual TblPlanesTransacciones TblPlanesTransacciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPagosElectronicos> TblPagosElectronicos { get; set; }
        public virtual TblEmpresasResoluciones TblEmpresasResoluciones { get; set; }
        public virtual TblEmpresas TblEmpresasAdquiriente { get; set; }
        public virtual TblEmpresas TblEmpresasFacturador { get; set; }
    }
}
