//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDocumentos
    {
        public System.Guid StrIdSeguridad { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public Nullable<int> IntDocTipo { get; set; }
        public int IntIdEmpresa { get; set; }
        public int IntIdEmpresaResolucion { get; set; }
        public string StrPrefijo { get; set; }
        public int IntNumero { get; set; }
        public string StrCufe { get; set; }
        public System.DateTime DatFechaDocumento { get; set; }
        public System.DateTime DatFechaVencDocumento { get; set; }
        public string StrObligadoIdRegistro { get; set; }
        public int IntIdEmpresaAdquiriente { get; set; }
        public short IntAdquirienteRecibo { get; set; }
        public Nullable<System.DateTime> DatAdquirienteFechaRecibo { get; set; }
        public string StrAdquirienteMvoRechazo { get; set; }
        public decimal IntVlrTotal { get; set; }
        public string StrUrlArchivoUbl { get; set; }
        public string StrUrlArchivoPdf { get; set; }
        public string StrUrlArchivoZip { get; set; }
        public System.Guid StrIdPlanTransaccion { get; set; }
        public short IntIdEstado { get; set; }
        public System.DateTime DatFechaActualizaEstado { get; set; }
    
        public virtual TblEmpresas TblEmpresas { get; set; }
        public virtual TblEmpresas TblEmpresas1 { get; set; }
        public virtual TblEmpresasResoluciones TblEmpresasResoluciones { get; set; }
    }
}
