//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpresasResoluciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmpresasResoluciones()
        {
            this.TblDocumentos = new HashSet<TblDocumentos>();
        }
    
        public string StrEmpresa { get; set; }
        public string StrNumResolucion { get; set; }
        public string StrPrefijo { get; set; }
        public int IntRangoInicial { get; set; }
        public int IntRangoFinal { get; set; }
        public System.DateTime DatFechaVigenciaDesde { get; set; }
        public System.DateTime DatFechaVigenciaHasta { get; set; }
        public string StrClaveTecnica { get; set; }
        public short IntIdPlantillaPdf { get; set; }
        public short IntIdPlantillaMail { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
        public string StrObservaciones { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public string StrRespuestaServicioWeb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentos> TblDocumentos { get; set; }
        public virtual TblEmpresas TblEmpresas { get; set; }
    }
}
