//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmpresas()
        {
            this.TblDocumentosAdquiriente = new HashSet<TblDocumentos>();
            this.TblDocumentosFacturador = new HashSet<TblDocumentos>();
            this.TblEmpresasResoluciones = new HashSet<TblEmpresasResoluciones>();
            this.TblOpcionesUsuario = new HashSet<TblOpcionesUsuario>();
            this.TblPlanesTransacciones = new HashSet<TblPlanesTransacciones>();
            this.TblUsuarios = new HashSet<TblUsuarios>();
        }
    
        public string StrIdentificacion { get; set; }
        public short IntIdentificacionDv { get; set; }
        public string StrTipoIdentificacion { get; set; }
        public string StrRazonSocial { get; set; }
        public string StrMail { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public string StrObservaciones { get; set; }
        public System.Guid StrSerial { get; set; }
        public bool IntAdquiriente { get; set; }
        public bool IntObligado { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
        public byte IntHabilitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentos> TblDocumentosAdquiriente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentos> TblDocumentosFacturador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpresasResoluciones> TblEmpresasResoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOpcionesUsuario> TblOpcionesUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPlanesTransacciones> TblPlanesTransacciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios> TblUsuarios { get; set; }
    }
}
