//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGestionAnexos
    {
        public System.Guid StrIdArchivo { get; set; }
        public System.Guid StrIdSeguridadDoc { get; set; }
        public string StrNombreArchivo { get; set; }
        public string StrUrlArchivo { get; set; }
        public short IntProceso { get; set; }
        public int IntPesoArchivo { get; set; }
        public string StrObservaciones { get; set; }
    
        public virtual TblDocumentos TblDocumentos { get; set; }
    }
}
