//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblImportacionDoc
    {
        public System.Guid IdSeguridad { get; set; }
        public int IdProceso { get; set; }
        public string StrObservaciones { get; set; }
        public string StrTipodoc { get; set; }
        public string StrCufe { get; set; }
        public string IntNumero { get; set; }
        public string StrPrefijo { get; set; }
        public System.DateTime DatFechaEmision { get; set; }
        public System.DateTime DatFechaRecepcion { get; set; }
        public string StrEmpresaFacturador { get; set; }
        public string StrNombreFacturador { get; set; }
        public string StrEmpresaAdquiriente { get; set; }
        public string StrNombreAdquiriente { get; set; }
        public decimal IntVlrIva { get; set; }
        public decimal IntVlrIca { get; set; }
        public decimal IntVlrIPC { get; set; }
        public decimal IntVlrTotal { get; set; }
        public string StrEstadoDian { get; set; }
        public string StrGrupo { get; set; }
    }
}
