//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOpcionesUsuario
    {
        public int IntIdOpcion { get; set; }
        public int IntIdUsuario { get; set; }
        public bool IntConsultar { get; set; }
        public bool IntAgregar { get; set; }
        public bool IntEditar { get; set; }
        public bool IntEliminar { get; set; }
        public bool IntAnular { get; set; }
        public bool IntGestion { get; set; }
    
        public virtual TblOpciones TblOpciones { get; set; }
        public virtual TblUsuarios TblUsuarios { get; set; }
    }
}
