//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOpciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOpciones()
        {
            this.TblOpcionesPerfil = new HashSet<TblOpcionesPerfil>();
            this.TblOpcionesUsuario = new HashSet<TblOpcionesUsuario>();
        }
    
        public int IntId { get; set; }
        public Nullable<int> IntIdDependencia { get; set; }
        public string StrDescripcion { get; set; }
        public bool IntHabilitado { get; set; }
        public short IntIdPerfilSuperior { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
        public string StrClaseMenu { get; set; }
        public string StrRutaMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOpcionesPerfil> TblOpcionesPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOpcionesUsuario> TblOpcionesUsuario { get; set; }
    }
}
