//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOpciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOpciones()
        {
            this.TblOpcionesPerfil = new HashSet<TblOpcionesPerfil>();
            this.TblOpcionesUsuario = new HashSet<TblOpcionesUsuario>();
        }
    
        public int IntId { get; set; }
        public Nullable<int> IntIdDependencia { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public bool IntHabilitado { get; set; }
        public short IntIdPerfilSuperior { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOpcionesPerfil> TblOpcionesPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOpcionesUsuario> TblOpcionesUsuario { get; set; }
    }
}
