//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOpcionesPerfil
    {
        public int IntIdOpcion { get; set; }
        public short IntIdPerfil { get; set; }
        public bool IntConsultar { get; set; }
        public bool IntAgregar { get; set; }
        public bool IntEditar { get; set; }
        public bool IntEliminar { get; set; }
        public bool IntAnular { get; set; }
        public bool IntGestion { get; set; }
    
        public virtual TblPerfiles TblPerfiles { get; set; }
        public virtual TblOpciones TblOpciones { get; set; }
    }
}
