//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPagosElectronicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPagosElectronicos()
        {
            this.TblPagosDetalles = new HashSet<TblPagosDetalles>();
        }
    
        public System.Guid StrIdRegistro { get; set; }
        public string StrIdSeguridadPago { get; set; }
        public string StrIdPlataforma { get; set; }
        public Nullable<System.Guid> StrIdRegistro2 { get; set; }
        public Nullable<System.Guid> StrIdSeguridadPlanes { get; set; }
        public string StrEmpresaFacturador { get; set; }
        public string StrEmpresaAdquiriente { get; set; }
        public System.DateTime DatFechaRegistro { get; set; }
        public Nullable<System.DateTime> DatFechaVerificacion { get; set; }
        public int IntEstadoPago { get; set; }
        public string StrTicketID { get; set; }
        public string StrTransaccionCUS { get; set; }
        public decimal IntValorPago { get; set; }
        public Nullable<int> IntClicloTransaccion { get; set; }
        public string StrCodigoBanco { get; set; }
        public Nullable<int> IntCodigoServicio { get; set; }
        public Nullable<int> IntFormaPago { get; set; }
        public string StrCodigoFranquicia { get; set; }
        public string StrMensaje { get; set; }
        public string StrCampo1 { get; set; }
        public string StrCampo2 { get; set; }
        public string StrCampo3 { get; set; }
        public bool IntProcesado { get; set; }
    
        public virtual TblEmpresas TblEmpresas { get; set; }
        public virtual TblEmpresas TblEmpresas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPagosDetalles> TblPagosDetalles { get; set; }
        public virtual TblPlanesTransacciones TblPlanesTransacciones { get; set; }
    }
}
