//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProcesoCorreo
    {
        public System.Guid StrIdSeguridadDoc { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
        public System.DateTime DatFecha { get; set; }
        public bool IntEnvioMail { get; set; }
        public string StrIdMensaje { get; set; }
        public bool IntValidadoMail { get; set; }
        public Nullable<System.DateTime> DatFechaValidado { get; set; }
        public string StrMailEnviado { get; set; }
        public int IntEventoResp { get; set; }
    }
}
