//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPlanes
    {
        public short IntId { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public short IntNumeroTransacciones { get; set; }
        public decimal IntValor { get; set; }
        public string StrUrlImagen { get; set; }
        public string StrObservaciones { get; set; }
        public bool IntHabilitado { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
    }
}
