//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProveedores()
        {
            this.TblDocumentos = new HashSet<TblDocumentos>();
            this.TblDocumentos1 = new HashSet<TblDocumentos>();
        }
    
        public string StrIdentificacion { get; set; }
        public string StrRazonSocial { get; set; }
        public string StrMail { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public string StrObservaciones { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public string StrTelefono { get; set; }
        public string StrRutaFTP { get; set; }
        public string StrUsuarioReceptor { get; set; }
        public string StrClaveReceptor { get; set; }
        public System.DateTime DatFechaExpiracionReceptor { get; set; }
        public string StrUsuarioEmisor { get; set; }
        public string StrClaveEmisor { get; set; }
        public System.DateTime DatFechaExpiracionEmisor { get; set; }
        public string StrTokenEmisor { get; set; }
        public Nullable<System.DateTime> DatFechaTokenEmisor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentos> TblDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentos> TblDocumentos1 { get; set; }
    }
}
