//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPlanes
    {
        public short IntId { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public short IntNumeroTransacciones { get; set; }
        public decimal IntValor { get; set; }
        public string StrUrlImagen { get; set; }
        public string StrObservaciones { get; set; }
        public bool IntHabilitado { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
    }
}
