//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPagosDetalles
    {
        public System.Guid StrIdPagoPrincipal { get; set; }
        public System.Guid StrIdSeguridadDoc { get; set; }
        public decimal IntValorPago { get; set; }
    
        public virtual TblDocumentos TblDocumentos { get; set; }
        public virtual TblPagosElectronicos TblPagosElectronicos { get; set; }
    }
}
