//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRegistroRecepcion
    {
        public System.Guid StrId { get; set; }
        public System.DateTime DatFechaRegistro { get; set; }
        public System.DateTime DatFechaCorreo { get; set; }
        public string StrRemitente { get; set; }
        public string StrAsunto { get; set; }
        public bool IntEstado { get; set; }
        public string StrObservaciones { get; set; }
    }
}
