//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUsuarios()
        {
            this.TblOpcionesUsuario = new HashSet<TblOpcionesUsuario>();
            this.TblPlanesTransacciones = new HashSet<TblPlanesTransacciones>();
        }
    
        public string StrEmpresa { get; set; }
        public string StrUsuario { get; set; }
        public string StrClave { get; set; }
        public string StrNombres { get; set; }
        public string StrApellidos { get; set; }
        public string StrCargo { get; set; }
        public string StrTelefono { get; set; }
        public string StrExtension { get; set; }
        public string StrCelular { get; set; }
        public string StrMail { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public short IntIdEstado { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
        public Nullable<System.DateTime> DatFechaCambioClave { get; set; }
        public Nullable<System.Guid> StrIdCambioClave { get; set; }
        public Nullable<System.Guid> StrToken { get; set; }
        public Nullable<System.DateTime> DatFechaUltimoIngreso { get; set; }
    
        public virtual TblEmpresas TblEmpresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOpcionesUsuario> TblOpcionesUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPlanesTransacciones> TblPlanesTransacciones { get; set; }
    }
}
