//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuariosPorPerfil
    {
        public short IntIdPerfil { get; set; }
        public int IntIdUsuario { get; set; }
        public bool Activado { get; set; }
    
        public virtual TblPerfiles TblPerfiles { get; set; }
        public virtual TblUsuarios TblUsuarios { get; set; }
    }
}
