//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaData.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuariosPagos
    {
        public string StrEmpresaFacturador { get; set; }
        public string StrUsuario { get; set; }
        public string StrEmpresaAdquiriente { get; set; }
        public string StrClave { get; set; }
        public string StrNombres { get; set; }
        public string StrApellidos { get; set; }
        public string StrTelefono { get; set; }
        public string StrMail { get; set; }
        public System.DateTime DatFechaRegistro { get; set; }
        public System.DateTime DatFechaActualizacion { get; set; }
        public short IntIdEstado { get; set; }
        public System.Guid StrIdSeguridad { get; set; }
        public Nullable<System.DateTime> DatFechaCambioClave { get; set; }
        public Nullable<System.Guid> StrIdCambioClave { get; set; }
        public Nullable<System.Guid> StrToken { get; set; }
        public Nullable<System.DateTime> DatFechaUltimoIngreso { get; set; }
    }
}
