//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectronicaWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpcionesPermisos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpcionesPermisos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HGInetMiFacturaElectronicaWeb.Properties.OpcionesPermisos", typeof(OpcionesPermisos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1333.
        /// </summary>
        internal static string ActivacionSerial {
            get {
                return ResourceManager.GetString("ActivacionSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1312.
        /// </summary>
        internal static string ConsultaAcuseRecibo {
            get {
                return ResourceManager.GetString("ConsultaAcuseRecibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1314.
        /// </summary>
        internal static string ConsultaAcuseTacito {
            get {
                return ResourceManager.GetString("ConsultaAcuseTacito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1342.
        /// </summary>
        internal static string ConsultaDocumentoCliente {
            get {
                return ResourceManager.GetString("ConsultaDocumentoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1321.
        /// </summary>
        internal static string ConsultaDocumentosAdquiriente {
            get {
                return ResourceManager.GetString("ConsultaDocumentosAdquiriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1311.
        /// </summary>
        internal static string ConsultaDocumentosFacturador {
            get {
                return ResourceManager.GetString("ConsultaDocumentosFacturador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1322.
        /// </summary>
        internal static string ConsultaPagosAdquiriente {
            get {
                return ResourceManager.GetString("ConsultaPagosAdquiriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1313.
        /// </summary>
        internal static string ConsultaPagosFacturador {
            get {
                return ResourceManager.GetString("ConsultaPagosFacturador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1343.
        /// </summary>
        internal static string DocumetosAdmin {
            get {
                return ResourceManager.GetString("DocumetosAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1332.
        /// </summary>
        internal static string Empresas {
            get {
                return ResourceManager.GetString("Empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13.
        /// </summary>
        internal static string FacturacionElectronicaPrincipal {
            get {
                return ResourceManager.GetString("FacturacionElectronicaPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1334.
        /// </summary>
        internal static string PlanesTransacciones {
            get {
                return ResourceManager.GetString("PlanesTransacciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1341.
        /// </summary>
        internal static string ProcesarDocumentos {
            get {
                return ResourceManager.GetString("ProcesarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1331.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
    }
}
