//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetFeAPI.ServicioPagosElectronicos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagoElectronicoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio.Respuestas")]
    [System.SerializableAttribute()]
    public partial class PagoElectronicoRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HGInetFeAPI.ServicioPagosElectronicos.PagoElectronicoRespuestaDetalle> DetallesPagosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFeAPI.ServicioPagosElectronicos.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cufe {
            get {
                return this.CufeField;
            }
            set {
                if ((object.ReferenceEquals(this.CufeField, value) != true)) {
                    this.CufeField = value;
                    this.RaisePropertyChanged("Cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HGInetFeAPI.ServicioPagosElectronicos.PagoElectronicoRespuestaDetalle> DetallesPagos {
            get {
                return this.DetallesPagosField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesPagosField, value) != true)) {
                    this.DetallesPagosField = value;
                    this.RaisePropertyChanged("DetallesPagos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentoTipo {
            get {
                return this.DocumentoTipoField;
            }
            set {
                if ((this.DocumentoTipoField.Equals(value) != true)) {
                    this.DocumentoTipoField = value;
                    this.RaisePropertyChanged("DocumentoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFeAPI.ServicioPagosElectronicos.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDocumento {
            get {
                return this.FechaDocumentoField;
            }
            set {
                if ((this.FechaDocumentoField.Equals(value) != true)) {
                    this.FechaDocumentoField = value;
                    this.RaisePropertyChanged("FechaDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroResolucion {
            get {
                return this.NumeroResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroResolucionField, value) != true)) {
                    this.NumeroResolucionField = value;
                    this.RaisePropertyChanged("NumeroResolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HGInetFeAPI.ServicioPagosElectronicos.CodigoError CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HGInetFeAPI.ServicioPagosElectronicos.CodigoError Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagoElectronicoRespuestaDetalle", Namespace="http://schemas.datacontract.org/2004/07/HGInetMiFacturaElectonicaData.ModeloServi" +
        "cio.Respuestas")]
    [System.SerializableAttribute()]
    public partial class PagoElectronicoRespuestaDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FranquiciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PagoEstadoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaCUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaPago {
            get {
                return this.FormaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaPagoField, value) != true)) {
                    this.FormaPagoField = value;
                    this.RaisePropertyChanged("FormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Franquicia {
            get {
                return this.FranquiciaField;
            }
            set {
                if ((object.ReferenceEquals(this.FranquiciaField, value) != true)) {
                    this.FranquiciaField = value;
                    this.RaisePropertyChanged("Franquicia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPago {
            get {
                return this.IdPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPagoField, value) != true)) {
                    this.IdPagoField = value;
                    this.RaisePropertyChanged("IdPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagoEstado {
            get {
                return this.PagoEstadoField;
            }
            set {
                if ((this.PagoEstadoField.Equals(value) != true)) {
                    this.PagoEstadoField = value;
                    this.RaisePropertyChanged("PagoEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PagoEstadoDescripcion {
            get {
                return this.PagoEstadoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.PagoEstadoDescripcionField, value) != true)) {
                    this.PagoEstadoDescripcionField = value;
                    this.RaisePropertyChanged("PagoEstadoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenciaCUS {
            get {
                return this.ReferenciaCUSField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaCUSField, value) != true)) {
                    this.ReferenciaCUSField = value;
                    this.RaisePropertyChanged("ReferenciaCUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketID {
            get {
                return this.TicketIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketIDField, value) != true)) {
                    this.TicketIDField = value;
                    this.RaisePropertyChanged("TicketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodigoError", Namespace="http://schemas.datacontract.org/2004/07/LibreriaGlobalHGInet.Error")]
    public enum CodigoError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_NO_CONTROLADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EN_SERVIDOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VALIDACION = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_AGREGAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_EDITAR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_ELIMINAR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR_LICENCIA = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NINGUNO = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", ConfigurationName="ServicioPagosElectronicos.ServicioPagosElectronicos")]
    public interface ServicioPagosElectronicos {
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/TestResponse")]
        HGInetFeAPI.ServicioPagosElectronicos.TestResponse Test(HGInetFeAPI.ServicioPagosElectronicos.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/Test", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/TestResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioPagosElectronicos.TestResponse> TestAsync(HGInetFeAPI.ServicioPagosElectronicos.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorCodigo" +
            "Registro", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorCodigo" +
            "RegistroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HGInetFeAPI.ServicioPagosElectronicos.Error), Action="ConsultaPorCodigoRegistro", Name="Error")]
        HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroResponse ConsultaPorCodigoRegistro(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorCodigo" +
            "Registro", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorCodigo" +
            "RegistroResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroResponse> ConsultaPorCodigoRegistroAsync(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorFechaE" +
            "laboracion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorFechaE" +
            "laboracionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HGInetFeAPI.ServicioPagosElectronicos.Error), Action="ConsultaPorFechaElaboracion", Name="Error")]
        HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionResponse ConsultaPorFechaElaboracion(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorFechaE" +
            "laboracion", ReplyAction="HGInetFacturaElectronica.ServiciosWcf/ServicioPagosElectronicos/ConsultaPorFechaE" +
            "laboracionResponse")]
        System.Threading.Tasks.Task<HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionResponse> ConsultaPorFechaElaboracionAsync(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorCodigoRegistro", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorCodigoRegistroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string DataKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=1)]
        public string Identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=2)]
        public string CodigosRegistros;
        
        public ConsultaPorCodigoRegistroRequest() {
        }
        
        public ConsultaPorCodigoRegistroRequest(string DataKey, string Identificacion, string CodigosRegistros) {
            this.DataKey = DataKey;
            this.Identificacion = Identificacion;
            this.CodigosRegistros = CodigosRegistros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorCodigoRegistroResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorCodigoRegistroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFeAPI.ServicioPagosElectronicos.PagoElectronicoRespuesta> ConsultaPorCodigoRegistroResult;
        
        public ConsultaPorCodigoRegistroResponse() {
        }
        
        public ConsultaPorCodigoRegistroResponse(System.Collections.Generic.List<HGInetFeAPI.ServicioPagosElectronicos.PagoElectronicoRespuesta> ConsultaPorCodigoRegistroResult) {
            this.ConsultaPorCodigoRegistroResult = ConsultaPorCodigoRegistroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorFechaElaboracion", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorFechaElaboracionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public string DataKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=1)]
        public string Identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=2)]
        public System.DateTime FechaInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=3)]
        public System.DateTime FechaFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=4)]
        public bool Procesados;
        
        public ConsultaPorFechaElaboracionRequest() {
        }
        
        public ConsultaPorFechaElaboracionRequest(string DataKey, string Identificacion, System.DateTime FechaInicial, System.DateTime FechaFinal, bool Procesados) {
            this.DataKey = DataKey;
            this.Identificacion = Identificacion;
            this.FechaInicial = FechaInicial;
            this.FechaFinal = FechaFinal;
            this.Procesados = Procesados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPorFechaElaboracionResponse", WrapperNamespace="HGInetFacturaElectronica.ServiciosWcf", IsWrapped=true)]
    public partial class ConsultaPorFechaElaboracionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HGInetFacturaElectronica.ServiciosWcf", Order=0)]
        public System.Collections.Generic.List<HGInetFeAPI.ServicioPagosElectronicos.PagoElectronicoRespuesta> ConsultaPorFechaElaboracionResult;
        
        public ConsultaPorFechaElaboracionResponse() {
        }
        
        public ConsultaPorFechaElaboracionResponse(System.Collections.Generic.List<HGInetFeAPI.ServicioPagosElectronicos.PagoElectronicoRespuesta> ConsultaPorFechaElaboracionResult) {
            this.ConsultaPorFechaElaboracionResult = ConsultaPorFechaElaboracionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioPagosElectronicosChannel : HGInetFeAPI.ServicioPagosElectronicos.ServicioPagosElectronicos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPagosElectronicosClient : System.ServiceModel.ClientBase<HGInetFeAPI.ServicioPagosElectronicos.ServicioPagosElectronicos>, HGInetFeAPI.ServicioPagosElectronicos.ServicioPagosElectronicos {
        
        public ServicioPagosElectronicosClient() {
        }
        
        public ServicioPagosElectronicosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPagosElectronicosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPagosElectronicosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPagosElectronicosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HGInetFeAPI.ServicioPagosElectronicos.TestResponse Test(HGInetFeAPI.ServicioPagosElectronicos.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioPagosElectronicos.TestResponse> TestAsync(HGInetFeAPI.ServicioPagosElectronicos.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroResponse ConsultaPorCodigoRegistro(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroRequest request) {
            return base.Channel.ConsultaPorCodigoRegistro(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroResponse> ConsultaPorCodigoRegistroAsync(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorCodigoRegistroRequest request) {
            return base.Channel.ConsultaPorCodigoRegistroAsync(request);
        }
        
        public HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionResponse ConsultaPorFechaElaboracion(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionRequest request) {
            return base.Channel.ConsultaPorFechaElaboracion(request);
        }
        
        public System.Threading.Tasks.Task<HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionResponse> ConsultaPorFechaElaboracionAsync(HGInetFeAPI.ServicioPagosElectronicos.ConsultaPorFechaElaboracionRequest request) {
            return base.Channel.ConsultaPorFechaElaboracionAsync(request);
        }
    }
}
