//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMonitorServController.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constantes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HGInetMonitorServController.Properties.Constantes", typeof(Constantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ObjetoJson.
        /// </summary>
        internal static string CarpetaObjetoJson {
            get {
                return ResourceManager.GetString("CarpetaObjetoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///	&quot;DataKey&quot;: &quot;b02fe5c200434a2cb1dc9cc4c037b6cfa2163ca6ed182ed07407fd775fffd0fb668c54ea1fc96d3b4376c2af66a75752c8f185240322821e793e492f955f2aa0&quot;,
        ///	&quot;CodigoRegistro&quot;: &quot;9fd43ae2-a5fb-42c1-82cb-452d4e215991&quot;,
        ///	&quot;Documento&quot;: 990001170,
        ///	&quot;DocumentoRef&quot;: null,
        ///	&quot;PedidoRef&quot;: null,
        ///	&quot;NumeroResolucion&quot;: &quot;18760000001&quot;,
        ///	&quot;Cufe&quot;: &quot;0477a2b9ba7ecb7cdf6f93d9fd834f1ed359e89d292f5b2e2f716a1d0804f443ad4c91ffb321f450e477ee9016fe92d9&quot;,
        ///	&quot;Prefijo&quot;: &quot;SETP&quot;,
        ///	&quot;Fecha&quot;: &quot;2020-09-25T14:49:24&quot;,
        ///	&quot;FechaVence&quot;: &quot;2020-09-25T00:00:00&quot;,
        ///	&quot;N [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObjetoJson {
            get {
                return ResourceManager.GetString("ObjetoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://hgi#.hgidocs.co/.
        /// </summary>
        internal static string RutaPlataformaHgi {
            get {
                return ResourceManager.GetString("RutaPlataformaHgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://Serv#.hgidocs.co/.
        /// </summary>
        internal static string RutaPlataformaIntegrador {
            get {
                return ResourceManager.GetString("RutaPlataformaIntegrador", resourceCulture);
            }
        }
    }
}
