//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGInetMiFacturaElectonicaController.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constantes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HGInetMiFacturaElectonicaController.Properties.Constantes", typeof(Constantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso Plataforma HGInet Factura Electrónica.
        /// </summary>
        public static string AsuntoEmailBienvenida {
            get {
                return ResourceManager.GetString("AsuntoEmailBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial de activacion HGInet Factura Electrónica.
        /// </summary>
        public static string AsuntoEnviaSerial {
            get {
                return ResourceManager.GetString("AsuntoEnviaSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación Electrónica.
        /// </summary>
        public static string AsuntoNotificacionDocumento {
            get {
                return ResourceManager.GetString("AsuntoNotificacionDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tic@hgi.com.co.
        /// </summary>
        public static string EmailCopiaOculta {
            get {
                return ResourceManager.GetString("EmailCopiaOculta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a notificaciones@mifacturaenlinea.com.co.
        /// </summary>
        public static string EmailRemitente {
            get {
                return ResourceManager.GetString("EmailRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 811021438.
        /// </summary>
        public static string NitResolucionconPrefijo {
            get {
                return ResourceManager.GetString("NitResolucionconPrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 811021438.
        /// </summary>
        public static string NitResolucionsinPrefijo {
            get {
                return ResourceManager.GetString("NitResolucionsinPrefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HGInet Factura Electrónica.
        /// </summary>
        public static string NombreRemitenteEmail {
            get {
                return ResourceManager.GetString("NombreRemitenteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Views/Pages/AcuseRecibo.aspx?id_seguridad={id_seguridad}.
        /// </summary>
        public static string PaginaAcuseRecibo {
            get {
                return ResourceManager.GetString("PaginaAcuseRecibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Views/Login/RestablecerClave.aspx?id_seguridad={id_seguridad}.
        /// </summary>
        public static string PaginaRestablecerClave {
            get {
                return ResourceManager.GetString("PaginaRestablecerClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRUE.
        /// </summary>
        public static string PrefijoResolucionPruebas {
            get {
                return ResourceManager.GetString("PrefijoResolucionPruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9000000033394696.
        /// </summary>
        public static string ResolucionPruebas {
            get {
                return ResourceManager.GetString("ResolucionPruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://habilitacion.mifacturaenlinea.com.co.
        /// </summary>
        public static string RutaAccesoPlataforma {
            get {
                return ResourceManager.GetString("RutaAccesoPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FacturaElectronica\\.
        /// </summary>
        public static string RutaHGInetFacturaElectronica {
            get {
                return ResourceManager.GetString("RutaHGInetFacturaElectronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interoperabilidad\\operacion\\envio\\.
        /// </summary>
        public static string RutaInteroperabilidadEnvio {
            get {
                return ResourceManager.GetString("RutaInteroperabilidadEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interoperabilidad\\publico\\.
        /// </summary>
        public static string RutaInteroperabilidadFtp {
            get {
                return ResourceManager.GetString("RutaInteroperabilidadFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interoperabilidad\\operacion\\recepcion\\.
        /// </summary>
        public static string RutaInteroperabilidadRecepcion {
            get {
                return ResourceManager.GetString("RutaInteroperabilidadRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_documento_acuse.html.
        /// </summary>
        public static string RutaPlantillaAcuse {
            get {
                return ResourceManager.GetString("RutaPlantillaAcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_bienvenida_adquiriente.html.
        /// </summary>
        public static string RutaPlantillaBienvenidaAdquiriente {
            get {
                return ResourceManager.GetString("RutaPlantillaBienvenidaAdquiriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_bienvenida_facturador.html.
        /// </summary>
        public static string RutaPlantillaBienvenidaObligado {
            get {
                return ResourceManager.GetString("RutaPlantillaBienvenidaObligado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_envio_serial.html.
        /// </summary>
        public static string RutaPlantillaEnviarSerial {
            get {
                return ResourceManager.GetString("RutaPlantillaEnviarSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_documento.html.
        /// </summary>
        public static string RutaPlantillaHtmlDocumentos {
            get {
                return ResourceManager.GetString("RutaPlantillaHtmlDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_recarga_transacciones.html.
        /// </summary>
        public static string RutaPlantillaRecarga {
            get {
                return ResourceManager.GetString("RutaPlantillaRecarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emails\\plantilla_restablecer_clave.html.
        /// </summary>
        public static string RutaPlantillaRestablecer {
            get {
                return ResourceManager.GetString("RutaPlantillaRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 573163494083,573136469239,573104935257,573053954360.
        /// </summary>
        public static string SmsCelulares {
            get {
                return ResourceManager.GetString("SmsCelulares", resourceCulture);
            }
        }
    }
}
